"use client";
import { useEffect, useRef, useState } from "react";
import { useAdminAuth } from "@/lib/store/admin-auth";
import { adminShellSessionKey } from "@/lib/admin/shell-authorities";
import { canAccessResolvedPath, resolveVisibleDomains } from "@/lib/nav/console-nav";
import { accountVersion, canReplayGroupCommand, groupPendingCommands, observedVersion, supportGroupClient, type GroupPendingRecord, type QualificationKind, type QualificationStatus, type SupportGroup, type SupportGroupDetail, type SupportGroupMember, type SupportQualifications } from "@/lib/admin/support-group-client";
import { Btn, Modal } from "../design-kit";
import { HDSelect } from "./hd-ui";
import "./m-support-admin.css";
import "./m1-group-management.css";

const PAGE_SIZE = 20;
const STATUS_TEXT = { ENABLED: "启用", DISABLED: "停用", ARCHIVED: "归档", REMOVED: "移除" };
const KIND_TEXT = { SERVICE: "专属客服", SUPERVISOR: "主管" };
const QUAL_OPTIONS = [{ value: "ENABLED", label: "启用" }, { value: "DISABLED", label: "停用" }, { value: "REMOVED", label: "移除" }];
function errorStatus(error: unknown): number { return error && typeof error === "object" && "status" in error ? Number(error.status) : 0; }
function errorText(error: unknown): string { const code = errorStatus(error); return [401,403,404].includes(code) ? "当前资料已不可访问，请返回获准范围并重新读取。" : code === 409 ? "资料或版本已变化。原输入已保留，请重新读取预览后再次确认。" : code === 422 ? "当前账号、资格或组状态不允许此操作，请核对账号启用状态、成员和交接任务。" : "暂时无法确认结果，原命令与资料已保留；请先查询原操作。"; }
function reasonValid(value: string) { return Array.from(value.trim()).length >= 8 && value.trim().length <= 200; }
function authStamp() { const a = useAdminAuth.getState(); return adminShellSessionKey(a.session, a.authEpoch) + JSON.stringify(a.session?.menuNodes ?? null) + `|${a.isAuthenticated}|${a.logoutPending}|${a.logoutUnknown}`; }
export function canManageSupportQualifications(session: { role: string; authorities: string[] } | null) { return !!session && ["SUPERADMIN", "SUPER_ADMIN", "SUPER"].includes(session.role.toUpperCase()) && session.authorities.includes("platform_a1_read") && session.authorities.includes("platform_a1_write"); }
function expiredText() { return "原操作超过回查保护期，请先核对是否已创建或执行，不能直接重发。原命令和理由仍保留。"; }
const QUERY_PENDING_TEXT = "原操作尚未确认，不能重复提交；请先查询原操作。原命令、资料和理由保持不变。";
type Intent = GroupPendingRecord["intent"];
type Draft = { actorStamp: string; kind: "CREATE" | "RENAME" | "STATUS" | "OWNER" | "MEMBER"; name: string; ownerId: string; targetGroupId: string; status: "ENABLED" | "DISABLED" | "ARCHIVED"; reason: string; member?: SupportGroupMember; source?: SupportGroup; target?: SupportGroup; group?: SupportGroup; stale?: boolean };

/** Root supplies server-resolved mode; role names never manufacture group scope. */
export function M1GroupManagement({ mode, initialGroupId, onBack, onChanged }: { mode: "PERSONAL" | "MANAGED" | "ALL"; initialGroupId?: string; onBack: () => void; onChanged: () => void }) {
  const session = useAdminAuth(s => s.session), epoch = useAdminAuth(s => s.authEpoch), authenticated = useAdminAuth(s => s.isAuthenticated), logoutPending = useAdminAuth(s => s.logoutPending), logoutUnknown = useAdminAuth(s => s.logoutUnknown);
  const identity = adminShellSessionKey(session, epoch) + JSON.stringify(session?.menuNodes ?? null) + `|${authenticated}|${logoutPending}|${logoutUnknown}`;
  const allowed = authenticated && !logoutPending && !logoutUnknown && !!session && !session.passwordChangeRequired && mode !== "PERSONAL" && session.authorities.includes("service_m1_read") && canAccessResolvedPath(resolveVisibleDomains(session), "/service/overview");
  const hasWritePermission = allowed && !!session?.authorities.includes("service_m1_write"), ownerAllowed = mode === "ALL" && !!session?.authorities.includes("platform_a1_read");
  const [selectedId, setSelectedId] = useState<string | undefined>(initialGroupId), [page, setPage] = useState(1), [refresh, setRefresh] = useState(0);
  const [groups, setGroups] = useState<{ key: string; rows: SupportGroup[] }>(), [detail, setDetail] = useState<{ key: string; value: SupportGroupDetail }>(), [names, setNames] = useState<{ key: string; rows: Record<string, SupportGroupMember> }>();
  const [error, setError] = useState(""), [notice, setNotice] = useState(""), [loading, setLoading] = useState(false), [saving, setSaving] = useState(false), [previewBusy, setPreviewBusy] = useState(false);
  const [draftRecord, setDraft] = useState<Draft>(), [pendingRecord, setPending] = useState<GroupPendingRecord>(), [supervisors, setSupervisors] = useState<Awaited<ReturnType<typeof supportGroupClient.supervisors>>["items"]>([]);
  const draft = draftRecord?.actorStamp === identity ? draftRecord : undefined;
  const pending = pendingRecord?.actorId === session?.adminId ? pendingRecord : undefined;
  const [candidatePage, setCandidatePage] = useState(1), [candidateScope, setCandidateScope] = useState<string>(mode === "ALL" ? "global" : initialGroupId ?? ""), [candidateId, setCandidateId] = useState("");
  const [candidates, setCandidates] = useState<Awaited<ReturnType<typeof supportGroupClient.candidates>>>();
  const readKey = `${identity}|${mode}|${selectedId ?? "directory"}|${refresh}`, liveKey = useRef(readKey); liveKey.current = allowed ? readKey : "";
  const previewAbort = useRef<AbortController | null>(null), previewGeneration = useRef(0), writeAbort = useRef<AbortController | null>(null);
  const directoryReady = allowed && groups?.key === `${identity}|${mode}|${refresh}`;
  const rows = directoryReady ? groups.rows : [], currentDetail = allowed && detail?.key === readKey ? detail.value : undefined, memberNames = names?.key === `${readKey}|${page}` ? names.rows : {};
  const writeAllowed = hasWritePermission && directoryReady && (!selectedId || !!currentDetail);
  const closeDraft = () => { previewGeneration.current++; previewAbort.current?.abort(); setDraft(undefined); setCandidates(undefined); setCandidateId(""); };
  const revoke = () => { setGroups(undefined); setDetail(undefined); setNames(undefined); setSupervisors([]); setCandidates(undefined); closeDraft(); setSelectedId(undefined); };
  useEffect(() => { revoke(); setSaving(false); setPreviewBusy(false); setSelectedId(initialGroupId); setPage(1); setError(""); setNotice(""); setPending(groupPendingCommands.list().find(r => r.actorId === session?.adminId && r.intent.kind !== "QUALIFICATION")); return () => { previewGeneration.current++; previewAbort.current?.abort(); writeAbort.current?.abort(); }; }, [identity, mode, initialGroupId]);
  useEffect(() => {
    const controller = new AbortController(); setLoading(allowed); setError(""); setGroups(undefined); setDetail(undefined); setNames(undefined);
    if (allowed) void Promise.all([supportGroupClient.groups(controller.signal), selectedId ? supportGroupClient.detail(selectedId, controller.signal) : Promise.resolve(undefined)]).then(([groupRows, nextDetail]) => {
      if (controller.signal.aborted || authStamp() !== identity || liveKey.current !== readKey) return;
      if (mode === "MANAGED" && groupRows.some(g => g.supervisorAdminId !== String(session?.adminId))) throw new Error("组范围不一致");
      if (nextDetail && (!groupRows.some(g => g.id === nextDetail.group.id) || mode === "MANAGED" && nextDetail.group.supervisorAdminId !== String(session?.adminId))) throw new Error("组详情超出获准范围");
      setGroups({ key: `${identity}|${mode}|${refresh}`, rows: groupRows }); if (nextDetail) setDetail({ key: readKey, value: nextDetail });
    }).catch(cause => { if (!controller.signal.aborted && authStamp() === identity && liveKey.current === readKey) { if ([401,403,404].includes(errorStatus(cause))) revoke(); setError([401,403,404].includes(errorStatus(cause)) ? "当前组资料不可访问，请返回获准范围并重新读取。" : "组资料暂不可读，尚未确认当前负责组；请重新读取后再管理。"); } }).finally(() => { if (!controller.signal.aborted && authStamp() === identity) setLoading(false); });
    return () => controller.abort();
  }, [allowed, readKey]);
  useEffect(() => {
    const controller = new AbortController(); setNames(undefined); if (!currentDetail) return () => controller.abort();
    void Promise.all(currentDetail.members.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE).map(m => supportGroupClient.member(m.adminId, controller.signal))).then(projections => {
      if (controller.signal.aborted || liveKey.current !== readKey) return;
      if (projections.some(m => m.currentMember.state !== "AVAILABLE" || m.currentMember.groupId !== selectedId)) throw new Error("成员所属组已变化");
      setNames({ key: `${readKey}|${page}`, rows: Object.fromEntries(projections.map(m => [m.adminId, m])) });
    }).catch(cause => { if (!controller.signal.aborted && liveKey.current === readKey) { setNames(undefined); if ([401,403,404].includes(errorStatus(cause))) revoke(); setError("成员名单已变化或暂不可读，请刷新当前组。不会使用旧成员版本。" ); } }); return () => controller.abort();
  }, [currentDetail, page, readKey]);
  useEffect(() => { const controller = new AbortController(); setSupervisors([]); if (allowed && ownerAllowed && draft && (draft.kind === "CREATE" || draft.kind === "OWNER")) void supportGroupClient.supervisors(controller.signal).then(next => { if (!controller.signal.aborted && authStamp() === identity) setSupervisors(next.items.filter(s => s.state === "ENABLED" && s.accountStatus === 1)); }).catch(cause => { if (!controller.signal.aborted && authStamp() === identity) { setSupervisors([]); setError("主管目录暂不可读，不能选择新的组负责人。" + errorText(cause)); } }); return () => controller.abort(); }, [allowed, ownerAllowed, draft?.kind, identity]);
  useEffect(() => {
    const controller = new AbortController(); setCandidates(undefined);
    if (allowed && draft?.kind === "MEMBER" && !draft.member && (mode === "ALL" && candidateScope === "global" || rows.some(g => g.id === candidateScope))) void supportGroupClient.candidates({ pageNum: candidatePage, pageSize: PAGE_SIZE, groupId: candidateScope === "global" ? undefined : candidateScope }, controller.signal).then(next => { if (!controller.signal.aborted && authStamp() === identity) setCandidates(next); }).catch(cause => { if (!controller.signal.aborted && authStamp() === identity) { setCandidates(undefined); setError(errorText(cause)); } });
    return () => controller.abort();
  }, [allowed, draft?.kind, draft?.member, candidateScope, candidatePage, readKey]);
  const open = (kind: Draft["kind"], member?: SupportGroupMember, targetStatus?: Draft["status"]) => { if (!writeAllowed || pending || saving) return; setError(""); setCandidateId(""); setCandidatePage(1); setCandidateScope(mode === "ALL" ? "global" : selectedId ?? rows[0]?.id ?? ""); setDraft({ actorStamp: identity, kind, group: currentDetail?.group, name: currentDetail?.group.name ?? "", ownerId: mode === "MANAGED" ? String(session?.adminId) : "", targetGroupId: kind === "MEMBER" && member ? "" : selectedId ?? "", status: targetStatus ?? "DISABLED", reason: "", member, stale: kind === "MEMBER" && !!member }); };
  const previewMove = async (adminId: string, targetGroupId: string, saved = draft) => {
    if (!saved || saved.kind !== "MEMBER" || pending || !writeAllowed) return;
    previewAbort.current?.abort(); const controller = new AbortController(); previewAbort.current = controller; const generation = ++previewGeneration.current; setPreviewBusy(true); setError("");
    try { const member = await supportGroupClient.member(adminId, controller.signal); if (controller.signal.aborted || authStamp() !== identity || generation !== previewGeneration.current) return; observedVersion(member.currentMember);
      if (mode === "MANAGED" && (!member.currentMember.groupId || !rows.some(g => g.id === member.currentMember.groupId) || !targetGroupId || !rows.some(g => g.id === targetGroupId))) throw new Error("仅可在本人负责组之间调组");
      const [source, target] = await Promise.all([member.currentMember.groupId ? supportGroupClient.detail(member.currentMember.groupId, controller.signal).then(d => d.group) : Promise.resolve(undefined), targetGroupId ? supportGroupClient.detail(targetGroupId, controller.signal).then(d => d.group) : Promise.resolve(undefined)]);
      if (mode === "MANAGED" && [source, target].some(g => !g || g.supervisorAdminId !== String(session?.adminId))) throw new Error("组负责人已变化");
      if (target && target.status !== "ENABLED") throw new Error("目标组未启用"); if (controller.signal.aborted || authStamp() !== identity || generation !== previewGeneration.current) return; setDraft({ ...saved, member, source, target, targetGroupId, stale: false });
    } catch (cause) { if (!controller.signal.aborted && authStamp() === identity && generation === previewGeneration.current) { setDraft({ ...saved, stale: true }); if ([401,403,404].includes(errorStatus(cause))) revoke(); setError("调组预览不可用，请重读后再确认。" + errorText(cause)); } } finally { if (!controller.signal.aborted && authStamp() === identity && generation === previewGeneration.current) setPreviewBusy(false); }
  };
  const refreshDraft = async () => { if (!draft || pending || !writeAllowed) return; if (draft.kind === "MEMBER" && draft.member) { await previewMove(draft.member.adminId, draft.targetGroupId, draft); return; } const controller = new AbortController(); previewAbort.current?.abort(); previewAbort.current = controller; const generation = ++previewGeneration.current; setPreviewBusy(true);
    try { if (draft.group) { const next = await supportGroupClient.detail(draft.group.id, controller.signal); if (!controller.signal.aborted && authStamp() === identity && generation === previewGeneration.current) { setDraft({ ...draft, group: next.group, stale: false }); setDetail({ key: readKey, value: next }); setError(""); } } } catch (cause) { if (!controller.signal.aborted && authStamp() === identity) { if ([401,403,404].includes(errorStatus(cause))) revoke(); setError(errorText(cause)); } } finally { if (!controller.signal.aborted && authStamp() === identity) setPreviewBusy(false); } };
  const readFacts = async (intent: Intent, signal: AbortSignal) => { const member = intent.kind === "MEMBER" ? await supportGroupClient.member(intent.targetId, signal) : undefined; if (signal.aborted || authStamp() !== identity) throw new Error("READ_IDENTITY_CHANGED"); const group = intent.kind !== "CREATE" && intent.kind !== "MEMBER" && intent.kind !== "QUALIFICATION" ? (await supportGroupClient.detail(intent.targetId, signal)).group : undefined; if (signal.aborted || authStamp() !== identity) throw new Error("READ_IDENTITY_CHANGED"); const rows = await supportGroupClient.groups(signal); if (mode === "MANAGED" && rows.some(g => g.supervisorAdminId !== String(session?.adminId)) || group && !rows.some(g => g.id === group.id) || mode === "MANAGED" && member && (member.currentMember.state !== "AVAILABLE" || !rows.some(g => g.id === member.currentMember.groupId)) || intent.kind === "MEMBER" && intent.payload.targetGroupId !== null && !rows.some(g => g.id === intent.payload.targetGroupId)) throw new Error("组范围不一致"); return { member, group, rows }; };
  const failedDraft = (saved: GroupPendingRecord, facts: Awaited<ReturnType<typeof readFacts>>): Draft | undefined => { const i = saved.intent; if (i.kind === "QUALIFICATION") return undefined; const targetGroupId = i.kind === "MEMBER" && facts.rows.some(g => g.id === i.payload.targetGroupId) ? i.payload.targetGroupId ?? "" : ""; return { actorStamp: identity, kind: i.kind, name: i.kind === "CREATE" || i.kind === "RENAME" ? i.payload.name : facts.group?.name ?? "", ownerId: i.kind === "CREATE" || i.kind === "OWNER" ? i.payload.supervisorAdminId : "", reason: i.payload.reason, targetGroupId, status: i.kind === "STATUS" ? i.payload.status : "DISABLED", member: facts.member, group: facts.group && i.kind !== "CREATE" && i.kind !== "MEMBER" ? { ...facts.group, version: i.payload.expectedVersion } : undefined, stale: i.kind !== "CREATE" }; };
  const checkPending = async () => { if (!pending || saving || !allowed) return; const saved = pending, controller = new AbortController(); writeAbort.current = controller; setSaving(true); setError("");
    try { const receipt = await supportGroupClient.command(saved.commandKey, controller.signal); if (controller.signal.aborted || authStamp() !== identity) return; if (receipt.status === "SUCCEEDED" || receipt.status === "FAILED") { const facts = await readFacts(saved.intent, controller.signal); if (authStamp() !== identity || controller.signal.aborted) return; groupPendingCommands.forget(saved.fingerprint, saved.commandKey); setPending(undefined); if (receipt.status === "SUCCEEDED") closeDraft(); else setDraft(failedDraft(saved, facts)); setRefresh(n => n + 1); onChanged(); setNotice(receipt.status === "SUCCEEDED" ? "原操作已成功，已按当前权限重读组资料。" : "原操作已明确失败；理由已保留，请重新预览并确认。"); } else if (authStamp() === identity) setError(canReplayGroupCommand(saved) ? "原操作仍未确认，请稍后回查；原资料与命令号保持不变。" : expiredText()); }
    catch (cause) { if (authStamp() === identity && !controller.signal.aborted) { if ([401,403].includes(errorStatus(cause))) revoke(); setError("无法确认原操作，命令和理由仍保留。" + (canReplayGroupCommand(saved) ? errorText(cause) : expiredText())); } } finally { if (authStamp() === identity) setSaving(false); } };
  const submit = async () => {
    if (saving || !writeAllowed || previewBusy) return; let record = pending, createdThisAttempt = false;
    const previous = record ?? groupPendingCommands.list().find(r => r.actorId === session?.adminId && r.intent.kind !== "QUALIFICATION");
    if (previous) { setPending(previous); setError(QUERY_PENDING_TEXT); return; }
    if (!record) {
      if (!draft || draft.stale || !reasonValid(draft.reason)) return; let intent: Intent; const why = draft.reason.trim();
      if (draft.kind === "CREATE") { if (!draft.name.trim() || draft.name.trim().length > 120 || !draft.ownerId || mode === "ALL" && !supervisors.some(s => s.adminId === draft.ownerId)) return; intent = { kind: "CREATE", payload: { name: draft.name.trim(), supervisorAdminId: mode === "MANAGED" ? String(session?.adminId) : draft.ownerId, reason: why } }; }
      else if (draft.kind === "MEMBER") { if (!draft.member || draft.member.currentMember.state === "UNKNOWN" || draft.member.currentMember.groupId === (draft.targetGroupId || null) || draft.member.currentMember.groupId && !draft.source || draft.targetGroupId && !draft.target || mode === "MANAGED" && (!draft.source || !draft.target)) return; intent = { kind: "MEMBER", targetId: draft.member.adminId, payload: { targetGroupId: draft.targetGroupId || null, expectedMemberVersion: observedVersion(draft.member.currentMember), sourceGroupVersion: draft.source?.version ?? null, targetGroupVersion: draft.target?.version ?? null, reason: why } }; }
      else { if (!draft.group) return; if (draft.kind === "RENAME") intent = { kind: "RENAME", targetId: draft.group.id, payload: { name: draft.name.trim(), expectedVersion: draft.group.version, reason: why } }; else if (draft.kind === "OWNER") { if (mode !== "ALL" || !supervisors.some(s => s.adminId === draft.ownerId) || draft.ownerId === draft.group.supervisorAdminId) return; intent = { kind: "OWNER", targetId: draft.group.id, payload: { supervisorAdminId: draft.ownerId, expectedVersion: draft.group.version, reason: why } }; } else intent = { kind: "STATUS", targetId: draft.group.id, payload: { status: draft.status, expectedVersion: draft.group.version, reason: why } }; }
      const commandKey = crypto.randomUUID(), fingerprint = `group-management:${session!.adminId}`; groupPendingCommands.remember(fingerprint, commandKey, { actorId: session!.adminId, intent, label: draft.kind === "MEMBER" ? `调组 · ${draft.member?.name}` : `${draft.kind === "CREATE" ? "创建" : draft.kind === "RENAME" ? "重命名" : draft.kind === "OWNER" ? "移交负责人" : "调整状态"} · ${draft.name}` });
      record = groupPendingCommands.list().find(r => r.commandKey === commandKey); if (!record) { setError("原命令无法保存，已停止提交。请恢复浏览器存储后重试。" ); return; } createdThisAttempt = true; setPending(record);
    }
    if (!createdThisAttempt || !record) { setError(QUERY_PENDING_TEXT); return; }
    if (!groupPendingCommands.isDurablyStored(record.fingerprint, record.commandKey)) { setError("原命令未能持久保存，已停止提交。请恢复浏览器存储后查询原命令。" ); return; }
    const saved = record, controller = new AbortController(); writeAbort.current = controller; setSaving(true); setError(""); let written = false;
    try { const i = saved.intent; if (i.kind === "CREATE") await supportGroupClient.createSupportGroup(i.payload, saved.commandKey, controller.signal); else if (i.kind === "RENAME") await supportGroupClient.renameSupportGroup(i.targetId, i.payload, saved.commandKey, controller.signal); else if (i.kind === "STATUS") await supportGroupClient.setSupportGroupStatus(i.targetId, i.payload, saved.commandKey, controller.signal); else if (i.kind === "OWNER") await supportGroupClient.transferSupportGroupOwner(i.targetId, i.payload, saved.commandKey, controller.signal); else if (i.kind === "MEMBER") await supportGroupClient.moveSupportGroupMember(i.targetId, i.payload, saved.commandKey, controller.signal); else return;
      written = true; if (controller.signal.aborted || authStamp() !== identity) return; await readFacts(i, controller.signal); if (authStamp() !== identity || controller.signal.aborted) return; groupPendingCommands.forget(saved.fingerprint, saved.commandKey); setPending(undefined); closeDraft(); setRefresh(n => n + 1); onChanged(); setNotice("操作已成功，已重读当前可见组资料。");
    } catch (cause) { if (authStamp() !== identity || controller.signal.aborted) return; if (!written && errorStatus(cause) === 409) setDraft(old => old ? { ...old, stale: true } : old); if ([401,403,404].includes(errorStatus(cause))) revoke(); setError(errorText(cause)); } finally { if (authStamp() === identity) setSaving(false); }
  };
  const targetGroups = rows.filter(g => g.status === "ENABLED" && g.id !== draft?.member?.currentMember.groupId);
  const draftReady = !!draft && !draft.stale && reasonValid(draft.reason) && (draft.kind === "CREATE" || draft.kind === "RENAME" ? !!draft.name.trim() && draft.name.trim().length <= 120 : true) && (draft.kind === "CREATE" || draft.kind === "OWNER" ? mode === "MANAGED" || supervisors.some(s => s.adminId === draft.ownerId) : true) && (draft.kind !== "MEMBER" || !!draft.member && draft.member.currentMember.state !== "UNKNOWN" && draft.member.currentMember.groupId !== (draft.targetGroupId || null) && (!draft.member.currentMember.groupId || !!draft.source) && (!draft.targetGroupId || !!draft.target) && (mode === "ALL" || !!draft.source && !!draft.target));
  return <section className="m1-group-management" aria-label="客服组管理">
    <header className="m-admin-toolbar"><Btn onClick={onBack} disabled={saving}>返回统计工作台</Btn><h2>{selectedId ? currentDetail?.group.name ?? "组成员" : "组管理"}</h2><Btn disabled={!allowed || saving} onClick={() => { setPage(1); setRefresh(n => n + 1); }}>刷新资料</Btn>{hasWritePermission && !selectedId && <Btn disabled={!writeAllowed || saving || !!pending} title={!directoryReady ? "先成功读取当前获准组目录" : undefined} onClick={() => open("CREATE")}>创建组</Btn>}</header>
    {!allowed && <p role="alert">当前账号不能管理客服组。主管只能管理本人负责的组。</p>}{notice && <p role="status" className="m-admin-muted">{notice}</p>}{error && <p role="alert" className="m-admin-error">{error}</p>}
    {allowed && pending && <div className="m-admin-error" role="alert"><p>{QUERY_PENDING_TEXT}{!canReplayGroupCommand(pending) && expiredText()}</p><Btn disabled={saving} onClick={() => void checkPending()}>查询原操作</Btn></div>}{allowed && loading && <p role="status">正在读取获准组资料…</p>}
    {directoryReady && !loading && !selectedId && <div className="m-admin-table-wrap"><table className="m-admin-table"><thead><tr><th>组名</th><th>状态</th><th>操作</th></tr></thead><tbody>{rows.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE).map(g => <tr key={g.id}><td>{g.name}</td><td>{STATUS_TEXT[g.status]}</td><td><Btn disabled={saving} onClick={() => { closeDraft(); setSelectedId(g.id); setPage(1); }}>管理成员与组资料</Btn></td></tr>)}</tbody></table>{rows.length === 0 && <p>当前没有负责组。{writeAllowed ? "可创建组并由当前有效主管负责。" : "请由有写权限的主管或总管理员创建。"}</p>}</div>}
    {allowed && !loading && selectedId && currentDetail && <><div className="m-admin-toolbar"><Btn disabled={saving} onClick={() => { closeDraft(); setSelectedId(undefined); setPage(1); }}>返回组目录</Btn><span>{STATUS_TEXT[currentDetail.group.status]} · 成员 {currentDetail.memberCount} 人 · 待分配 {currentDetail.routedCustomers} 人 · 未结束管理任务 {currentDetail.pendingOperations} 项</span></div>
      {writeAllowed && <div className="m-admin-toolbar"><Btn disabled={saving || !!pending || currentDetail.group.status === "ARCHIVED"} onClick={() => open("RENAME")}>重命名</Btn><Btn disabled={saving || !!pending || currentDetail.group.status !== "ENABLED"} onClick={() => open("MEMBER")}>加入或调入成员</Btn>{mode === "ALL" && <Btn disabled={saving || !!pending || !ownerAllowed} title={!ownerAllowed ? "读取主管目录需要账号读取权限" : undefined} onClick={() => open("OWNER")}>移交负责人</Btn>}{currentDetail.group.status === "ENABLED" ? <Btn disabled={saving || !!pending || !currentDetail.blockers.canExit} title={!currentDetail.blockers.canExit ? "先处理全部成员、待分配客户和未结束管理任务" : undefined} onClick={() => open("STATUS", undefined, "DISABLED")}>停用组</Btn> : currentDetail.group.status === "DISABLED" && <><Btn disabled={saving || !!pending} onClick={() => open("STATUS", undefined, "ENABLED")}>启用组</Btn><Btn disabled={saving || !!pending || !currentDetail.blockers.canExit} title={!currentDetail.blockers.canExit ? "先处理全部成员、待分配客户和未结束管理任务" : undefined} onClick={() => open("STATUS", undefined, "ARCHIVED")}>归档组</Btn></>}</div>}
      {!currentDetail.blockers.canExit && <p className="m-admin-muted">停用或归档前，先将成员调出、处理本组待分配客户，并结束或核对未完成的管理任务。{currentDetail.routedCustomers > 0 && "客户队列从工作台“分配与服务”进入；返回统计后保留原组条件。"}</p>}
      <div className="m-admin-table-wrap"><table className="m-admin-table"><thead><tr><th>专属客服</th><th>账号 / 交接</th><th>当前绑定客户</th><th>操作</th></tr></thead><tbody>{currentDetail.members.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE).map(m => <tr key={m.adminId}><td>{memberNames[m.adminId]?.name ?? "正在核对成员…"}</td><td>{m.accountStatus === 1 ? "账号启用" : "账号停用"}{m.handoverRequired ? " · 待交接" : ""}</td><td>{m.boundCustomers} 人</td><td><Btn disabled={!writeAllowed || saving || !!pending || !memberNames[m.adminId]} onClick={() => { const member = memberNames[m.adminId]; if (member) open("MEMBER", member); }}>调组</Btn></td></tr>)}</tbody></table>{!currentDetail.members.length && <p>本组当前没有成员。</p>}</div>
    </>}
    {directoryReady && !loading && <nav className="m-admin-toolbar" aria-label={selectedId ? "成员分页" : "组分页"}><Btn disabled={saving || page <= 1} onClick={() => setPage(n => n - 1)}>上一页</Btn><span>第 {page} / {Math.max(1, Math.ceil((selectedId ? currentDetail?.memberCount ?? 0 : rows.length) / PAGE_SIZE))} 页</span><Btn disabled={saving || page >= Math.ceil((selectedId ? currentDetail?.memberCount ?? 0 : rows.length) / PAGE_SIZE)} onClick={() => setPage(n => n + 1)}>下一页</Btn></nav>}
    {draft && directoryReady && !pending && <Modal title={draft.kind === "CREATE" ? "创建客服组" : draft.kind === "MEMBER" ? "确认成员调组" : draft.kind === "OWNER" ? "移交组负责人" : draft.kind === "STATUS" ? `${STATUS_TEXT[draft.status]}客服组` : "重命名客服组"} busy={saving || previewBusy} onClose={() => { if (!saving && !previewBusy) closeDraft(); }} footer={<><Btn disabled={saving || previewBusy} onClick={closeDraft}>返回</Btn>{draft.stale && <Btn disabled={saving || previewBusy} onClick={() => void refreshDraft()}>重读预览</Btn>}<Btn variant="primary" disabled={saving || previewBusy || !writeAllowed || !draftReady} onClick={() => void submit()}>{saving ? "正在提交…" : "确认并提交"}</Btn></>}>
      {(draft.kind === "CREATE" || draft.kind === "RENAME") && <label className="field"><span>组名</span><input className="fld" value={draft.name} maxLength={120} disabled={saving || !!pending} onChange={e => setDraft({ ...draft, name: e.target.value })} /></label>}
      {(draft.kind === "CREATE" || draft.kind === "OWNER") && <label className="field"><span>组负责人</span>{mode === "MANAGED" ? <p>当前主管本人 · {session?.operator || "当前账号"}</p> : saving || pending ? <p>{supervisors.find(s => s.adminId === draft.ownerId)?.name ?? "原选择已锁定"}</p> : <HDSelect value={draft.ownerId} options={supervisors.map(s => ({ value: s.adminId, label: s.name }))} placeholder="选择启用的主管" onChange={ownerId => setDraft({ ...draft, ownerId })} />}</label>}
      {draft.kind === "MEMBER" && <>
        {!draft.member && <><label className="field"><span>选择成员来源</span>{saving || pending ? <p>原来源已锁定</p> : <HDSelect value={candidateScope} options={[...(mode === "ALL" ? [{ value: "global", label: "全部获准专属客服（含待分组）" }] : []), ...rows.map(g => ({ value: g.id, label: g.name }))]} onChange={value => { setCandidateScope(value); setCandidatePage(1); setCandidateId(""); }} />}</label><label className="field"><span>选择专属客服</span><HDSelect value={candidateId} options={(candidates?.records ?? []).map(c => ({ value: c.adminId, label: c.name }))} placeholder="逐页选择成员" onChange={value => { if (!saving && !pending && !previewBusy) { setCandidateId(value); void previewMove(value, draft.targetGroupId); } }} /></label><div className="m-admin-toolbar"><Btn disabled={candidatePage <= 1 || previewBusy || !!pending} onClick={() => setCandidatePage(n => n - 1)}>上一页成员</Btn><span>第 {candidatePage} / {Math.max(1, Math.ceil((candidates?.total ?? 0) / PAGE_SIZE))} 页</span><Btn disabled={!candidates || candidatePage >= Math.ceil(candidates.total / PAGE_SIZE) || previewBusy || !!pending} onClick={() => setCandidatePage(n => n + 1)}>下一页成员</Btn></div></>}
        {draft.member && <><p>{draft.member.name} · 当前绑定 {draft.member.boundCustomers} 位客户 · 原组 {draft.source?.name ?? (draft.member.currentMember.state === "ABSENT" ? "确证未入组" : draft.member.currentMember.groupId ? "正在核对" : "待分组")}</p><p className="m-admin-muted">调组不更改已有个人绑定，不搬历史事件；当前所属资产范围随客服所在组变化。</p></>}
        <label className="field"><span>目标组</span>{saving || pending ? <p>{draft.target?.name ?? "待分组"}</p> : <HDSelect value={draft.targetGroupId} options={[...(mode === "ALL" ? [{ value: "", label: "待分组" }] : []), ...targetGroups.map(g => ({ value: g.id, label: g.name }))]} placeholder="选择启用的目标组" onChange={targetGroupId => { setDraft({ ...draft, targetGroupId, target: undefined, stale: true }); if (draft.member) void previewMove(draft.member.adminId, targetGroupId, draft); }} />}</label>
      </>}
      {draft.kind === "OWNER" && <p>移交负责人会更新本组管理范围，影响成员与待分配队列；个人绑定和历史事件保留。成员 {currentDetail?.memberCount ?? "待核对"} 人，待分配 {currentDetail?.routedCustomers ?? "待核对"} 人。</p>}
      <label className="field"><span>操作理由（8–200 字）</span><textarea value={draft.reason} maxLength={200} disabled={saving || !!pending} onChange={e => setDraft({ ...draft, reason: e.target.value })} /></label>{previewBusy && <p role="status">正在读取最新成员与来源、目标组版本…</p>}{draft.stale && <p role="alert">预览尚未核实或版本已变化，请重读后再次确认。</p>}{error && <p role="alert" className="m-admin-error">{error}</p>}
    </Modal>}
  </section>;
}

/** Qualifications share the existing A1 account; no second customer-service identity. */
export function SupportQualificationEditor({ adminId, kind, onClose, onChanged }: { adminId: string; kind: QualificationKind; onClose: () => void; onChanged: () => void }) {
  const session = useAdminAuth(s => s.session), epoch = useAdminAuth(s => s.authEpoch), authenticated = useAdminAuth(s => s.isAuthenticated), logoutPending = useAdminAuth(s => s.logoutPending), logoutUnknown = useAdminAuth(s => s.logoutUnknown);
  const identity = adminShellSessionKey(session, epoch) + JSON.stringify(session?.menuNodes ?? null) + `|${authenticated}|${logoutPending}|${logoutUnknown}`;
  const allowed = authenticated && !logoutPending && !logoutUnknown && !!session && !session.passwordChangeRequired && canManageSupportQualifications(session) && canAccessResolvedPath(resolveVisibleDomains(session), "/platform/rbac");
  const key = `${identity}|${adminId}|${kind}`, liveKey = useRef(key); liveKey.current = allowed ? key : "";
  const [projection, setProjection] = useState<{ key: string; value: SupportQualifications }>(), [state, setState] = useState<QualificationStatus>("ENABLED"), [reason, setReason] = useState(""), [error, setError] = useState(""), [busy, setBusy] = useState(false), [stale, setStale] = useState(false), [refresh, setRefresh] = useState(0), [pendingRecord, setPending] = useState<GroupPendingRecord>();
  const pending = pendingRecord && pendingRecord.actorId === session?.adminId && pendingRecord.intent.kind === "QUALIFICATION" && pendingRecord.intent.targetId === adminId && pendingRecord.intent.payload.qualificationKind === kind ? pendingRecord : undefined;
  const controllerRef = useRef<AbortController | null>(null), data = allowed && projection?.key === key ? projection.value : undefined, fact = data?.qualifications.find(q => q.kind === kind);
  useEffect(() => { setProjection(undefined); setReason(""); setError(""); setBusy(false); setStale(false); setPending(groupPendingCommands.list().find(r => r.actorId === session?.adminId && r.intent.kind === "QUALIFICATION" && r.intent.targetId === adminId && r.intent.payload.qualificationKind === kind)); return () => controllerRef.current?.abort(); }, [key]);
  useEffect(() => { const controller = new AbortController(); setProjection(undefined); if (allowed) void supportGroupClient.qualifications(adminId, controller.signal).then(next => { if (!controller.signal.aborted && liveKey.current === key && authStamp() === identity) { setProjection({ key, value: next }); setStale(false); } }).catch(cause => { if (!controller.signal.aborted && liveKey.current === key) { setProjection(undefined); setError(errorText(cause)); } }); return () => controller.abort(); }, [allowed, key, refresh]);
  const check = async () => { if (!pending || busy || !allowed) return; const saved = pending, controller = new AbortController(); controllerRef.current = controller; setBusy(true);
    try { const receipt = await supportGroupClient.command(saved.commandKey, controller.signal); if (controller.signal.aborted || authStamp() !== identity || liveKey.current !== key) return; if (receipt.status === "SUCCEEDED" || receipt.status === "FAILED") { const next = await supportGroupClient.qualifications(adminId, controller.signal); if (controller.signal.aborted || authStamp() !== identity || liveKey.current !== key) return; groupPendingCommands.forget(saved.fingerprint, saved.commandKey); setPending(undefined); setProjection({ key, value: next }); if (saved.intent.kind === "QUALIFICATION") { setReason(saved.intent.payload.reason); setState(saved.intent.payload.state); } setStale(receipt.status === "FAILED"); onChanged(); setError(receipt.status === "SUCCEEDED" ? "原操作已成功，已读取当前账号资格。" : "原操作已明确失败，理由已保留；请重读预览后重新确认。"); } else if (authStamp() === identity) setError(canReplayGroupCommand(saved) ? "原操作仍未确认，请稍后查询。" : expiredText()); } catch (cause) { if (authStamp() === identity && liveKey.current === key) { if ([401,403,404].includes(errorStatus(cause))) setProjection(undefined); setError("原命令和理由仍保留。" + errorText(cause)); } } finally { if (authStamp() === identity) setBusy(false); } };
  const submit = async () => {
    if (!allowed || busy) return; let saved = pending, createdThisAttempt = false;
    const previous = saved ?? groupPendingCommands.list().find(r => r.actorId === session?.adminId && r.intent.kind === "QUALIFICATION" && r.intent.targetId === adminId && r.intent.payload.qualificationKind === kind);
    if (previous) { setPending(previous); setError(QUERY_PENDING_TEXT); return; }
    if (!saved) { if (!data || !fact || fact.observationState === "UNKNOWN" || stale || !reasonValid(reason) || fact.state === state || state === "ENABLED" && data.accountStatus !== 1) return;
      const commandKey = crypto.randomUUID(), fingerprint = `support-qualification:${session!.adminId}:${adminId}:${kind}`, intent: Intent = { kind: "QUALIFICATION", targetId: adminId, payload: { qualificationKind: kind, state, expectedQualificationVersion: observedVersion(fact), expectedAccountVersion: accountVersion(data.accountVersion), reason: reason.trim() } };
      groupPendingCommands.remember(fingerprint, commandKey, { actorId: session!.adminId, intent, label: `${KIND_TEXT[kind]}资格 · ${data.name}` }); saved = groupPendingCommands.list().find(r => r.commandKey === commandKey); if (!saved) { setError("命令保存失败，已停止提交。" ); return; } createdThisAttempt = true; setPending(saved);
    }
    if (!createdThisAttempt || !saved) { setError(QUERY_PENDING_TEXT); return; }
    if (!groupPendingCommands.isDurablyStored(saved.fingerprint, saved.commandKey) || saved.intent.kind !== "QUALIFICATION") { setError("原命令未能持久保存，已停止提交。请恢复浏览器存储。" ); return; }
    const controller = new AbortController(); controllerRef.current = controller; setBusy(true); setError(""); let written = false;
    try { await supportGroupClient.setSupportQualification(adminId, saved.intent.payload, saved.commandKey, controller.signal); written = true; if (controller.signal.aborted || authStamp() !== identity || liveKey.current !== key) return; const next = await supportGroupClient.qualifications(adminId, controller.signal); if (controller.signal.aborted || authStamp() !== identity || liveKey.current !== key) return; groupPendingCommands.forget(saved.fingerprint, saved.commandKey); setPending(undefined); setProjection({ key, value: next }); onChanged(); setError("资格已更新，已重新读取账号资格。" ); }
    catch (cause) { if (controller.signal.aborted || authStamp() !== identity || liveKey.current !== key) return; if (!written && errorStatus(cause) === 409) setStale(true); if ([401,403,404].includes(errorStatus(cause))) setProjection(undefined); setError(errorText(cause)); } finally { if (authStamp() === identity) setBusy(false); }
  };
  const canSubmit = !!data && !!fact && fact.observationState !== "UNKNOWN" && !stale && reasonValid(reason) && state !== fact.state && (state !== "ENABLED" || data.accountStatus === 1);
  return <Modal title={pending ? "查询原操作" : `${KIND_TEXT[kind]}资格`} busy={busy} onClose={() => { if (!busy) onClose(); }} footer={<><Btn disabled={busy} onClick={onClose}>关闭</Btn>{allowed && pending ? <Btn disabled={busy} onClick={() => void check()}>查询原操作</Btn> : <><Btn disabled={!allowed || busy} onClick={() => setRefresh(n => n + 1)}>重读当前资格</Btn><Btn variant="primary" disabled={!allowed || busy || !canSubmit} onClick={() => void submit()}>{busy ? "正在提交…" : "确认并提交"}</Btn></>}</>}>
    {!allowed ? <p role="alert">仅总管理员且具备账号读取、写入权限时可管理资格。</p> : pending ? <p role="status">原操作恢复证据已保留，请查询结果；当前不展示保存的账号、目标或理由。</p> : !data ? <p role="status">{error || "正在读取当前账号与资格版本…"}</p> : <><p>{data.name} · {data.accountStatus === 1 ? "账号启用" : "账号停用"}</p><p>当前{KIND_TEXT[kind]}资格：{fact?.observationState === "UNKNOWN" ? "待核实，不能写入" : fact?.observationState === "ABSENT" ? "确证未授予" : fact?.state ? STATUS_TEXT[fact.state] : "待核实"}</p>
      <p className="m-admin-muted">专属客服是唯一人工客服身份；主管是独立管理资格，同一账号可兼任。授予资格不自动绑定客户，也不改普通账号角色。</p>{kind === "SUPERVISOR" && state !== "ENABLED" && <p>停用或移除前，须先将全部负责组（含归档组）移交给有效主管。</p>}{kind === "SERVICE" && state !== "ENABLED" && <p>停用或移除前，须先处理已有绑定客户并退出组；不会自动改派客户。</p>}
      <label className="field"><span>资格状态</span>{busy ? <p>{STATUS_TEXT[state]}</p> : <HDSelect value={state} onChange={value => setState(value as QualificationStatus)} options={QUAL_OPTIONS} />}</label><label className="field"><span>操作理由（8–200 字）</span><textarea value={reason} maxLength={200} disabled={busy} onChange={e => setReason(e.target.value)} /></label></>}
    {allowed && pending && <p role="alert">{QUERY_PENDING_TEXT}{!canReplayGroupCommand(pending) && expiredText()}</p>}{allowed && !pending && stale && <p role="alert">版本已变化，请重读当前资格并再次确认。理由已保留。</p>}{error && data && <p role="alert">{error}</p>}
  </Modal>;
}
