"use client";
import { useEffect, useRef, useState } from "react";
import { useAdminAuth } from "@/lib/store/admin-auth";
import { supportEnhancements, parseBulkJob, type BulkFilters, type BulkPreview, type BulkContent, type BulkJob, type BulkRecipient, type SupportProfile } from "@/lib/admin/m-support-enhancements";
import { supportClient, SupportClientError, isIndeterminateSupportError } from "@/lib/admin/m-support-client";
import { createPendingMutationStore, type PendingMutationRecord } from "@/lib/admin/pending-mutation-store";
import { displayAdminError } from "@/lib/admin/error-messages";
import { Modal } from "../design-kit";
import { SupportContentTools, type SelectedSupportContent } from "./support-content-tools";
import type { MCtx } from "./types";
type Stored = PendingMutationRecord & { actorId:number; payload:BulkContent; batchId?:string; readOnlyRecovery?:boolean; action?:"cancel"|"retry"; mutation?:{expectedVersion:number;reason:string} };
const commands=createPendingMutationStore<Stored>({storageKey:"nexion-support-bulk-pending",ttlMs:Number.MAX_SAFE_INTEGER-Date.now(),isValidRecord:r=>Number.isSafeInteger(r.actorId)&&Boolean(r.payload?.selectionId)});
const reasonText:Record<string,string>={STOPPED:"不再维护",MAINTENANCE_STOPPED:"不再维护",NOT_CURRENT_CUSTOMER:"当前非本人客户",EXPLICITLY_EXCLUDED:"手动排除",FILTER_MISMATCH:"不符合筛选",ACTIVITY_UNKNOWN:"活动状态未知",LEVEL_UNKNOWN:"等级未知",MAINTENANCE_UNKNOWN:"维护状态未知",REGISTRATION_UNKNOWN:"注册时间未知",FINANCE_UNKNOWN:"资金来源未知",FINANCE_ERROR:"资金读取失败"};
const stateText:Record<string,string>={QUEUED:"等待执行",RUNNING:"正在执行",COMPLETED:"执行结束",CANCELLED:"已取消剩余",PENDING:"待处理",SENT:"已提交",FAILED:"失败",SKIPPED:"跳过"};
const utc=(v:string)=>v?new Date(v+"T00:00:00Z").toISOString():undefined;
const bulkPreviewError = (error: unknown) => error instanceof SupportClientError
  && error.status === 403 && error.backendMessage === "SUPPORT_AGENT_UNAVAILABLE"
  ? "当前账号没有可用的顾问坐席，暂不能圈选群发。请联系主管核对坐席状态，再由可接待的顾问账号操作。"
  : displayAdminError(error);
export function SupportBulkComposer({ctx,onClose}:{ctx:MCtx;onClose:()=>void}) {
  const session=useAdminAuth(s=>s.session),epoch=useAdminAuth(s=>s.authEpoch),actorId=session?.adminId??0;
  const canWrite=session?.role==="super"||session?.role==="superadmin"||Boolean(session?.authorities.includes("service_m3_write"));
  const [step,setStep]=useState(1),[filters,setFilters]=useState<BulkFilters>({}),[query,setQuery]=useState<BulkPreview|null>(null),[selection,setSelection]=useState<BulkPreview|null>(null);
  const [selected,setSelected]=useState<Set<string>>(new Set()),[page,setPage]=useState(1),[profiles,setProfiles]=useState<Record<string,SupportProfile>>({});
  const [busy,setBusy]=useState(false),[error,setError]=useState(""),[retry,setRetry]=useState(0),[filterDraft,setFilterDraft]=useState<BulkFilters>({});
  const [text,setText]=useState(""),[intent,setIntent]=useState<"SERVICE"|"MAINTENANCE">("SERVICE"),[choice,setChoice]=useState<SelectedSupportContent|null>(null),[reason,setReason]=useState(""),[ack,setAck]=useState(false);
  const [draftOwner,setDraftOwner]=useState(0);
  const [image,setImage]=useState<{file:File;url:string;id:string;key:string;assetId?:string}|null>(null),[uploading,setUploading]=useState(false),[uploadError,setUploadError]=useState("");
  const [job,setJob]=useState<BulkJob|null>(null),[jobs,setJobs]=useState<BulkJob[]|null>(null),[jobsTotal,setJobsTotal]=useState(0),[jobsPage,setJobsPage]=useState(1),[jobsError,setJobsError]=useState("");
  const [recipients,setRecipients]=useState<BulkRecipient[]|null>(null),[recipientTotal,setRecipientTotal]=useState(0),[recipientPage,setRecipientPage]=useState(1),[resultRetry,setResultRetry]=useState(0),[resultError,setResultError]=useState("");
  const [pending,setPending]=useState<Stored|null>(null),[mutationAction,setMutationAction]=useState<"cancel"|"retry"|null>(null),[mutationReason,setMutationReason]=useState("");
  const generation=useRef(0),stamp=useRef("");stamp.current=`${epoch}:${actorId}:${generation.current}`;
  const imageRef=useRef(image);imageRef.current=image;
  const imageSelection=useRef(0);
  const composerRef=useRef<HTMLTextAreaElement>(null);
  useEffect(()=>{const handle=()=>{generation.current++;for(const record of commands.list())if(record.actorId===actorId)commands.remember(record.fingerprint,record.commandKey,{actorId,payload:{selectionId:record.payload.selectionId,intent:"SERVICE",kind:"TEXT",content:"",reason:""},batchId:record.batchId,readOnlyRecovery:true});try{sessionStorage.removeItem(`nexion-bulk-draft:${actorId}`);}catch{}setDraftOwner(0);setPending(null);stamp.current=`${epoch}:${actorId}:${generation.current}`;setProfiles({});setSelection(null);setQuery(null);setText("");setChoice(null);setJob(null);setRecipients(null);onClose();};window.addEventListener("support-scope-invalidated",handle);return()=>window.removeEventListener("support-scope-invalidated",handle);},[actorId,epoch,onClose]);
  useEffect(()=>{const old=commands.list().find(r=>r.actorId===actorId);if(old){setPending(old);setStep(3);setError("原操作结果待确认，请查询原命令。");}},[actorId]);
  useEffect(()=>{if(!actorId)return;try{const saved=JSON.parse(sessionStorage.getItem(`nexion-bulk-draft:${actorId}`)??"{}");setText(typeof saved.text==="string"?saved.text:"");setIntent(saved.intent==="MAINTENANCE"?"MAINTENANCE":"SERVICE");}catch{setError("群发草稿暂不能恢复，请在本页核对。");}setDraftOwner(actorId);},[actorId,epoch]);
  useEffect(()=>{if(!actorId||draftOwner!==actorId)return;try{sessionStorage.setItem(`nexion-bulk-draft:${actorId}`,JSON.stringify({text,intent}));}catch{setError("群发草稿暂不能持久保存，请在本页完成。");}},[actorId,draftOwner,text,intent]);
  useEffect(()=>{return()=>{generation.current++;stamp.current=`unmounted:${generation.current}`;imageSelection.current++;const current=imageRef.current;if(current)URL.revokeObjectURL(current.url);imageRef.current=null;};},[]);
  useEffect(()=>{
    const controller=new AbortController();setQuery(null);setError("");
    supportEnhancements.bulkPreview({filters,customerIds:[],excludedIds:[],selectionMode:"ALL_FILTERED"},controller.signal).then(v=>{if(!controller.signal.aborted)setQuery(v);}).catch(e=>{if(!controller.signal.aborted)setError(bulkPreviewError(e));});
    return()=>controller.abort();
  },[filters,retry,epoch]);
  const candidates=query?[...query.customers.map(c=>({id:c.id,reason:""})),...query.excluded.map(c=>({id:c.id,reason:c.reason}))]:[];
  const pageRows=candidates.slice((page-1)*10,page*10);
  useEffect(()=>{
    if(!query)return;const controller=new AbortController();
    Promise.allSettled(pageRows.map(c=>supportEnhancements.profile(c.id,controller.signal))).then(results=>{if(controller.signal.aborted)return;setProfiles(old=>{const next={...old};results.forEach((r,i)=>{if(r.status==="fulfilled")next[pageRows[i].id]=r.value;else delete next[pageRows[i].id];});return next;});});
    return()=>controller.abort();
  },[query,page,epoch]);
  useEffect(()=>{
    const controller=new AbortController();setJobs(null);setJobsError("");
    supportEnhancements.bulkJobs(jobsPage,controller.signal).then(p=>{if(!controller.signal.aborted){setJobs(p.records);setJobsTotal(p.total);}}).catch(e=>{if(!controller.signal.aborted)setJobsError(displayAdminError(e));});
    return()=>controller.abort();
  },[jobsPage,resultRetry,epoch]);
  useEffect(()=>{
    if(!job)return;const controller=new AbortController();let timer:ReturnType<typeof setTimeout>|undefined;
    const read=async()=>{const results=await Promise.allSettled([supportEnhancements.bulkJob(job.batchId,controller.signal),supportEnhancements.bulkRecipients(job.batchId,recipientPage,controller.signal)]);if(controller.signal.aborted)return;
      let failure="";if(results[0].status==="fulfilled"){setJob(results[0].value);if(["QUEUED","RUNNING"].includes(results[0].value.state))timer=setTimeout(()=>void read(),3000);}else failure=displayAdminError(results[0].reason);
      if(results[1].status==="fulfilled"){setRecipients(results[1].value.records);setRecipientTotal(results[1].value.total);}else{setRecipients(null);failure=displayAdminError(results[1].reason);}setResultError(failure);
    };setRecipients(null);void read();return()=>{controller.abort();if(timer)clearTimeout(timer);};
  },[job?.batchId,recipientPage,resultRetry,epoch]);
  const setFilter=(key:keyof BulkFilters,value:unknown)=>setFilterDraft(f=>({...f,[key]:value===""?undefined:value}));
  const levels=[...new Set(Object.values(profiles).flatMap(p=>typeof p.identity.data?.level==="string"?[p.identity.data.level]:[]))];
  const tags=[...new Set(Object.values(profiles).flatMap(p=>Array.isArray(p.annotations.data?.customTags)?p.annotations.data.customTags.filter((v):v is string=>typeof v==="string"):[]))];
  const currencies=[...new Set(Object.values(profiles).flatMap(p=>Array.isArray(p.finance.data?.byCurrency)?p.finance.data.byCurrency.map((v:Record<string,unknown>)=>v.currency).filter((v):v is string=>typeof v==="string"):[]))];
  const insert=(value:string)=>{const start=composerRef.current?.selectionStart??text.length,end=composerRef.current?.selectionEnd??start;setText(text.slice(0,start)+value+text.slice(end));requestAnimationFrame(()=>{composerRef.current?.focus();composerRef.current?.setSelectionRange(start+value.length,start+value.length);});};
  async function freeze(){if(!selected.size||busy)return;const saved=stamp.current;setBusy(true);setError("");try{const next=await supportEnhancements.bulkPreview({filters,customerIds:[...selected],excludedIds:[],selectionMode:"CROSS_PAGE"});if(saved!==stamp.current)return;if(next.actorId!==actorId)throw new Error("invalid scope");if(!next.count){setSelection(next);setError("所选客户均被排除，请核对名单。");return;}const checked:Record<string,SupportProfile>={};for(let i=0;i<next.customers.length;i+=10){const chunk=next.customers.slice(i,i+10);const details=await Promise.all(chunk.map(c=>supportEnhancements.profile(c.id)));if(saved!==stamp.current)return;details.forEach((profile,j)=>{checked[chunk[j].id]=profile;});}setProfiles(old=>({...old,...checked}));setSelection(next);setAck(false);setStep(2);}catch(e){if(saved===stamp.current)setError(bulkPreviewError(e));}finally{if(saved===stamp.current)setBusy(false);}}
  async function chooseFile(file?:File){if(!file||busy)return;const chosen=++imageSelection.current,saved=stamp.current;setUploadError("");try{const policy=await supportClient.attachmentPolicy();if(saved!==stamp.current||chosen!==imageSelection.current)return;if(!policy.available||!policy.allowedMimeTypes.includes(file.type as "image/png"|"image/jpeg")||policy.maxBytes!==null&&file.size>policy.maxBytes)throw new Error("请选择符合当前格式及大小要求的图片。");const decoded=await createImageBitmap(file);const pixels=decoded.width*decoded.height;decoded.close();if(policy.maxPixels!==null&&pixels>policy.maxPixels)throw new Error("图片像素超过当前上限。");if(saved!==stamp.current||chosen!==imageSelection.current)return;if(imageRef.current)URL.revokeObjectURL(imageRef.current.url);setChoice(null);setImage({file,url:URL.createObjectURL(file),id:crypto.randomUUID(),key:crypto.randomUUID()});}catch(e){if(saved===stamp.current&&chosen===imageSelection.current)setUploadError(e instanceof SupportClientError?displayAdminError(e):e instanceof Error&&e.message.startsWith("图片")||e instanceof Error&&e.message.startsWith("请选择")?e.message:"图片无法解码，请选择 JPG 或 PNG。");}}
  async function upload(){if(!image||uploading||image.assetId)return;const saved=stamp.current,current=image;setUploading(true);setUploadError("");try{const asset=await supportEnhancements.bulkUpload(current.file,current.id,current.key);if(saved===stamp.current&&imageRef.current?.id===current.id)setImage({...current,assetId:asset.assetId});}catch(e){if(saved===stamp.current)setUploadError(displayAdminError(e));}finally{if(saved===stamp.current)setUploading(false);}}
  const input:BulkContent|undefined=selection?{selectionId:selection.selectionId,intent,kind:image?"IMAGE":choice?.kind??"TEXT",content:text.trim(),skuId:choice?.kind==="SKU"?choice.skuId:undefined,linkTarget:choice?.kind==="LINK"?choice.linkTarget:undefined,assetId:image?.assetId,reason:reason.trim()}:undefined;
  const ready=Boolean(input&&selection?.count&&Date.parse(selection.expiresAt)>Date.now()&&reason.trim().length>=8&&reason.trim().length<=200&&ack&&(image?image.assetId:text.trim()));
  async function submit(recover=false){
    if(busy||!recover&&!ready)return;
    const record=pending??(input?{fingerprint:`${actorId}:create`,commandKey:crypto.randomUUID(),createdAt:Date.now(),expiresAt:Date.now()+86400000,actorId,payload:input}:null);if(!record)return;
    commands.remember(record.fingerprint,record.commandKey,{actorId:record.actorId,payload:record.payload,batchId:record.batchId,action:record.action,mutation:record.mutation,readOnlyRecovery:record.readOnlyRecovery});setPending(record);if(!commands.isDurablyStored(record.fingerprint,record.commandKey)){setError("原命令暂不能持久保存，尚未提交；请恢复浏览器存储后用此命令重试。");return;}setBusy(true);setError("");const saved=stamp.current;
    let submitted=false;
    try{
      const recovered=recover?await supportClient.command(record.commandKey).catch(e=>{if(e instanceof SupportClientError&&e.status===404)return null;throw e;}):null;
      if(saved!==stamp.current)return;
      if(recovered&&recovered.status!=="SUCCEEDED"&&recovered.status!=="FAILED"){setError("服务端结果仍待确认，请稍后查询原命令。");return;}
      if(record.readOnlyRecovery&&recovered?.status!=="SUCCEEDED"&&recovered?.status!=="FAILED"){setError("原操作尚未确认；因归属变化只查询结果，暂不能重新创建或发送。");return;}
      if(recovered?.status==="FAILED"){commands.forget(record.fingerprint);setPending(null);setError("原操作确认失败，输入已保留，请重新核对。");return;}
      if(!recovered)submitted=true;
      const next=recovered?parseBulkJob(recovered.result):record.action&&record.batchId&&record.mutation?await supportEnhancements.bulkMutate(record.batchId,record.action,record.mutation,record.commandKey):await supportEnhancements.bulkCreate(record.payload,record.commandKey);
      if(saved!==stamp.current)return;commands.forget(record.fingerprint);setPending(null);setJob(next);setStep(4);setRecipientPage(1);setMutationAction(null);setMutationReason("");setResultRetry(n=>n+1);window.dispatchEvent(new Event("support-todo-changed"));
    }catch(e){if(saved===stamp.current){setError(displayAdminError(e));if(submitted&&e instanceof SupportClientError&&[400,403,404,409,422].includes(e.status)&&!isIndeterminateSupportError(e)){commands.forget(record.fingerprint);setPending(null);}}}finally{if(saved===stamp.current)setBusy(false);}
  }
  async function mutate(){if(!job||!mutationAction||mutationReason.trim().length<8||busy||pending)return;const payload=input??{selectionId:"result",intent:"SERVICE" as const,kind:"TEXT" as const,content:"",reason:mutationReason.trim()};const record:Stored={fingerprint:`${actorId}:${job.batchId}:${mutationAction}`,commandKey:crypto.randomUUID(),createdAt:Date.now(),expiresAt:Date.now()+86400000,actorId,payload,batchId:job.batchId,action:mutationAction,mutation:{expectedVersion:job.version,reason:mutationReason.trim()}};commands.remember(record.fingerprint,record.commandKey,{actorId,payload,batchId:record.batchId,action:record.action,mutation:record.mutation});setPending(record);if(!commands.isDurablyStored(record.fingerprint,record.commandKey))setError("原命令暂不能持久保存，尚未提交，请恢复存储后查询原操作。");}
  useEffect(()=>{if(pending?.action&&!busy)void submit(true);},[pending?.commandKey]);
  const names=(preview:BulkPreview)=>preview.customers.map(c=>{const p=profiles[c.id];return `${p?.identity.data?.nickname??"客户"} · ${p?.identity.data?.userNo??"编码未知"} · ID ${c.id} · 当前顾问 ${p?.service.data?.agentName??"资料未知"}`;});
  const excluded=(preview:BulkPreview)=><details><summary>排除 {preview.excluded.length} 位</summary>{preview.excluded.map(c=><p key={c.id}>客户 ID {c.id} · {reasonText[c.reason]??"资料或资格不符，需核对"}</p>)}</details>;
  return <Modal title="圈选客户群发" icon="users" wide busy={busy||uploading} onClose={onClose} footer={<div className="m-admin-toolbar"><button className="btn btn-sec btn-sm" disabled={busy||uploading} onClick={onClose}>{step===4?"关闭结果":"退出群发"}</button>{step>1&&step<4&&!pending&&<button className="btn btn-sec btn-sm" disabled={busy} onClick={()=>setStep(n=>n-1)}>上一步</button>}{step===1&&<button className="btn btn-pri btn-sm" disabled={!selected.size||busy||Boolean(pending)} onClick={()=>void freeze()}>{busy?"核对名单…":"下一步：编写内容"}</button>}{step===2&&<button className="btn btn-pri btn-sm" disabled={image?!image.assetId:!text.trim()} onClick={()=>{setStep(3);setAck(false);}}>下一步：确认名单</button>}{step===3&&!pending&&<button className="btn btn-pri btn-sm" disabled={!ready||busy} onClick={()=>void submit()}>{busy?"提交中…":"确认创建群发"}</button>}{pending&&<button className="btn btn-pri btn-sm" disabled={busy} onClick={()=>void submit(true)}>查询原操作结果</button>}</div>}>
    <p role="status">第 {step} 步：{["","圈选客户","编写内容","确认提交","逐客结果"][step]}</p>{error&&<p className="itint danger" role="alert">{error}</p>}
    {step===1&&<><p>只发送当前本人客户；两种主动群发均排除“不再维护”。选择保持原名单，新匹配客户不会自动加入。</p><div className="m-admin-toolbar">
      <label>搜索姓名或编码<input className="fld" value={filterDraft.keyword??""} onChange={e=>setFilter("keyword",e.target.value)}/></label>
      <label>账户活动<select className="fld" value={filterDraft.accountState??""} onChange={e=>setFilter("accountState",e.target.value)}><option value="">全部</option><option value="ACTIVE">活跃</option><option value="DORMANT">沉睡</option><option value="UNKNOWN">未知</option></select></label>
      <label>维护状态<select className="fld" value={filterDraft.maintenanceState??""} onChange={e=>setFilter("maintenanceState",e.target.value)}><option value="">全部</option><option value="ENABLED">正常维护</option><option value="DUE">待维护</option><option value="STOPPED">不再维护（仅核对）</option></select></label>
      <label>等级<select className="fld" value={filterDraft.level??""} onChange={e=>setFilter("level",e.target.value)}><option value="">全部已知及未知</option>{levels.map(v=><option key={v}>{v}</option>)}</select></label>
      <label>币种<select className="fld" value={filterDraft.currency??""} onChange={e=>setFilter("currency",e.target.value)}><option value="">选择实际币种</option>{currencies.map(v=><option key={v}>{v}</option>)}</select></label>
      {[["registeredFrom","注册起日"],["registeredTo","注册止日（不含）"],["activityFrom","活动起日"],["activityTo","活动止日（不含）"]].map(([key,label])=><label key={key}>{label}（UTC）<input type="date" value={typeof filterDraft[key as keyof BulkFilters]==="string"?(filterDraft[key as keyof BulkFilters] as string).slice(0,10):""} onChange={e=>setFilter(key as keyof BulkFilters,utc(e.target.value))}/></label>)}
      {[["depositMin","累计充值至少"],["depositMax","累计充值至多"],["withdrawalMin","累计提现至少"],["withdrawalMax","累计提现至多"]].map(([key,label])=><label key={key}>{label}<input className="fld" type="number" min="0" step="any" value={filterDraft[key as keyof BulkFilters] as string??""} onChange={e=>setFilter(key as keyof BulkFilters,e.target.value)}/></label>)}
    </div><fieldset><legend>自定义标签（来自已读取客户）</legend>{tags.length?tags.map(t=><label key={t}><input type="checkbox" checked={filterDraft.tagIds?.includes(t)??false} onChange={e=>setFilter("tagIds",e.target.checked?[...(filterDraft.tagIds??[]),t]:(filterDraft.tagIds??[]).filter(v=>v!==t))}/>{t}</label>):<span>尚无可读取标签。</span>}</fieldset><label><input type="checkbox" checked={filterDraft.includeUnknown===true} onChange={e=>setFilter("includeUnknown",e.target.checked)}/>明确纳入未知来源；未知不等于零金额</label><button className="l-btn sm primary" disabled={busy} onClick={()=>{setFilters({...filterDraft});setPage(1);setQuery(null);}}>查询筛选结果</button>
      {!query?<p role="status">{error?<button className="l-btn sm" onClick={()=>setRetry(n=>n+1)}>重新读取名单</button>:"正在核对筛选名单…"}</p>:<><div className="m-admin-toolbar"><span>可选 {query.count} 位 · 已选 {selected.size} 位</span><button className="l-btn sm" onClick={()=>setSelected(new Set([...selected,...pageRows.filter(c=>!c.reason).map(c=>c.id)]))}>选择本页</button><button className="l-btn sm" onClick={()=>setSelected(new Set(query.customers.map(c=>c.id)))}>选择当前全部筛选结果</button><button className="l-btn sm" onClick={()=>setSelected(new Set())}>清空选择</button></div>{pageRows.map(c=>{const p=profiles[c.id];return <label key={c.id} style={{display:"block",padding:10,borderBottom:"1px solid var(--v5-border)"}}><input type="checkbox" checked={selected.has(c.id)} disabled={Boolean(c.reason)} onChange={e=>setSelected(old=>{const n=new Set(old);if(e.target.checked)n.add(c.id);else n.delete(c.id);return n;})}/>{p?.identity.data?.nickname?String(p.identity.data.nickname):"客户"} · {String(p?.identity.data?.userNo??"编码未知")} · ID {c.id} · {c.reason?reasonText[c.reason]??"不符合当前范围":p?.service.data?.agentName?String(p.service.data.agentName):"当前本人归属（已核对）"}</label>;})}<div className="m-admin-toolbar"><button className="l-btn sm" disabled={page<=1} onClick={()=>setPage(n=>n-1)}>上一页</button><span>第 {page} 页 · 共 {candidates.length} 位</span><button className="l-btn sm" disabled={page*10>=candidates.length} onClick={()=>setPage(n=>n+1)}>下一页</button></div>{excluded(query)}</>}
    </>}
    {step===2&&selection&&<><p>已冻结 {selection.count} 位客户；内容返回修改时保留。</p><label>本条消息用途<select className="fld" value={intent} onChange={e=>setIntent(e.target.value as "SERVICE"|"MAINTENANCE")}><option value="SERVICE">普通服务</option><option value="MAINTENANCE">联系维护</option></select></label><p>普通服务不计维护；联系维护仅在消息成功提交后计一次，后续新的有效活动才形成成功维护。群发不清待回复。</p><SupportContentTools ctx={ctx} disabled={uploading} onInsert={insert} onSelect={v=>{if(image)URL.revokeObjectURL(image.url);setImage(null);setChoice(v);if(!text.trim())setText(v.kind==="SKU"?"推荐商品："+v.name:"查看："+v.name);}}/>{choice&&<p>已选：{choice.name}<button className="l-btn sm" onClick={()=>setChoice(null)}>取消推荐</button></p>}<label>发送文案<textarea ref={composerRef} className="fld" aria-label="群发文案" maxLength={10000} value={text} onChange={e=>setText(e.target.value)}/></label><label>群发图片<input type="file" accept="image/jpeg,image/png" disabled={uploading} onChange={e=>{void chooseFile(e.target.files?.[0]);e.target.value="";}}/></label>{image&&<div><img src={image.url} alt="群发图片预览" style={{maxWidth:180,maxHeight:150}}/><p>{image.assetId?"已上传，尚未发送":uploading?"正在上传…":"尚未上传"}</p><button className="l-btn sm" disabled={uploading||Boolean(image.assetId)} onClick={()=>void upload()}>上传或重试图片</button><button className="l-btn sm" disabled={uploading} onClick={()=>{URL.revokeObjectURL(image.url);setImage(null);}}>移除图片</button></div>}{uploadError&&<p role="alert">{uploadError}</p>}{excluded(selection)}</>}
    {step===3&&<>{pending?<p>已保存原操作号，查询和重试使用完全相同的名单及内容。</p>:selection&&<><h3>确认 {selection.count} 位 · 当前顾问本人</h3><details open><summary>冻结名单</summary>{names(selection).map((name,i)=><p key={selection.customers[i].id}>{name}</p>)}</details>{excluded(selection)}<p>用途：{intent==="SERVICE"?"普通服务":"联系维护"} · 内容类型：{image?"图片":choice?.kind==="SKU"?"商品推荐":choice?.kind==="LINK"?"页面链接":"文字"}</p><p style={{whiteSpace:"pre-wrap"}}>{text}</p>{choice&&<p>{choice.name}</p>}{image&&<img src={image.url} alt="确认群发图片" style={{maxWidth:180,maxHeight:150}}/>}<label>操作理由<textarea className="fld" value={reason} minLength={8} maxLength={200} onChange={e=>setReason(e.target.value)}/></label><label><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>已核对名单、当前顾问、用途和内容，确认逐客独立发送。</label><p>预览有效期至 {new Date(selection.expiresAt).toLocaleString("zh-CN")}；过期请返回选人重新核对。</p></>}</>}
    {step===4&&job&&<><h3>{stateText[job.state]??"待核对"} · {job.batchId}</h3><div className="m-admin-toolbar"><span>固定总数 {job.counts.total}</span><span>已提交 {job.counts.sent}</span><span>失败 {job.counts.failed}</span><span>跳过 {job.counts.skipped}</span><span>取消 {job.counts.cancelled}</span><span>待处理（已知）{job.counts.pending-job.counts.unknown}</span><span>待确认 {job.counts.unknown}</span></div><p>冻结 {job.frozenCount} 位 · 当前可读 {job.visibleCount} 位；执行结束不代表全部成功。</p>{job.contentRestricted?<p>客户归属已变化，部分内容、附件和明细受限；不显示旧缓存。</p>:<p>{job.content}</p>}<button className="l-btn sm" onClick={()=>setResultRetry(n=>n+1)}>刷新原批次</button>{resultError&&<p role="alert">结果读取失败，以上为上次已核对值：{resultError}</p>}{!recipients?<p role="status">逐客明细暂未读取</p>:recipients.map((r,i)=><p key={r.customerId+":"+i}>客户 ID {r.customerId} · {r.resultCertainty==="UNKNOWN"?"结果待确认":stateText[r.state]??"待核对"}{r.failureCode?` · ${{SUPPORT_ASSIGNMENT_CHANGED:"客户已转绑，本次不再发送",SUPPORT_MAINTENANCE_STOPPED:"客户已停止维护",SUPPORT_AGENT_UNAVAILABLE:"顾问当前不可发送",RESULT_UNKNOWN:"需核对原提交结果",SUPPORT_BULK_PAYLOAD_REVIEW_REQUIRED:"原内容需核对，暂不自动重发"}[r.failureCode]??"执行未通过，请核对客户与原消息"}`:""}{r.retryable?" · 可核对重试":""}{r.conversationNo&&<a className="l-btn sm" href={`/service/sessions?conversationNo=${encodeURIComponent(r.conversationNo!)}`}>打开原客户会话</a>}</p>)}<div className="m-admin-toolbar"><button className="l-btn sm" disabled={recipientPage<=1} onClick={()=>setRecipientPage(n=>n-1)}>上一页</button><span>第 {recipientPage} 页 · 可读 {recipientTotal} 位</span><button className="l-btn sm" disabled={recipientPage*10>=recipientTotal} onClick={()=>setRecipientPage(n=>n+1)}>下一页</button><button className="l-btn sm" disabled={job.actorId!==actorId||!canWrite||!job.counts.pending||Boolean(pending)} onClick={()=>setMutationAction("cancel")}>取消未提交项</button><button className="l-btn sm" disabled={job.actorId!==actorId||!canWrite||!(job.counts.failed||job.counts.unknown)||Boolean(pending)} onClick={()=>setMutationAction("retry")}>核对并重试失败项</button></div>{mutationAction&&<div><p>{mutationAction==="cancel"?"取消只影响未提交项，已经提交的消息保留。":"先核对原消息，已提交、已转绑或不再维护项不重发。"}</p><label>操作理由（8–200 字）<textarea className="fld" minLength={8} maxLength={200} value={mutationReason} onChange={e=>setMutationReason(e.target.value)}/></label><p>理由至少 8 字且不超过 200 字，提交中或原结果未确认时暂不能重复操作。</p><button className="l-btn sm primary" disabled={busy||Boolean(pending)||mutationReason.trim().length<8||mutationReason.trim().length>200} onClick={()=>void mutate()}>确认{mutationAction==="cancel"?"取消剩余":"核对重试"}</button><button className="l-btn sm" disabled={busy} onClick={()=>setMutationAction(null)}>返回结果</button></div>}</>}
    <details><summary>已提交批次（可关闭后恢复）</summary>{jobsError?<p role="alert">{jobsError}<button className="l-btn sm" onClick={()=>setResultRetry(n=>n+1)}>重试批次列表</button></p>:!jobs?<p role="status">正在读取…</p>:jobs.map(j=><button className="l-btn sm" key={j.batchId} disabled={Boolean(pending)||busy} onClick={()=>{setJob(j);setStep(4);setRecipientPage(1);}}>{j.batchId} · {stateText[j.state]??"待核对"} · 固定 {j.frozenCount} 位</button>)}<div className="m-admin-toolbar"><button className="l-btn sm" disabled={jobsPage<=1} onClick={()=>setJobsPage(n=>n-1)}>上一页批次</button><span>第 {jobsPage} 页 · {jobsTotal} 批</span><button className="l-btn sm" disabled={jobsPage*10>=jobsTotal} onClick={()=>setJobsPage(n=>n+1)}>下一页批次</button></div></details>
  </Modal>;
}
