import { createHmac } from "node:crypto";
import { readFileSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { expect, test, type Page } from "@playwright/test";

const fixturePath = process.env.A_PERMISSION_FIXTURE_PATH || "";
const evidenceDir = process.env.A_FINAL_EVIDENCE_DIR || "";
const finalToken = process.env.A_FINAL_RERUN_TOKEN || "";
const pages = [
  ["A1", "/platform/rbac", "/api/admin/platform/accounts/overview"], ["A2", "/platform/audit", "/api/admin/platform/audit/overview"],
  ["A3", "/platform/config", "/api/admin/platform/config/overview"], ["A4", "/platform/events", "/api/admin/platform/events/overview"],
  ["A5", "/platform/params-registry", "/api/admin/platform/params-registry"], ["A6", "/platform/roles", "/api/admin/platform/roles/overview"],
  ["A7", "/platform/menus", "/api/admin/platform/menus/overview"], ["A8", "/platform/permissions", "/api/admin/platform/permissions?pageNum=1&pageSize=20"],
] as const;
type Account = { username: string; password: string; totpSecret: string };
type Fixture = { accounts: Record<"maker" | "readonly" | "nowrite" | "nomenu", Account> };
let lastStep = -1;
function otp(secret: string) { const abc="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567"; const s=secret.replace(/\W/g,"").toUpperCase(); let b=""; for(const c of s)b+=abc.indexOf(c).toString(2).padStart(5,"0"); const bytes=Buffer.from(Array.from({length:Math.floor(b.length/8)},(_,i)=>parseInt(b.slice(i*8,i*8+8),2))); const n=Buffer.alloc(8); n.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000))); const d=createHmac("sha1",bytes).update(n).digest(); const o=d[d.length-1]&15; return String((d.readUInt32BE(o)&0x7fffffff)%1e6).padStart(6,"0"); }
async function login(page: Page, a: Account) { await page.goto("http://127.0.0.1:3002",{waitUntil:"domcontentloaded"}); await page.locator('input[autocomplete="username"]').fill(a.username); await page.locator('input[autocomplete="current-password"]').fill(a.password); const response=page.waitForResponse(r=>new URL(r.url()).pathname==="/api/admin/auth/login"&&r.request().method()==="POST"); await page.getByRole("button",{name:/登录|继续/}).click(); const loginResponse=await response; const loginRaw=await loginResponse.text(); expect(loginResponse.status(),`login ${a.username}: ${loginRaw}`).toBe(200); const field=page.getByLabel("一次性验证码"); await expect(field).toBeVisible({timeout:15000}); const step=Math.floor(Date.now()/30000); if(step<=lastStep||30000-Date.now()%30000<3000) await page.waitForTimeout(30000-Date.now()%30000+500); lastStep=Math.floor(Date.now()/30000); await field.fill(otp(a.totpSecret)); await page.getByRole("button",{name:"验证并进入",exact:true}).click(); await expect(page.locator("aside")).toBeVisible({timeout:30000}); }
test.describe.configure({mode:"serial",timeout:240000});
test("A final: visible-sidebar A1-A8, refresh/relogin, four-role five-layer negative matrix",async({page,browser})=>{
  test.skip(!fixturePath||!evidenceDir||!finalToken,"final restricted fixture/evidence/token required");
  const fixture=JSON.parse(readFileSync(fixturePath,"utf8")) as Fixture; mkdirSync(evidenceDir,{recursive:true}); const ev:any={build:(readFileSync(path.resolve(".next/BUILD_ID"),"utf8")).trim(),pages:{},roles:{},errors:[],logout401:[]}; let logoutPending=false;
  page.on("pageerror",e=>ev.errors.push(`pageerror:${e.message}`)); page.on("console",m=>{if(m.type()!=="error")return; const url=m.location().url; const expected=/401 \(Unauthorized\)/.test(m.text())&&(/\/api\/admin\/auth\/session/.test(url)||(logoutPending&&/\/api\/admin\//.test(url))); if(expected)ev.logout401.push({url,text:m.text()}); else ev.errors.push(`console:${m.text()}@${url}`)});
  try { await login(page,fixture.accounts.maker); const group=page.getByRole("button",{name:/平台基础\s+A|A\s+平台基础/}).first(); if(await group.getAttribute("aria-expanded")!=="true")await group.click();
    for(const [id,url,api] of pages){ if(await group.getAttribute("aria-expanded")!=="true")await group.click(); const link=page.locator(`aside a[href="${url}"]`).first(); await expect(link,`${id} visible sidebar`).toBeVisible(); const response=page.waitForResponse(r=>r.url().includes(api.split("?")[0])&&r.request().method()==="GET"); await link.click(); await expect(page).toHaveURL(new RegExp(`${url.replace(/[/?]/g,"\\$&")}$`)); const r=await response; ev.pages[id]={status:r.status()}; expect(r.status()).toBe(200); await page.reload({waitUntil:"domcontentloaded"}); await expect(page).toHaveURL(new RegExp(`${url.replace(/[/?]/g,"\\$&")}$`)); }
    logoutPending=true; await page.request.post("/api/admin/auth/logout"); expect((await page.request.get("/api/admin/auth/session")).status()).toBe(401); await page.goto("http://127.0.0.1:3002",{waitUntil:"domcontentloaded"}); await expect(page.locator('input[autocomplete="username"]')).toBeVisible(); expect(await page.locator("aside").count()).toBe(0); await page.waitForTimeout(3000); await login(page,fixture.accounts.maker); logoutPending=false; ev.roles.maker={visible:8,relogin:true,session401:true,oldDataCleared:true};
    for(const role of ["readonly","nowrite"] as const){ const c=await browser.newContext({baseURL:"http://127.0.0.1:3002"}); const p=await c.newPage(); await login(p,fixture.accounts[role]); const g=p.getByRole("button",{name:/平台基础\s+A|A\s+平台基础/}).first(); if(await g.getAttribute("aria-expanded")!=="true")await g.click(); let visible=0; for(const [,url,api] of pages){if(await p.locator(`aside a[href="${url}"]`).count())visible++; const r=await p.request.get(api); expect(r.status()).toBe(200);} const denied=await p.request.patch("/api/admin/platform/accounts/99535/status",{data:{status:"disabled",reason:"final permission denial",operator:fixture.accounts[role].username,expectedVersion:"12"}}); expect(denied.status()).toBe(403); ev.roles[role]={visible,read200:8,write403:true}; await c.close(); }
    const n=await browser.newContext({baseURL:"http://127.0.0.1:3002"}); const np=await n.newPage(); await login(np,fixture.accounts.nomenu); const ng=np.getByRole("button",{name:/平台基础\s+A|A\s+平台基础/}).first(); if(await ng.count()&&await ng.getAttribute("aria-expanded")!=="true")await ng.click().catch(()=>undefined); const menuCount=await np.locator("aside a[href^='/platform/']").count(); for(const[,,api]of pages){expect((await np.request.get(api)).status()).toBe(403); expect((await np.request.patch("/api/admin/platform/accounts/99535/status",{data:{status:"disabled",reason:"nomenu denial",operator:fixture.accounts.nomenu.username,expectedVersion:"12"}})).status()).toBe(403);} await np.goto("http://127.0.0.1:3002/platform/rbac",{waitUntil:"domcontentloaded"}); await expect.poll(()=>np.url(),{timeout:10000}).not.toContain("/platform/rbac"); await np.reload({waitUntil:"domcontentloaded"}); ev.roles.nomenu={visible:menuCount,read403:8,write403:8,directRouteDenied:true,refreshDenied:true}; expect(menuCount).toBe(0); await n.close(); expect(ev.errors).toEqual([]); }
  finally { writeFileSync(path.join(evidenceDir,"a004-final-owner.json"),JSON.stringify(ev,null,2)); }
});
