import { createHmac } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { expect, test, type Page, type Response } from "@playwright/test";

const RUN_ID = "pc-full-acceptance-20260729-114336";
const MANIFEST = process.env.FINAL_FIXTURE_MANIFEST_PATH ?? `D:/workspace/bug-pic/.restricted/${RUN_ID}/A/final-fixture-admin-window/final-domain-checkers.json`;
const REASON = `${RUN_ID} final bootstrap closeout`; type F = { username: string; password: string; totpSecret: string }; type M = { bootstrapCleanup: F; finalAccounts: { a6_reviewer: F } };
test.describe.configure({ mode: "serial", timeout: 180_000 });
test("FINAL closeout: bootstrap visible A1 disable is independently A2-approved and session is revoked", async ({ page, browser }, info) => {
 const m = JSON.parse(await readFile(MANIFEST, "utf8")) as M; const target = m.bootstrapCleanup; await login(page, target); const c = await browser.newContext(); const checker = await c.newPage(); try { await login(checker, m.finalAccounts.a6_reviewer); await nav(page, "运营账号 & RBAC A1", /\/platform\/rbac$/); await page.locator("select.pager-size").selectOption("50"); const row = await find(page, target.username); const before = await row.innerText(); await row.getByRole("button", { name: "禁用", exact: true }).click(); const ticket = await submit(page, (r) => r.request().method() === "POST" && r.url().endsWith("/api/admin/platform/audit/operations")); await approve(checker, ticket); const revoked = await page.request.get("/api/admin/auth/session"); expect(revoked.status(), "bootstrap approval后会话必须失效").toBe(401); await nav(checker, "运营账号 & RBAC A1", /\/platform\/rbac$/); await checker.locator("select.pager-size").selectOption("50"); const after = await find(checker, target.username); expect(await after.locator("td").nth(3).innerText()).toContain("已禁用"); expect(await after.locator("td").nth(5).innerText()).toContain("0"); await nav(checker, "审计 & 操作确认 A2", /\/platform\/audit$/); await checker.reload(); expect(await checker.locator("tbody tr").filter({ hasText: target.username }).count()).toBe(0); const payload = JSON.stringify({ runId: RUN_ID, targetDigest: digest(target.username), beforeDigest: digest(before), disabled: true, sessionStatus: revoked.status(), roleRelationCount: 0, targetPendingAuditRows: 0, verifiedAt: new Date().toISOString() }, null, 2); await writeFile(info.outputPath("bootstrap-closeout.json"), `${payload}\nsha256=${digest(payload)}\n`); } finally { await c.close(); }
});
async function login(p: Page, f: F) { await p.goto("/"); await p.locator('input[autocomplete="username"]').fill(f.username); await p.locator('input[autocomplete="current-password"]').fill(f.password); await p.getByRole("button", { name: "继续", exact: true }).click(); const otp=p.getByLabel("一次性验证码"); await otp.waitFor({state:"visible",timeout:15000}); await otp.fill(totp(f.totpSecret)); const r=p.waitForResponse(x=>x.request().method()==="POST"&&x.url().endsWith("/api/admin/auth/mfa/verify")); await p.getByRole("button",{name:"验证并进入",exact:true}).click(); expect((await r).status()).toBe(200); await expect(p.locator("aside")).toBeVisible({timeout:30000}); }
async function nav(p: Page,n:string,u:RegExp){const l=p.locator("aside").getByRole("link",{name:n,exact:true});if(!await l.isVisible().catch(()=>false))await p.locator("aside").getByRole("button",{name:/平台基础.*A|A.*平台基础/}).click();await l.click();await expect(p).toHaveURL(u)}
async function find(p: Page,u:string){for(let i=0;i<20;i++){const r=p.locator("tbody tr").filter({hasText:u});if(await r.count())return r;const n=p.locator("button.pager-btn").last();if(await n.isDisabled())break;await n.click()}throw new Error("TARGET_ACCOUNT_NOT_VISIBLE")}
async function submit(p:Page,pred:(r:Response)=>boolean){const w=p.waitForResponse(pred);const d=p.getByRole("dialog").last();await d.getByLabel(/操作理由/).fill(REASON);await d.getByRole("button",{name:"确认提交",exact:true}).click();const x=await (await w).json() as {code?:number;data?:{operationId?:string;id?:string}};expect(x.code).toBe(0);const id=x.data?.operationId??x.data?.id;expect(id).toMatch(/^(?:WO|OP)-/);return id!}
async function approve(p:Page,id:string){await nav(p,"审计 & 操作确认 A2",/\/platform\/audit$/);await p.reload();const r=p.locator("tbody tr").filter({hasText:id});await expect(r).toBeVisible();await r.getByRole("button",{name:"执行",exact:true}).click();const w=p.waitForResponse(x=>x.request().method()==="POST"&&x.url().endsWith(`/api/admin/platform/audit/operations/${id}/approve`));const d=p.getByRole("dialog").last();await d.getByLabel(/操作理由/).fill(REASON);await d.getByRole("button",{name:"确认提交",exact:true}).click();expect((await w).status()).toBe(200)}
function totp(s:string){const a="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";let b="";for(const c of s.replace(/[^A-Z2-7]/gi,"").toUpperCase())b+=a.indexOf(c).toString(2).padStart(5,"0");const z:number[]=[];for(let i=0;i+8<=b.length;i+=8)z.push(Number.parseInt(b.slice(i,i+8),2));const c=Buffer.alloc(8);c.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)));const h=createHmac("sha1",Buffer.from(z)).update(c).digest(),o=h[h.length-1]&15;return String((h.readUInt32BE(o)&0x7fffffff)%1e6).padStart(6,"0")}
function digest(x:string){return createHmac("sha256","final-closeout").update(x).digest("hex")}
