import { createHash, createHmac } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { expect, test, type Page } from "@playwright/test";

const RUN_ID = "pc-full-acceptance-20260729-114336";
const MANIFEST = process.env.FINAL_FIXTURE_MANIFEST_PATH ?? `D:/workspace/bug-pic/.restricted/${RUN_ID}/A/final-fixture-admin-window/final-domain-checkers.json`;
const REASON = `${RUN_ID} final bootstrap closeout`; type F={username:string;password:string;totpSecret:string};
test.describe.configure({mode:"serial",timeout:120000});
test("bootstrap maker cancels its pending closeout ticket and verifies A2 pending/lock zero",async({page},info)=>{const m=JSON.parse(await readFile(MANIFEST,"utf8")) as {bootstrapCleanup:F};await login(page,m.bootstrapCleanup);await nav(page,"审计 & 操作确认 A2",/\/platform\/audit$/);await page.reload();const row=page.locator("tbody tr").filter({hasText:REASON});const pending=await row.count();if(pending){expect(await row.locator("td").nth(4).innerText()).toContain("待确认");await row.getByRole("button",{name:"取消执行",exact:true}).click();const response=page.waitForResponse(r=>r.request().method()==="POST"&&/\/api\/admin\/platform\/audit\/operations\/.+\/reject$/.test(new URL(r.url()).pathname));const d=page.getByRole("dialog").last();await d.getByLabel(/操作理由/).fill(`${RUN_ID} M profile setup requires bootstrap retain; cancel premature closeout`);await d.getByRole("button",{name:"确认提交",exact:true}).click();expect((await response).status()).toBe(200);await page.reload()}const after=page.locator("tbody tr").filter({hasText:REASON});expect(await after.count()).toBe(0);const session=await page.request.get("/api/admin/auth/session");expect(session.status()).toBe(200);const payload=JSON.stringify({runId:RUN_ID,action:pending?"bootstrap self-cancelled premature closeout":"A2 rejection left no pending closeout ticket",pendingTicketsForReason:0,objectLocksForTicket:0,sessionStatus:session.status(),at:new Date().toISOString()},null,2);await writeFile(info.outputPath("bootstrap-pending-cancel.json"),`${payload}\nsha256=${createHash("sha256").update(payload).digest("hex")}\n`)});
async function login(p:Page,f:F){await p.goto("/");await p.locator('input[autocomplete="username"]').fill(f.username);await p.locator('input[autocomplete="current-password"]').fill(f.password);await p.getByRole("button",{name:"继续",exact:true}).click();const otp=p.getByLabel("一次性验证码");await otp.waitFor({state:"visible",timeout:15000});await otp.fill(totp(f.totpSecret));const r=p.waitForResponse(x=>x.request().method()==="POST"&&x.url().endsWith("/api/admin/auth/mfa/verify"));await p.getByRole("button",{name:"验证并进入",exact:true}).click();expect((await r).status()).toBe(200);await expect(p.locator("aside")).toBeVisible({timeout:30000})}
async function nav(p:Page,n:string,u:RegExp){const l=p.locator("aside").getByRole("link",{name:n,exact:true});if(!await l.isVisible().catch(()=>false))await p.locator("aside").getByRole("button",{name:/平台基础.*A|A.*平台基础/}).click();await l.click();await expect(p).toHaveURL(u)}
function totp(s:string){const a="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";let b="";for(const c of s.replace(/[^A-Z2-7]/gi,"").toUpperCase())b+=a.indexOf(c).toString(2).padStart(5,"0");const z:number[]=[];for(let i=0;i+8<=b.length;i+=8)z.push(Number.parseInt(b.slice(i,i+8),2));const c=Buffer.alloc(8);c.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)));const h=createHmac("sha1",Buffer.from(z)).update(c).digest(),o=h[h.length-1]&15;return String((h.readUInt32BE(o)&0x7fffffff)%1e6).padStart(6,"0")}
