import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {createRequire} from 'node:module';
const ts=createRequire(import.meta.url)('typescript'),source=fs.readFileSync('app/components/domain-views/m-tabs/m5-scripts.tsx','utf8');
function harness({seatType='DEDICATED',mode='MANAGED',role='support',authorities=['service_m1_read','service_m5_write'],failure=false}={}){
 let hooks;const calls=[],auth={session:{role,adminId:17,authorities,menuCodes:['M1','M5']},authEpoch:1},useAdminAuth=s=>s(auth);useAdminAuth.getState=()=>auth;
 const no=()=>{},jsx=(type,props)=>({type,props}),react={useState:i=>hooks.state(i),useEffect:(f,d)=>hooks.effect(f,d),useMemo:f=>f(),useRef:i=>hooks.ref(i)};
 const module={exports:{}};vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022}}).outputText,{module,exports:module.exports,AbortController,Map,Set,Object,require:id=>{if(id==='react')return react;if(id==='react/jsx-runtime')return{jsx,jsxs:jsx};if(id.includes('m-client'))return{fetchMSupportAgentsPage:async()=>({records:[],advisorAssignments:[],total:0}),fetchMAdvisorBindingUsers:async()=>({records:[],total:0})};if(id.includes('support-analytics-client'))return{supportAnalyticsClient:{query:async options=>{calls.push(options);if(failure)throw{status:403};return{scopeSummary:{mode}};}}};if(id.includes('admin-auth'))return{useAdminAuth};if(id.includes('shell-authorities'))return{adminShellSessionKey:s=>s?JSON.stringify(s):'anonymous'};if(id.includes('error-messages'))return{displayAdminError:()=> '读取失败'};if(id.includes('design-kit'))return{Icon:no,Modal:'Modal',Toggle:no};throw Error(id);}});
 const params={'I.support.agents':JSON.stringify([{adminId:17,seatType,position:seatType==='MANAGER'?'客服主管':'专属客服',serviceTypes:['advisor'],enabled:true,maxConcurrent:5,assignedUserCount:0}]),'I.support.advisorAssignments':'[]','I.session.templatesAvailable':'1'};
 const ctx={params,pget:key=>params[key],setParam:async()=>true,toast:no,openActionConfirm:no};const values=[],effects=[];let cursor;
 const render=()=>{for(let pass=0;pass<10;pass++){cursor=0;const pending=[];hooks={state(initial){const i=cursor++;if(!(i in values))values[i]=typeof initial==='function'?initial():initial;return[values[i],n=>values[i]=typeof n==='function'?n(values[i]):n];},ref(initial){const i=cursor++;return values[i]??(values[i]={current:initial});},effect(fn,deps){const i=cursor++;if(!effects[i]||deps.some((d,n)=>!Object.is(d,effects[i].deps[n])))pending.push(()=>{effects[i]?.cleanup?.();effects[i]={deps,cleanup:fn()};});}};const tree=module.exports.M5Scripts({ctx});if(!pending.length)return tree;pending.forEach(fn=>fn());}throw Error('effects');};return{render,calls,auth};
}
function nodes(x){if(Array.isArray(x))return x.flatMap(nodes);return x&&typeof x==='object'?[x,...nodes(x.props?.children)]:[];}function text(x){if(Array.isArray(x))return x.map(text).join('');return x&&typeof x==='object'?text(x.props?.children):typeof x==='string'?x:'';}
const flush=async()=>{for(let i=0;i<8;i++)await Promise.resolve();};
const canManage=tree=>nodes(tree).some(n=>n.type==='button'&&text(n).includes('新增话术'));
test('M5 management uses current MANAGED qualification even for DEDICATED profile and rejects revoked legacy MANAGER',async()=>{
 for(const options of [{seatType:'DEDICATED',mode:'MANAGED',expected:true},{seatType:'MANAGER',mode:'PERSONAL',expected:false},{seatType:'MANAGER',failure:true,expected:false},{seatType:'MANAGER',mode:'ALL',expected:false},{seatType:'MANAGER',authorities:['service_m5_write'],expected:false},{mode:'MANAGED',authorities:['service_m1_read'],expected:false}]){const h=harness(options);let tree=h.render();assert.equal(canManage(tree),false);await flush();tree=h.render();assert.equal(canManage(tree),options.expected,JSON.stringify(options));if(!options.authorities||options.authorities.includes('service_m1_read'))assert.equal(h.calls[0]?.view,'OVERVIEW');else assert.equal(h.calls.length,0);}
});
test('M5 keeps real super and content precise write authority and immediately rejects old actor scope',async()=>{
 for(const role of ['superadmin','content']){const h=harness({role,authorities:['service_m5_write']});assert.equal(canManage(h.render()),true);assert.equal(h.calls.length,0);}
 const h=harness();h.render();await flush();assert.equal(canManage(h.render()),true);h.auth.session={...h.auth.session,adminId:18};h.auth.authEpoch++;assert.equal(canManage(h.render()),false);
});
