import test from "node:test";
import assert from "node:assert/strict";
import { harness, storage, makeClient, group, detail, member, qualification, deferred, text, all, why } from "./helpers.mjs";
const key="12345678-1234-1234-1234-123456789012";
async function createDraft(h){await h.flush();h.click("创建组");h.input("本人的新组");h.reason();}
const rawMember={adminId:"21",version:2,groupId:"5",accountStatus:1,handoverRequired:false,boundCustomers:4};
test("server-provided MANAGED allows a supervisor with no groups to create self-owned group without global/A1 reads",async()=>{
  const h=harness({implementations:{createSupportGroup:()=>{throw new Error("network unknown");}}});await createDraft(h);h.click("确认并提交");await h.flush();const call=h.calls.find(c=>c.name==="createSupportGroup");assert.equal(call.args[0].supervisorAdminId,"17");assert.equal(call.stored[0].commandKey,call.args[1]);assert.equal(call.stored[0].intent.payload.reason,why);assert.equal(h.calls.some(c=>["supervisors","qualifications","candidates"].includes(c.name)),false);assert.equal(h.store.list().length,1);h.unmount();
});
test("PERSONAL and explicit M1 menu denial perform zero reads or writes",async()=>{
  const personal=harness({props:{mode:"PERSONAL"}});await personal.flush();assert.equal(personal.calls.length,0);personal.unmount();
  const denied=harness();const deniedAuth={...denied.auth,session:{...denied.auth.session,menuCodes:[]}};denied.unmount();const h=harness({auth:deniedAuth});await h.flush();assert.equal(h.calls.length,0);assert.match(text(h.tree),/不能管理客服组/);h.unmount();
});
test("anonymous/lost session renders denial without dereferencing absent command evidence",async()=>{for(const isQualification of [false,true]){const h=harness({qualification:isQualification,auth:{session:null,isAuthenticated:false,authEpoch:1,logoutPending:false,logoutUnknown:false}});await h.flush();assert.equal(h.calls.length,0);assert.match(text(h.tree),isQualification?/仅总管理员/:/不能管理客服组/);h.unmount();}});
test("group directory and selected member main lists are mutually exclusive, back preserves parent callback",async()=>{
  const h=harness({implementations:{groups:()=>[group()],detail:()=>detail("5",[rawMember]),member:()=>member()}});await h.flush();assert.equal(all(h.tree,n=>n.type==="table").length,1);h.click("管理成员与组资料");await h.flush();assert.equal(all(h.tree,n=>n.type==="table").length,1);assert.match(text(h.tree),/专属客服21/);h.click("返回统计工作台");assert.equal(h.backs,1);h.unmount();
});
test("super candidates can visit later server pages; MANAGED candidates always carry an owned groupId",async()=>{
  for(const mode of ["ALL","MANAGED"]){const h=harness({props:{mode,initialGroupId:"5"},implementations:{groups:()=>[group()],detail:()=>detail(),candidates:q=>({records:[{adminId:"21",name:"客服甲"}],total:41,pageNum:q.pageNum,pageSize:20})}});await h.flush();h.click("加入或调入成员");await h.flush();h.click("下一页成员");await h.flush();const calls=h.calls.filter(c=>c.name==="candidates");assert.equal(calls.at(-1).args[0].pageNum,2);assert.equal(calls.at(-1).args[0].groupId,mode==="MANAGED"?"5":undefined);if(mode==="MANAGED")assert.equal(h.calls.some(c=>c.name==="supervisors"),false);h.unmount();}
});
test("move loads latest member/source/target independently, not profile/list version; existing bindings stay personal",async()=>{
  const h=harness({props:{mode:"MANAGED",initialGroupId:"5"},implementations:{groups:()=>[group(),group("6")],detail:id=>({...detail(id,id==="5"?[rawMember]:[]),group:group(id,"17",id==="5"?9:12)}),member:id=>({...member(id),currentMember:{...member(id).currentMember,version:11}}),moveSupportGroupMember:()=>({})}});await h.flush();h.click("调组");h.reason();assert.equal(h.button("确认并提交").props.disabled,true);const target=h.selects().at(-1);target.props.onChange("6");h.commit();await h.flush();h.click("确认并提交");await h.flush();const call=h.calls.find(c=>c.name==="moveSupportGroupMember");assert.deepEqual({...call.args[1]},{targetGroupId:"6",expectedMemberVersion:11,sourceGroupVersion:9,targetGroupVersion:12,reason:why});assert.equal(h.changes,1);assert.equal(h.store.list().length,0);h.unmount();
});
test("ALL unassignment cannot submit before source/member re-preview; MANAGED cannot choose unassigned target",async()=>{
  const h=harness({props:{mode:"ALL",initialGroupId:"5"},implementations:{groups:()=>[group()],detail:()=>detail("5",[rawMember]),member:()=>member(),moveSupportGroupMember:()=>({})}});await h.flush();h.click("调组");h.reason();assert.equal(h.button("确认并提交").props.disabled,true);h.click("重读预览");await h.flush();h.click("确认并提交");await h.flush();assert.equal(h.calls.find(c=>c.name==="moveSupportGroupMember").args[1].sourceGroupVersion,3);assert.equal(h.calls.find(c=>c.name==="moveSupportGroupMember").args[1].targetGroupId,null);h.unmount();
  const managed=harness({props:{initialGroupId:"5"},implementations:{groups:()=>[group()],detail:()=>detail("5",[rawMember]),member:()=>member()}});await managed.flush();managed.click("调组");assert.equal(managed.selects().at(-1).props.options.some(o=>o.value===""),false);managed.unmount();
});
test("quota-before-dispatch stops CREATE and preserves original record in memory",async()=>{const persisted=storage(),h=harness({storage:persisted});await createDraft(h);persisted.quota=true;h.click("确认并提交");await h.flush();assert.equal(h.calls.some(c=>c.name==="createSupportGroup"),false);assert.equal(h.store.list().length,1);assert.match(text(h.tree),/未能持久保存/);h.unmount();});
test("unknown retry and refresh reuse exact CREATE key/body/reason; status UNKNOWN or 404 cannot release it",async()=>{
  const persisted=storage(), h=harness({storage:persisted,implementations:{createSupportGroup:()=>{throw new Error("timeout");},command:()=>({status:"UNKNOWN"})}});await createDraft(h);const staleConfirm=h.button("确认并提交").props.onClick;h.click("确认并提交");await h.flush();const original=h.calls.find(c=>c.name==="createSupportGroup");staleConfirm();h.commit();await h.flush();assert.equal(h.calls.filter(c=>c.name==="createSupportGroup").length,1);assert.doesNotMatch(text(h.tree),/使用原资料与命令重试/);const retried=h.calls.filter(c=>c.name==="createSupportGroup").at(-1);assert.equal(retried.args[1],original.args[1]);assert.deepEqual(retried.args[0],original.args[0]);assert.deepEqual(h.store.list()[0].intent.payload,original.args[0]);h.click("查询原操作");await h.flush();assert.equal(h.store.list().length,1);h.unmount();
  const reloaded=harness({storage:persisted,implementations:{command:()=>Promise.reject({status:404})}});await reloaded.flush();assert.equal(reloaded.store.list()[0].intent.payload.reason,why);assert.doesNotMatch(text(reloaded.tree),new RegExp(why));reloaded.click("查询原操作");await reloaded.flush();assert.equal(reloaded.store.list()[0].commandKey,original.args[1]);assert.equal(reloaded.button("创建组").props.disabled,true);reloaded.unmount();
});
test("expired CREATE remains across reload, explains manual verification and blocks both replay and new create",async()=>{
  const persisted=storage(),module=makeClient({},persisted);module.groupPendingCommands.remember("group-management:17",key,{actorId:17,label:"创建客服组",intent:{kind:"CREATE",payload:{name:"过期待定组",supervisorAdminId:"17",reason:why}}});const record=module.groupPendingCommands.list()[0];class Later extends Date{static now(){return record.createdAt+25*60*60*1000;}}
  const h=harness({storage:persisted,clock:Later});await h.flush();assert.match(text(h.tree),/原操作超过回查保护期/);assert.match(text(h.tree),/核对是否已创建/);assert.equal(h.button("创建组").props.disabled,true);assert.doesNotMatch(text(h.tree),/使用原资料与命令重试/);h.click("查询原操作");await h.flush();assert.equal(h.store.list()[0].commandKey,key);assert.equal(h.calls.some(c=>c.name==="createSupportGroup"),false);h.unmount();
});
test("success receipt needs authorized facts readback: 403 retains pending, subsequent confirmed read releases it",async()=>{
  let denied=false;const h=harness({implementations:{groups:()=>denied?Promise.reject({status:403}):[],createSupportGroup:()=>{denied=true;return group();},command:()=>({status:"SUCCEEDED"})}});await createDraft(h);h.click("确认并提交");await h.flush();assert.equal(h.store.list().length,1);assert.equal(h.changes,0);denied=false;h.click("查询原操作");await h.flush();assert.equal(h.store.list().length,0);assert.equal(h.changes,1);h.unmount();
});
test("409 keeps original key/payload/reason; FAILED plus authorized GET still requires manual fresh preview",async()=>{
  const h=harness({props:{initialGroupId:"5"},implementations:{groups:()=>[group()],detail:()=>detail(),renameSupportGroup:()=>Promise.reject({status:409,apiCode:409}),command:()=>({status:"FAILED"})}});await h.flush();h.click("重命名");h.input("新的组名");h.reason();h.click("确认并提交");await h.flush();assert.equal(h.calls.filter(c=>c.name==="renameSupportGroup").length,1);assert.equal(h.store.list().length,1);assert.equal(h.store.list()[0].intent.payload.expectedVersion,3);assert.equal(h.store.list()[0].intent.payload.reason,why);h.click("查询原操作");await h.flush();assert.equal(h.store.list().length,0);assert.equal(h.button("确认并提交").props.disabled,true);assert.match(text(h.tree),/理由已保留/);assert.equal(h.modal().props.children.flat(Infinity).find(n=>n?.type==="label"&&text(n).includes("操作理由")).props.children[1].props.value,why);h.unmount();
});
test("identity switch hides old directory/draft before effects and ignores an old pending response",async()=>{
  const late=deferred();let reads=0;const h=harness({implementations:{groups:()=>++reads===1?[group()]:late.promise}});await h.flush();h.click("创建组");h.input("敏感原组名");const pre=h.changeAuth({authEpoch:2,session:{...h.auth.session,adminId:18}},true);assert.doesNotMatch(text(pre),/第一组5|敏感原组名/);h.commit();await h.flush();late.resolve([group("6","18")]);await h.flush();assert.match(text(h.tree),/第一组6/);assert.doesNotMatch(text(h.tree),/第一组5/);h.unmount();
});
test("revocation clears readable names/draft and late unabortable reads cannot return",async()=>{
  const late=deferred();const h=harness({props:{initialGroupId:"5"},implementations:{groups:()=>[group()],detail:()=>late.promise}});await h.flush();h.changeAuth({session:{...h.auth.session,authorities:[]}});late.resolve(detail());await h.flush();assert.doesNotMatch(text(h.tree),/第一组5/);assert.equal(h.modal(),undefined);h.unmount();
});
test("late acknowledged CREATE after identity changes issues no old follow-up GET and never forgets evidence",async()=>{const late=deferred(),h=harness({implementations:{createSupportGroup:()=>late.promise}});await createDraft(h);h.click("确认并提交");await h.flush();const writes=h.calls.filter(c=>c.name==="createSupportGroup");assert.equal(writes.length,1);h.changeAuth({authEpoch:2,session:{...h.auth.session,adminId:18}});await h.flush();const reads=h.calls.filter(c=>c.name==="groups").length;late.resolve(group());await h.flush();assert.equal(h.calls.filter(c=>c.name==="groups").length,reads);assert.equal(h.changes,0);assert.equal(h.store.list()[0].actorId,17);assert.doesNotMatch(text(h.tree),new RegExp(why));h.unmount();});
test("late member preview after identity change cannot fetch old source/target detail",async()=>{const late=deferred();let calls=0;const h=harness({props:{initialGroupId:"5"},implementations:{groups:()=>[group()],detail:()=>detail("5",[rawMember]),member:()=>++calls===1?member():late.promise}});await h.flush();h.click("调组");h.click("重读预览");await h.flush();h.changeAuth({authEpoch:2,session:{...h.auth.session,adminId:18}});await h.flush();const reads=h.calls.filter(c=>c.name==="detail").length;late.resolve(member());await h.flush();assert.equal(h.calls.filter(c=>c.name==="detail").length,reads);h.unmount();});
test("qualification uses latest account.version string and independent selected kind with ABSENT zero",async()=>{
  let q=qualification();const h=harness({qualification:true,props:{kind:"SUPERVISOR"},implementations:{qualifications:()=>q,setSupportQualification:()=>{q=qualification("21","AVAILABLE","14");return [];}}});await h.flush();h.reason();h.click("确认并提交");await h.flush();const call=h.calls.find(c=>c.name==="setSupportQualification");assert.deepEqual({...call.args[1]},{qualificationKind:"SUPERVISOR",state:"ENABLED",expectedQualificationVersion:0,expectedAccountVersion:13,reason:why});assert.equal(call.stored[0].intent.payload.qualificationKind,"SUPERVISOR");assert.equal(h.store.list().length,0);assert.equal(h.changes,1);h.unmount();
});
test("UNKNOWN qualification and non-super / missing actual A1 rights cannot write or read",async()=>{
  const h=harness({qualification:true,implementations:{qualifications:()=>qualification("21","UNKNOWN")}});await h.flush();h.reason();assert.equal(h.button("确认并提交").props.disabled,true);assert.equal(h.calls.some(c=>c.name==="setSupportQualification"),false);h.unmount();
  for(const alter of [s=>({...s,role:"SUPERVISOR"}),s=>({...s,authorities:s.authorities.filter(a=>a!=="platform_a1_write")}),s=>({...s,menuCodes:["M1"]})]){const template=h.auth;const denied=harness({qualification:true,auth:{...template,session:alter(template.session)}});await denied.flush();assert.equal(denied.calls.length,0);assert.equal(denied.button("确认并提交").props.disabled,true);denied.unmount();}
});
test("qualification 409 requires explicit GET before confirm while preserving reason; no auto version change",async()=>{
  const h=harness({qualification:true,implementations:{qualifications:()=>qualification(),setSupportQualification:()=>Promise.reject({status:409,apiCode:409}),command:()=>({status:"FAILED"})}});await h.flush();h.reason();const staleConfirm=h.button("确认并提交").props.onClick;h.click("确认并提交");await h.flush();assert.equal(h.calls.filter(c=>c.name==="qualifications").length,1);assert.equal(h.store.list().length,1);staleConfirm();h.commit();await h.flush();assert.equal(h.store.list()[0].intent.payload.expectedAccountVersion,13);assert.equal(h.calls.filter(c=>c.name==="setSupportQualification").length,1);h.click("查询原操作");await h.flush();assert.equal(h.store.list().length,0);assert.equal(h.button("确认并提交").props.disabled,true);assert.match(text(h.tree),/理由已保留/);h.click("重读当前资格");await h.flush();assert.equal(h.button("确认并提交").props.disabled,false);h.unmount();
});
test("qualification unknown write key survives refresh; FAILED/SUCCEEDED receipt still requires readable facts",async()=>{
  const persisted=storage(),h=harness({qualification:true,storage:persisted,implementations:{setSupportQualification:()=>Promise.reject(new Error("network"))}});await h.flush();h.reason();h.click("确认并提交");await h.flush();const original=h.store.list()[0];h.unmount();let deny=true;const next=harness({qualification:true,storage:persisted,implementations:{qualifications:()=>deny?Promise.reject({status:403}):qualification(),command:()=>({status:"FAILED"})}});await next.flush();next.click("查询原操作");await next.flush();assert.equal(next.store.list()[0].commandKey,original.commandKey);deny=false;next.click("查询原操作");await next.flush();assert.equal(next.store.list().length,0);assert.equal(next.changes,1);next.unmount();
});
test("late qualification write cannot read old target or finish under a different account/kind",async()=>{const late=deferred(),h=harness({qualification:true,implementations:{setSupportQualification:()=>late.promise}});await h.flush();h.reason();h.click("确认并提交");await h.flush();h.props.adminId="22";h.props.kind="SUPERVISOR";h.commit();await h.flush();const reads=h.calls.filter(c=>c.name==="qualifications").length;late.resolve([]);await h.flush();assert.equal(h.calls.filter(c=>c.name==="qualifications").length,reads);assert.equal(h.changes,0);assert.equal(h.store.list()[0].intent.targetId,"21");h.unmount();});
