import test from "node:test";
import assert from "node:assert/strict";
import {harness,makeClient,storage,group,detail,member,qualification,text,why,all} from "./helpers.mjs";
const recordFor=intent=>({actorId:17,label:"旧授权秘密名称",intent});
const saved=persisted=>makeClient({},persisted).groupPendingCommands;
const fingerprint="group-management:17",key="original-private-target-key",secret="旧授权私有原因不可展示";
test("all saved group write families remain generic despite successful unrelated owned-group directory",async()=>{
  for(const intent of [{kind:"CREATE",payload:{name:"旧授权秘密名称",supervisorAdminId:"987654321",reason:secret}},{kind:"RENAME",targetId:"987654321",payload:{name:"旧授权秘密名称",expectedVersion:3,reason:secret}},{kind:"STATUS",targetId:"987654321",payload:{status:"DISABLED",expectedVersion:3,reason:secret}},{kind:"OWNER",targetId:"987654321",payload:{supervisorAdminId:"987654322",expectedVersion:3,reason:secret}},{kind:"MEMBER",targetId:"987654321",payload:{targetGroupId:"987654322",expectedMemberVersion:7,sourceGroupVersion:3,targetGroupVersion:4,reason:secret}}]){
    const persisted=storage();saved(persisted).remember(fingerprint,key,recordFor(intent));const h=harness({storage:persisted,implementations:{groups:()=>[group("6","17")]}});await h.flush();const before=structuredClone(h.store.list());assert.match(text(h.tree),/第一组6/);assert.doesNotMatch(JSON.stringify(h.tree),/旧授权秘密名称|旧授权私有原因不可展示|987654321|987654322/);assert.equal(h.modal(),undefined);assert.equal(h.calls.some(c=>["member","detail","supervisors","candidates"].includes(c.name)),false);h.click("查询原操作");await h.flush();assert.deepEqual(structuredClone(h.store.list()),before);assert.equal(h.calls.filter(c=>c.name==="command")[0].args[0],key);h.unmount();
  }
});
test("in-memory RENAME draft disappears as soon as it becomes pending and never resurfaces when old group transfers",async()=>{
  let transferred=false;const h=harness({props:{initialGroupId:"5"},implementations:{groups:()=>transferred?[group("6")]:[group(),group("6")],detail:id=>transferred&&id==="5"?Promise.reject({status:403}):detail(id),renameSupportGroup:()=>Promise.reject(new Error("receipt lost"))}});await h.flush();h.click("重命名");h.input("旧授权秘密名称");h.reason(secret);h.click("确认并提交");assert.equal(h.modal(),undefined);assert.doesNotMatch(JSON.stringify(h.tree),/旧授权秘密名称|旧授权私有原因不可展示/);await h.flush();const original=structuredClone(h.store.list()[0]);transferred=true;h.click("刷新资料");await h.flush();assert.match(text(h.tree),/第一组6/);assert.doesNotMatch(JSON.stringify(h.tree),/第一组5|旧授权秘密名称|旧授权私有原因不可展示/);assert.equal(h.modal(),undefined);assert.deepEqual(structuredClone(h.store.list()[0]),original);h.unmount();
});
test("terminal RENAME receipt cannot restore old private draft when latest directory no longer authorizes its group",async()=>{
  const persisted=storage();saved(persisted).remember(fingerprint,key,recordFor({kind:"RENAME",targetId:"5",payload:{name:"旧授权秘密名称",expectedVersion:3,reason:secret}}));const h=harness({storage:persisted,implementations:{groups:()=>[group("6")],detail:()=>({...detail(),group:{...group(),name:"旧授权秘密名称"}}),command:()=>({status:"FAILED"})}});await h.flush();const original=structuredClone(h.store.list()[0]);h.click("查询原操作");await h.flush();assert.deepEqual(structuredClone(h.store.list()[0]),original);assert.equal(h.modal(),undefined);assert.doesNotMatch(JSON.stringify(h.tree),/旧授权秘密名称|旧授权私有原因不可展示/);assert.equal(h.changes,0);h.unmount();
});
test("MEMBER recovery hides moved source and lost target directions, even with current M1 scope still enabled",async()=>{
  for(const [currentGroupId,targetGroupId] of [["5","6"],["6","5"]]){const persisted=storage();saved(persisted).remember(fingerprint,key,recordFor({kind:"MEMBER",targetId:"987654321",payload:{targetGroupId,expectedMemberVersion:7,sourceGroupVersion:3,targetGroupVersion:4,reason:secret}}));const h=harness({storage:persisted,implementations:{groups:()=>[group("6")],member:id=>({...member(id,currentGroupId),name:"旧授权秘密成员"}),command:()=>({status:"FAILED"})}});await h.flush();assert.equal(h.calls.some(c=>["detail","member"].includes(c.name)),false);const original=structuredClone(h.store.list()[0]);h.click("查询原操作");await h.flush();assert.deepEqual(structuredClone(h.store.list()[0]),original);assert.doesNotMatch(JSON.stringify(h.tree),/旧授权秘密成员|旧授权秘密名称|旧授权私有原因不可展示|987654321/);assert.equal(h.modal(),undefined);assert.equal(h.changes,0);assert.equal(h.calls.filter(c=>c.name==="member").length,1);assert.equal(h.calls.filter(c=>c.name==="detail").length,0);h.unmount();}
});
test("qualification pending masks account/state/textarea/title until terminal receipt and authoritative readback",async()=>{
  const persisted=storage();saved(persisted).remember("support-qualification:17:21:SERVICE",key,recordFor({kind:"QUALIFICATION",targetId:"21",payload:{qualificationKind:"SERVICE",state:"ENABLED",expectedQualificationVersion:0,expectedAccountVersion:13,reason:secret}}));let reads=0;const h=harness({qualification:true,storage:persisted,implementations:{qualifications:()=>({...qualification(),name:++reads===1?"最新但仍隐藏的账号名":"当前授权账号新名称"}),command:()=>({status:"FAILED"})}});await h.flush();assert.equal(h.modal().props.title,"查询原操作");assert.doesNotMatch(JSON.stringify(h.tree),/旧授权秘密名称|旧授权私有原因不可展示|最新但仍隐藏的账号名/);assert.equal(all(h.tree,n=>n.type==="textarea").length,0);assert.equal(h.selects().length,0);const original=structuredClone(h.store.list()[0]);h.click("查询原操作");await h.flush();assert.equal(h.store.list().length,0);assert.equal(h.changes,1);assert.match(text(h.tree),/当前授权账号新名称/);assert.equal(all(h.tree,n=>n.type==="textarea")[0].props.value,original.intent.payload.reason);assert.equal(reads,2);h.unmount();
});
