import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
import {before,after,test} from 'node:test';
const root=path.resolve(import.meta.dirname,'..');
const runtimeRoot=process.env.NEXION_PC_RUNTIME_ROOT||root;
const req=createRequire(path.join(runtimeRoot,'package.json'));
const ts=req('typescript'),{chromium}=req('@playwright/test');
function compile(source,fileName='fixture.tsx'){const r=ts.transpileModule(source,{fileName,compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX},reportDiagnostics:true});assert.equal(r.diagnostics?.length??0,0);return r.outputText;}
function source(rel){return fs.readFileSync(path.join(root,rel),'utf8');}
function installed(name,file){return fs.readFileSync(path.join(path.dirname(req.resolve(name)),'cjs',file),'utf8');}
const originalTest=source('tests/l4-live-data-contract.test.mjs');
const ast=ts.createSourceFile('fixture.mjs',originalTest,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS);let fixtureExpression;
function findFixture(n){if(!fixtureExpression&&ts.isCallExpression(n)&&n.expression.getText(ast)==='readL4Operations')fixtureExpression=n.arguments[0].getText(ast);ts.forEachChild(n,findFixture);}findFixture(ast);assert(fixtureExpression);
const viewAst=ts.createSourceFile('l-view.tsx',source('app/components/domain-views/l-view.tsx'),ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);let reloadExpression;
function findReload(n){if(ts.isVariableDeclaration(n)&&n.name.getText(viewAst)==='reloadBi')reloadExpression=n.initializer.getText(viewAst);ts.forEachChild(n,findReload);}findReload(viewAst);assert(reloadExpression);
const modules={react:installed('react','react.production.js'),'react/jsx-runtime':installed('react/jsx-runtime','react-jsx-runtime.production.js'),'react-dom':installed('react-dom','react-dom.production.js'),'react-dom/client':installed('react-dom/client','react-dom-client.production.js'),scheduler:installed('scheduler','scheduler.production.js'),
 '@/app/components/kit/tab-group':compile(source('app/components/kit/tab-group.tsx')),'./tab-group-keyboard':compile(source('app/components/kit/tab-group-keyboard.ts')),
 '@/app/components/kit/gloss':'exports.AutoGloss=({children})=>children;',
 '@/lib/admin/error-messages':'exports.displayAdminError=e=>String(e?.message||e);',
 '@/lib/admin/l-client':'exports.fetchL5ExportTasks=(...args)=>window.fixtureTasksRead(...args);exports.fetchL5RegulatoryOptions=async()=>({templates:[],disclosures:[]});exports.fetchL5ExportAudits=async()=>[];',
 '@/lib/admin/d-client':'exports.downloadD4BillsCsv=()=>{window.trace.financial++;throw Error("Forbidden financial fixture action");};',
 './live-data':compile(source('app/components/domain-views/l-tabs/live-data.tsx')),'./l4-live-data':compile(source('app/components/domain-views/l-tabs/l4-live-data.ts')),'./l5-pagination':compile(source('app/components/domain-views/l-tabs/l5-pagination.ts')),'./l5-kpi-range':compile(source('app/components/domain-views/l-tabs/l5-kpi-range.ts')),
 './l4-source':compile(source('app/components/domain-views/l-tabs/l4-ops.tsx')),'./l5-source':compile(source('app/components/domain-views/l-tabs/l5-export.tsx'))};
const entry=compile(`
const React=require('react'),{createRoot}=require('react-dom/client');
const {useCallback,useEffect,useRef,useState}=React;
const {readL4Operations}=require('./l4-live-data'),{L4Ops,L4HeaderActions}=require('./l4-source'),{L5Export}=require('./l5-source');
const displayAdminError=e=>String(e?.message||e),formatAdminApiError=s=>s;const fixture=${fixtureExpression};
window.trace={exports:[],reads:[],taskReads:[],toasts:[],downloads:0,financial:0};let host=createRoot(document.getElementById('root')),generation=0,version=0;
const sample=(query)=>({...fixture,period:{key:query.period,label:query.period==='day'?'近1天':query.period==='month'?'近30天':query.period==='custom'?'自定义':'近7天',from:query.from||'2026-10-02',to:query.to||'2026-10-09'},phaseFilter:query.phase});
const fetchLBiOverview=async(tab,l3,query)=>{window.trace.reads.push({...query});if(query.period==='custom'&&query.from==='2024-01-01')throw Error('L4_CUSTOM_RANGE_INVALID');return {l4:sample(query)};};
function L4Host({config}){const tab='L4',session='isolated-fixture';const [l3Query]=useState({period:'month'}),[l4Query,setL4Query]=useState({period:'week',phase:'ALL'});const [biSnapshot,setBiData]=useState({l4:sample(l4Query)}),[biOwner,setBiOwner]=useState(session),[biLoading,setBiLoading]=useState(false),[biError,setBiError]=useState(null);const currentOwner=useRef(session),readGeneration=useRef(0);const reloadBi=${reloadExpression};
 useEffect(()=>{void reloadBi();return()=>{readGeneration.current++;};},[reloadBi]);useEffect(()=>{window.fixtureRendered=config.version;},[config.version]);
 const ctx={biData:biOwner===session?biSnapshot:null,biLoading,biError,reloadBi,l4Query,setL4Query,canExport:!config.readonly,toast:x=>window.trace.toasts.push(x),biActions:{createReport:async(input,reason,key)=>{window.trace.exports.push({input,reason,key});if(config.exportFailure)throw Error('isolated uncertain receipt');}}};
 return React.createElement(React.Fragment,null,React.createElement(L4HeaderActions,{ctx}),React.createElement(L4Ops,{ctx}));}
const readyTask=(id='SOURCE-READY-1')=>({id,type:'运营报表',reportType:'OPERATIONS_AGG',scope:'week/ALL',fields:'聚合',pii:false,mask:'—',rows:12,st:'READY',chain:'snapshot',supported:true,snapshotAvailable:true,acts:['download']});
window.taskPage=(ids=['SOURCE-READY-1'],page=1,total=ids.length)=>({page,pageSize:8,total,records:ids.map(id=>readyTask(id))});
window.pendingTaskReads=[];window.fixtureTasksRead=(status,page,size)=>{window.trace.taskReads.push({status,page,size});return new Promise((resolve,reject)=>window.pendingTaskReads.push({status,page,resolve,reject}));};
function L5Host({config}){useEffect(()=>{window.fixtureRendered=config.version;},[config.version]);const ctx={biData:config.noData?null:config.data,biLoading:!!config.loading,biError:config.error||null,toast:x=>window.trace.toasts.push(x),canAccessReportType:()=>!config.readonly,biActions:{downloadReport:()=>{window.trace.downloads++;throw Error('Forbidden download fixture action');}},openActionConfirm:()=>{throw Error('Unexpected fixture confirmation');}};return React.createElement(L5Export,{ctx});}
window.mount=(kind,config={},remount=true)=>{if(remount)generation++;config.version=++version;if(kind==='L5')config.data=config.data||{l5:{summary:{totalReports:12,readyReports:1},exportTasks:[readyTask()]}};host.render(React.createElement(kind==='L4'?L4Host:L5Host,{key:generation,config}));return config.version;};
window.resolveTask=(index,page)=>window.pendingTaskReads[index].resolve(page);window.rejectTask=(index)=>window.pendingTaskReads[index].reject(Error('isolated filtered read failure'));
`);
const bundle=`(()=>{const factories={${Object.entries(modules).map(([id,code])=>`${JSON.stringify(id)}:function(require,module,exports){\n${code}\n}`).join(',')}};const cache={};function require(id){if(cache[id])return cache[id].exports;if(!factories[id])throw Error('Unbundled '+id);const m=cache[id]={exports:{}};factories[id](require,m,m.exports);return m.exports;}\n${entry}\n})();`;
let browser,page;const errors=[],network=[];
before(async()=>{browser=await chromium.launch({headless:true});page=await browser.newPage();page.setDefaultTimeout(2500);await page.route('**/*',r=>{network.push(r.request().url());return r.abort();});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.setContent('<!doctype html><div id="root"></div>');await page.addScriptTag({content:bundle});});
after(async()=>{const trace=await page?.evaluate(()=>({downloads:window.trace.downloads,financial:window.trace.financial}));await browser?.close();assert.deepEqual(errors,[]);assert.deepEqual(network,[]);assert.equal(trace.downloads,0);assert.equal(trace.financial,0);});
async function mount(kind,config={},remount=true){const v=await page.evaluate(({kind,config,remount})=>window.mount(kind,config,remount),{kind,config,remount});await page.waitForFunction(v=>window.fixtureRendered===v,v);}
async function pendingCount(n){await page.waitForFunction(n=>window.pendingTaskReads.length>=n,n);}
const exportButton=()=>page.getByRole('button',{name:'导出运营报表 CSV',exact:true});
const taskSection=()=>page.locator('section').filter({has:page.locator('.ttl').filter({hasText:/^导出任务管理$/})});
test('unapplied custom draft retains report while blocking export',async()=>{await mount('L4');await page.getByRole('tab',{name:'自定义',exact:true}).click();await page.getByLabel('自定义开始日期').waitFor();assert.equal(await exportButton().isDisabled(),true);assert.match(await page.locator('#root').textContent(),/近7天/);assert.equal(await page.evaluate(()=>window.trace.exports.length),0);});
test('rejected custom dates remain editable and recover through a valid period',async()=>{await mount('L4');await page.getByRole('tab',{name:'自定义',exact:true}).click();await page.getByLabel('自定义开始日期').fill('2024-01-01');await page.getByLabel('自定义结束日期').fill('2026-10-01');await page.getByRole('button',{name:'应用自定义周期',exact:true}).click();await page.getByText(/L4 数据加载失败/).waitFor();assert.equal(await page.getByLabel('自定义开始日期').count(),1);assert.equal(await page.getByLabel('自定义开始日期').inputValue(),'2024-01-01');await page.getByLabel('自定义开始日期').fill('2026-10-03');await page.getByLabel('自定义结束日期').fill('2026-10-08');await page.getByRole('button',{name:'应用自定义周期',exact:true}).click();await page.waitForFunction(()=>!document.body.textContent.includes('L4 数据加载失败'));assert.equal(await exportButton().isDisabled(),false);await page.getByRole('tab',{name:'周',exact:true}).click();await page.waitForFunction(()=>document.body.textContent.includes('近7天'));assert.equal(await exportButton().isDisabled(),false);});
test('same-payload uncertain retry keeps key, changed successful query gets a new key',async()=>{await mount('L4',{exportFailure:true});const start=await page.evaluate(()=>window.trace.exports.length);await exportButton().click();await page.waitForFunction(n=>window.trace.exports.length===n,start+1);await exportButton().click();await page.waitForFunction(n=>window.trace.exports.length===n,start+2);await page.getByRole('tab',{name:'日',exact:true}).click();await page.waitForFunction(()=>document.body.textContent.includes('近1天'));await exportButton().click();await page.waitForFunction(n=>window.trace.exports.length===n,start+3);const rows=await page.evaluate(n=>window.trace.exports.slice(n),start);assert.equal(rows[0].key,rows[1].key);assert.notEqual(rows[2].key,rows[1].key);assert.equal(rows[2].input.timeRange,'period=day;phase=ALL');});
test('new filtered read failure exposes neither old READY task nor empty success/zero count',async()=>{const start=await page.evaluate(()=>window.pendingTaskReads.length);await mount('L5');await pendingCount(start+1);await page.evaluate(i=>window.resolveTask(i,window.taskPage(['SOURCE-READY-1'],1,12)),start);await taskSection().getByText('SOURCE-READY-1',{exact:true}).waitFor();await page.getByRole('tab',{name:'待确认',exact:true}).click();await pendingCount(start+2);await page.evaluate(i=>window.rejectTask(i),start+1);await taskSection().getByText(/导出任务加载失败/).waitFor();assert.equal(await taskSection().getByText('SOURCE-READY-1',{exact:true}).count(),0);assert.equal(await taskSection().getByRole('button',{name:'下载',exact:true}).count(),0);assert.doesNotMatch(await taskSection().textContent(),/当前筛选暂无导出任务|共 0 条/);await page.getByRole('tab',{name:'全部',exact:true}).click();await pendingCount(start+3);await page.evaluate(i=>window.resolveTask(i,window.taskPage(['SOURCE-RECOVERED'],1,1)),start+2);await taskSection().getByText('SOURCE-RECOVERED',{exact:true}).waitFor();});
test('late filtered response cannot replace current query; readonly downloads stay unavailable',async()=>{const start=await page.evaluate(()=>window.pendingTaskReads.length);await mount('L5',{readonly:true});await pendingCount(start+1);await page.evaluate(i=>window.resolveTask(i,window.taskPage(['SOURCE-OLD'],1,10)),start);await taskSection().getByText('SOURCE-OLD',{exact:true}).waitFor();await page.getByRole('tab',{name:'待确认',exact:true}).click();await pendingCount(start+2);await page.getByRole('tab',{name:'已就绪（含历史）',exact:true}).click();await pendingCount(start+3);await page.evaluate(i=>window.resolveTask(i,window.taskPage(['SOURCE-CURRENT'],1,1)),start+2);await taskSection().getByText('SOURCE-CURRENT',{exact:true}).waitFor();await page.evaluate(i=>window.resolveTask(i,window.taskPage(['SOURCE-LATE'],1,1)),start+1);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));assert.equal(await taskSection().getByText('SOURCE-LATE',{exact:true}).count(),0);assert.equal(await taskSection().getByRole('button',{name:'下载',exact:true}).count(),0);});
test('shrinking total clamps and rereads without exposing overview fallback',async()=>{const start=await page.evaluate(()=>window.pendingTaskReads.length);await mount('L5');await pendingCount(start+1);await page.evaluate(i=>window.resolveTask(i,window.taskPage(['SOURCE-PAGE1'],1,12)),start);await taskSection().getByText('SOURCE-PAGE1',{exact:true}).waitFor();await taskSection().getByRole('button',{name:'下一页',exact:true}).click();await pendingCount(start+2);await page.evaluate(i=>window.resolveTask(i,window.taskPage([],2,0)),start+1);await pendingCount(start+3);assert.equal(await taskSection().getByText('SOURCE-READY-1',{exact:true}).count(),0);await page.evaluate(i=>window.resolveTask(i,window.taskPage([],1,0)),start+2);await taskSection().getByText('当前筛选暂无导出任务',{exact:true}).waitFor();assert.match(await taskSection().textContent(),/第 1 \/ 1 页 · 共 0 条/);});
test('readonly L4 and initial missing L5 data preserve existing permission/no-empty boundaries',async()=>{await mount('L4',{readonly:true});assert.equal(await exportButton().isDisabled(),true);await mount('L5',{noData:true,loading:true});await page.getByText('L5 数据加载中...', {exact:true}).waitFor();assert.equal(await taskSection().count(),0);assert.equal(await page.getByText('当前筛选暂无导出任务',{exact:true}).count(),0);});
