import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const root = process.cwd();
const read = (path) => readFileSync(resolve(root, path), "utf8");

test("M2 keeps resolution and archive as separate, reversible states", () => {
  const tickets = read("app/components/domain-views/m-tabs/m2-tickets.tsx");
  const client = read("lib/admin/m-client.ts");

  assert.match(tickets, /scope === "archived"\) return t\.archived/);
  assert.match(tickets, /scope === "resolved"\) return !t\.archived/);
  assert.match(tickets, /setArchivedDirect\(t\.id, false\)/);
  assert.match(client, /\/tickets\/\$\{encodeURIComponent\(ticketNo\)\}\/archive/);
});

test("M2 escalation is one backend command and preserves the real user binding", () => {
  const tickets = read("app/components/domain-views/m-tabs/m2-tickets.tsx");
  const view = read("app/components/domain-views/m-view.tsx");

  assert.match(tickets, /该工单未关联真实用户/);
  assert.match(tickets, /I\.support\.ticketEscalation\.__create/);
  assert.match(view, /mContentActions\.escalateTicket/);
  assert.doesNotMatch(tickets, /localStorage/);
});

test("M2 never turns a failed queue request into a writable empty state", () => {
  const tickets = read("app/components/domain-views/m-tabs/m2-tickets.tsx");
  const client = read("lib/admin/m-client.ts");

  assert.match(client, /const ticketsAvailable = results\[0\]\.status === "fulfilled"/);
  assert.match(client, /"I\.support\.ticketsAvailable": data\.ticketsAvailable \? "1" : "0"/);
  assert.match(tickets, /工单数据暂时无法同步/);
  assert.match(tickets, /!ticketsAvailable/);
});

test("M2 fails closed when any authoritative ticket detail cannot be loaded", () => {
  const client = read("lib/admin/m-client.ts");

  assert.match(client, /detailOrUnavailable/);
  assert.match(client, /ticketsAvailable = results\[0\]\.status === "fulfilled" && ticketDetails\.complete/);
  assert.match(client, /tickets: ticketDetails\.rows/);
  assert.doesNotMatch(client, /if \(!messages\.length && base\.lastMessage\)/);
});

test("M2 loads every backend page instead of silently capping the queue at 100", () => {
  const client = read("lib/admin/m-client.ts");

  assert.match(client, /async function fetchAllSupportTickets/);
  assert.match(client, /while \(records\.length < total\)/);
  assert.match(client, /pageNum=\$\{pageNum\}/);
});

test("M2 writes are permission-gated and audit reasons are generated by the flow", () => {
  const tickets = read("app/components/domain-views/m-tabs/m2-tickets.tsx");

  assert.match(tickets, /service_m2_write/);
  assert.match(tickets, /当前账号为只读模式/);
  assert.match(tickets, /客服人工新建工单并自动留档/);
  assert.doesNotMatch(tickets, /name="reason"/);
});

test("M2 exposes explicit lifecycle edges, a clear reopen action, and the escalated conversation", () => {
  const tickets = read("app/components/domain-views/m-tabs/m2-tickets.tsx");
  const sessions = read("app/components/domain-views/m-tabs/m3-sessions.tsx");

  assert.match(tickets, /const STATUS_TRANSITIONS/);
  assert.match(tickets, /resolved: \["open", "pending_user", "closed"\]/);
  assert.match(tickets, /重新打开/);
  assert.match(tickets, /查看会话 \{conversation\.no\}/);
  assert.match(tickets, /seg=archived&q=/);
  assert.match(sessions, /params\.get\("q"\)/);
  assert.match(sessions, /data-proof="session-conversation-no">\{convo\.id\}/);
});

test("M2 only offers real, enabled and transferable support agents as ticket owners", () => {
  const tickets = read("app/components/domain-views/m-tabs/m2-tickets.tsx");

  assert.match(tickets, /agent\.enabled && agent\.transferable && agent\.serviceTypes\.includes\("support"\)/);
  assert.match(tickets, /ownerOptions\.includes\(form\.owner\)/);
  assert.match(tickets, /当前负责人不在可接单客服名册/);
  assert.doesNotMatch(tickets, /const ticketOwners/);
  assert.doesNotMatch(tickets, /agentIdForName/);
});

test("M2 waits for the backend result before showing success or advancing local UI", () => {
  const tickets = read("app/components/domain-views/m-tabs/m2-tickets.tsx");
  const view = read("app/components/domain-views/m-view.tsx");
  const types = read("app/components/domain-views/m-tabs/types.ts");

  assert.match(types, /setParam: .*Promise<boolean>/);
  assert.match(view, /await applyMBackendWrite/);
  assert.match(view, /await reloadMContent/);
  assert.match(view, /return false/);
  assert.match(tickets, /const succeeded = await commitTicketWrite/);
  assert.match(tickets, /if \(succeeded\) setReplyBody\(""\)/);
  assert.match(tickets, /if \(succeeded\) setDrawerOpen\(false\)/);
});

test("M2 opens a newly-created ticket by the authoritative backend ticket number", () => {
  const tickets = read("app/components/domain-views/m-tabs/m2-tickets.tsx");

  assert.match(tickets, /pendingCreatedTicket/);
  assert.match(tickets, /useState<PendingCreatedTicket \| null>\(null\)/);
  assert.match(tickets, /ticket\.subject === pending\.subject/);
  assert.match(tickets, /!pending\.existingIds\.includes\(ticket\.id\)/);
  assert.match(tickets, /existingIds: tickets\.map\(\(ticket\) => ticket\.id\)/);
  assert.match(tickets, /setSelectedId\(authoritative\.id\)/);
  assert.doesNotMatch(tickets, /setSelectedId\(row\.id\)/);
  assert.doesNotMatch(tickets, /useRef<PendingCreatedTicket \| null>/);
});
