/** 域 A 平台基础 — 注册表(archetype 模板示例)。accent=--admin-domain-a。 */
import type { ModuleEntry } from "@/lib/admin/module-content";

export const DOMAIN_A: ModuleEntry[] = [
  {
    path: "/platform/rbac",
    summary: "运营账号与角色→权限矩阵。账号停用 / 改角色 / 重置 2FA 均需 Maker-Checker 双签并写入 A2 审计。",
    content: {
      kind: "list",
      metrics: [
        { label: "运营账号", value: "12", sub: "在线 4", accent: "var(--admin-domain-a)", hint: "已开通后台账号总数。" },
        { label: "高权限账号", value: "3", sub: "总管理员 / 风控主管", accent: "var(--v5-warning)", hint: "可执行 kill / 大额放行 / 参数批改的账号。" },
        { label: "2FA 覆盖", value: "100%", sub: "强制开启", accent: "var(--v5-success)" },
        { label: "待停用", value: "1", sub: "离职流程", accent: "var(--v5-warning)" },
      ],
      search: "搜索账号 / 角色",
      filterKey: "role",
      filters: ["全部", "总管理员", "财务", "风控", "增长运营", "客服", "审计", "内容运营"],
      columns: [
        { key: "acct", header: "账号", mono: true },
        { key: "name", header: "姓名" },
        { key: "role", header: "角色" },
        { key: "state", header: "状态", status: true },
        { key: "twofa", header: "2FA" },
        { key: "last", header: "最近登录", mono: true, align: "right" },
      ],
      rows: [
        { acct: "ops.admin", name: "总管理员", role: "总管理员", state: "启用", twofa: "已开", last: "2 分钟前" },
        { acct: "fin.lee", name: "李财务", role: "财务", state: "启用", twofa: "已开", last: "11 分钟前" },
        { acct: "risk.zhou", name: "周风控", role: "风控", state: "启用", twofa: "已开", last: "刚刚" },
        { acct: "growth.wu", name: "吴增长", role: "增长运营", state: "启用", twofa: "已开", last: "1 小时前" },
        { acct: "support.qin", name: "秦客服", role: "客服", state: "启用", twofa: "已开", last: "23 分钟前" },
        { acct: "audit.he", name: "何审计", role: "审计", state: "启用", twofa: "已开", last: "今日 09:12" },
        { acct: "content.lin", name: "林内容", role: "内容运营", state: "启用", twofa: "已开", last: "昨日 18:40" },
        { acct: "fin.old", name: "张(离职)", role: "财务", state: "待停用", twofa: "已开", last: "3 天前" },
      ],
      detail: true,
      primaryAction: { label: "新增账号", fields: ["账号", "姓名", "角色"] },
      rowActions: [
        { label: "停用账号", tone: "danger", whenStatus: "启用" },
        { label: "启用", tone: "primary", whenStatus: "待停用" },
        { label: "重置 2FA" },
        { label: "改角色" },
      ],
      note: "角色→权限矩阵由 A1 维护;改角色 / 停用账号 / 重置 2FA 需 Maker-Checker 双签 + A2 留痕,发起人不可自审。",
    },
  },
  {
    path: "/platform/audit",
    summary: "全平台敏感操作审计流水 + Maker-Checker 复核台。所有资金 / 参数 / 风控动作 server 端不可篡改留痕。",
    content: {
      kind: "list",
      metrics: [
        { label: "今日审计", value: "86", sub: "全域", accent: "var(--admin-domain-a)", hint: "今日写入审计的操作条数。" },
        { label: "待我复核", value: "5", sub: "Maker-Checker", accent: "var(--v5-warning)", hint: "等待第二人签核的高敏操作。" },
        { label: "双签通过率", value: "100%", sub: "近 30 日", accent: "var(--v5-success)" },
        { label: "高敏操作", value: "12", sub: "kill / 大额 / impersonate", accent: "var(--v5-danger)" },
      ],
      search: "搜索操作员 / 对象",
      filterKey: "result",
      filters: ["全部", "已通过", "待复核", "已拒绝"],
      columns: [
        { key: "ts", header: "时间", mono: true },
        { key: "actor", header: "操作员" },
        { key: "action", header: "动作" },
        { key: "obj", header: "对象", mono: true },
        { key: "domain", header: "域" },
        { key: "result", header: "复核", status: true },
      ],
      rows: [
        { ts: "14:02:11", actor: "risk.zhou", action: "提现放行", obj: "WD-2606-0142", domain: "D", result: "待复核" },
        { ts: "13:48:30", actor: "fin.lee", action: "提现日限上调", obj: "param:wd_daily_cap", domain: "D", result: "待复核" },
        { ts: "13:20:05", actor: "ops.admin", action: "系统配置变更", obj: "feature:exchange", domain: "A", result: "已通过" },
        { ts: "12:55:41", actor: "risk.zhou", action: "账户冻结", obj: "U-88421", domain: "C", result: "已通过" },
        { ts: "12:30:18", actor: "fin.lee", action: "余额调整", obj: "U-77310 +$120", domain: "C", result: "待复核" },
        { ts: "11:58:02", actor: "ops.admin", action: "Kill-Switch 演练", obj: "gate:exchange", domain: "J", result: "已通过" },
        { ts: "11:10:44", actor: "growth.wu", action: "试用名额上调", obj: "param:trial_quota", domain: "H", result: "已拒绝" },
        { ts: "10:32:09", actor: "support.qin", action: "impersonate 只读", obj: "U-90233", domain: "C", result: "已通过" },
      ],
      detail: true,
      note: "审计为 append-only,server 端权威;条目不可编辑或删除。待复核项点开可双签或驳回。",
    },
  },
  {
    path: "/platform/config",
    summary: "系统级运行参数与特性开关。维护模式 / 全局限流即时全站生效;变更需 总管理员 + 审计 双签。",
    content: {
      kind: "config",
      metrics: [
        { label: "维护模式", value: "关", sub: "全站可写", accent: "var(--v5-success)" },
        { label: "全局限流", value: "1,200", sub: "rps", accent: "var(--admin-domain-a)" },
        { label: "特性开关", value: "18", sub: "开 16 / 关 2", accent: "var(--admin-domain-a)" },
        { label: "服务时区", value: "UTC", sub: "结算基准", accent: "var(--v5-ink-3)" },
      ],
      groups: [
        {
          title: "运行参数",
          note: "影响全站可用性,改动即时生效。",
          fields: [
            { label: "维护模式", value: "关闭", range: "开 / 关", effect: "开启 → 全站只读" },
            { label: "全局限流", value: "1,200 rps", range: "200–5,000", effect: "下调 → 高峰排队" },
            { label: "会话超时", value: "30 min", range: "5–120", effect: "影响运营登录态" },
            { label: "结算时区", value: "UTC", range: "UTC 固定", effect: "日切 / 分红基准" },
          ],
        },
        {
          title: "特性开关(灰度)",
          note: "按比例放量;关闭立即停用对应入口。",
          fields: [
            { label: "新用户注册", value: "开 · 100%", range: "0–100%", effect: "关 → 拉新入口归零" },
            { label: "提现通道", value: "开 · 100%", range: "0–100%", effect: "关 → 提现暂停" },
            { label: "兑换通道", value: "开 · 100%", range: "0–100%", effect: "联动 G2 风控" },
            { label: "Genesis 二级市场", value: "开 · 100%", range: "0–100%", effect: "联动 G4" },
            { label: "Trade-in", value: "灰度 · 30%", range: "0–100%", effect: "联动 E5" },
          ],
        },
        {
          title: "安全",
          fields: [
            { label: "登录失败锁定", value: "5 次 / 15 min", range: "3–10 次", effect: "防撞库" },
            { label: "运营 IP 白名单", value: "启用 · 8 段", range: "开 / 关", effect: "后台访问边界" },
            { label: "审计保留期", value: "3 年", range: "1–7 年", effect: "合规留存" },
          ],
        },
      ],
      approval: "系统级配置变更需 总管理员 + 审计 双签;维护模式 / 限流即时全站生效。",
      impact: [
        "维护模式开 → 全站只读,提现 / 兑换 / 购买暂停,Day-0 接入率清零",
        "全局限流下调 → 高峰期请求排队,影响接入顺畅度与转化",
        "关闭新用户注册 → B3 漏斗入口归零,拉新 KPI 失真",
      ],
    },
  },
  {
    path: "/platform/events",
    summary: "埋点事件结构登记中心(A4)。B 域漏斗 / KPI / L 域报表均派生自此服务端权威事件流。",
    content: {
      kind: "list",
      metrics: [
        { label: "事件类型", value: "142", sub: "已登记", accent: "var(--admin-domain-a)", hint: "纳入 schema 的事件种类。" },
        { label: "今日事件量", value: "2.4M", sub: "全端", accent: "var(--admin-domain-a)" },
        { label: "Schema 版本", value: "v3.7", sub: "与前端 PRD 对齐", accent: "var(--v5-ink-3)" },
        { label: "异常埋点", value: "0", sub: "字段缺失 / 漂移", accent: "var(--v5-success)" },
      ],
      search: "搜索事件名 / 触发点",
      filterKey: "state",
      filters: ["全部", "生效", "灰度", "草稿"],
      columns: [
        { key: "evt", header: "事件名", mono: true },
        { key: "trigger", header: "触发点" },
        { key: "fields", header: "关键字段" },
        { key: "ver", header: "版本", mono: true },
        { key: "state", header: "状态", status: true },
      ],
      rows: [
        { evt: "user_register", trigger: "注册完成", fields: "uid · channel · ts", ver: "v3.7", state: "生效" },
        { evt: "kyc_pass", trigger: "$1 验证通过", fields: "uid · method", ver: "v3.7", state: "生效" },
        { evt: "first_purchase", trigger: "首购下单", fields: "uid · sku · amount", ver: "v3.7", state: "生效" },
        { evt: "device_yield_tick", trigger: "算力产出", fields: "uid · device · usdt · nex", ver: "v3.7", state: "生效" },
        { evt: "withdraw_submit", trigger: "提现提交", fields: "uid · amount · risk", ver: "v3.7", state: "生效" },
        { evt: "repurchase", trigger: "复购下单", fields: "uid · gen · amount", ver: "v3.7", state: "生效" },
        { evt: "referral_bind", trigger: "推荐绑定", fields: "uid · upline", ver: "v3.7", state: "生效" },
        { evt: "trial_to_paid", trigger: "试用转付费", fields: "uid · offset", ver: "v3.6", state: "灰度" },
      ],
      detail: true,
      primaryAction: { label: "新增埋点事件", fields: ["事件名", "触发点", "关键字段"] },
      rowActions: [
        { label: "灰度发布", tone: "primary", whenStatus: "草稿" },
        { label: "全量生效", tone: "primary", whenStatus: "灰度" },
        { label: "停用" },
      ],
      note: "事件 schema 改版需与前端埋点同版本发布;字段漂移会被本页标红并阻断派生指标更新。",
    },
  },
];
