/** 域 C 用户与账户 — 注册表。accent=--admin-domain-c。C1 检索 & 画像为旗舰单独成页,此处补 C2–C6。 */
import type { ModuleEntry } from "@/lib/admin/module-content";

export const DOMAIN_C: ModuleEntry[] = [
  {
    path: "/users/actions",
    summary: "账户操作台(C2):对账户执行 冻结 / 解冻 / 限制 / 重置密码 / impersonate 只读。行级操作按账户当前态门控;高敏操作需 Maker-Checker 双签、发起人不可自审,全程写入 A2 审计。",
    content: {
      kind: "list",
      metrics: [
        { label: "今日操作", value: "37", sub: "全部类型", accent: "var(--admin-domain-c)", hint: "今日对账户执行的操作条数。" },
        { label: "当前冻结", value: "9", sub: "资金 / 提现冻结", accent: "var(--v5-danger)", hint: "处于冻结态、暂停出入金的账户数。" },
        { label: "待复核", value: "4", sub: "Maker-Checker", accent: "var(--v5-warning)", hint: "等待第二人签核的高敏操作。" },
        { label: "impersonate", value: "6", sub: "今日 · 只读", accent: "var(--v5-ink-3)", hint: "客服只读代入会话次数,全程录屏留痕。" },
      ],
      search: "搜索用户 ID / 昵称",
      filterKey: "acctState",
      filters: ["全部", "正常", "已冻结", "已限制"],
      columns: [
        { key: "uid", header: "用户", mono: true },
        { key: "nick", header: "昵称" },
        { key: "acctState", header: "账户态", status: true },
        { key: "risk", header: "风险分", mono: true, align: "right" },
        { key: "lastAction", header: "最近操作" },
        { key: "ts", header: "时间", mono: true, align: "right" },
      ],
      rows: [
        { uid: "U-88421", nick: "minerJoe", acctState: "已冻结", risk: "82", lastAction: "异常提现冻结(K 域命中)", ts: "14:08" },
        { uid: "U-90233", nick: "cryptoLee", acctState: "正常", risk: "21", lastAction: "impersonate 只读排障", ts: "13:52" },
        { uid: "U-77310", nick: "ggwp88", acctState: "已限制", risk: "55", lastAction: "限制兑换 · 待补 KYC", ts: "13:31" },
        { uid: "U-65120", nick: "node_amy", acctState: "正常", risk: "18", lastAction: "申诉解冻通过", ts: "12:40" },
        { uid: "U-81905", nick: "x_whale", acctState: "已冻结", risk: "88", lastAction: "多账户共设备命中", ts: "11:58" },
        { uid: "U-72488", nick: "steady_v", acctState: "已限制", risk: "47", lastAction: "限制提现 · 风险观察", ts: "11:12" },
        { uid: "U-93077", nick: "lucky7", acctState: "正常", risk: "12", lastAction: "余额复现排障", ts: "10:36" },
        { uid: "U-58642", nick: "earlybird", acctState: "正常", risk: "33", lastAction: "误判回滚解冻", ts: "09:48" },
      ],
      detail: true,
      rowActions: [
        { label: "冻结", tone: "danger", whenStatus: "正常" },
        { label: "解冻", tone: "primary", whenStatus: "已冻结" },
        { label: "限制提现", whenStatus: "正常" },
        { label: "解除限制", tone: "primary", whenStatus: "已限制" },
        { label: "重置密码" },
        { label: "impersonate 只读" },
      ],
      note: "冻结 / 解冻 / 限制为高敏操作,需 Maker-Checker 双签且发起人不可自审(总管理员免双签);impersonate 仅限只读、全程录屏并写入 A2 审计,不可代用户出入金。行级操作按账户当前态门控。",
    },
  },
  {
    path: "/users/assets",
    summary: "余额 & 资产调整申请台账(C3):用户 / 币种 / 金额 / 原因 / 双签状态。任何调账经财务发起 → 风控复核,server 端入账并写 A2;发起人不可自审。",
    content: {
      kind: "list",
      metrics: [
        { label: "今日申请", value: "14", sub: "调账工单", accent: "var(--admin-domain-c)", hint: "今日提交的余额 / 资产调整工单。" },
        { label: "待复核", value: "5", sub: "Maker-Checker", accent: "var(--v5-warning)", hint: "已发起、等待第二人签核的调账。" },
        { label: "今日净调整", value: "+$312", sub: "USDT 口径", accent: "var(--v5-ink-3)", hint: "今日已入账调整的净额(借贷轧差)。" },
        { label: "大额待审", value: "2", sub: "≥ $500", accent: "var(--v5-danger)", hint: "超过大额阈值、需总管理员加签的调账。" },
      ],
      search: "搜索用户 ID / 工单号",
      filterKey: "ccy",
      filters: ["全部", "USDT", "NEX", "积分"],
      columns: [
        { key: "ticket", header: "工单", mono: true },
        { key: "uid", header: "用户", mono: true },
        { key: "ccy", header: "币种" },
        { key: "amount", header: "金额", mono: true, align: "right" },
        { key: "reason", header: "原因" },
        { key: "state", header: "双签", status: true },
      ],
      rows: [
        { ticket: "ADJ-2606-0142", uid: "U-77310", ccy: "USDT", amount: "+$120.00", reason: "充值漏账补记", state: "待复核" },
        { ticket: "ADJ-2606-0141", uid: "U-65120", ccy: "USDT", amount: "−$58.00", reason: "重复入账冲正", state: "已通过" },
        { ticket: "ADJ-2606-0140", uid: "U-88421", ccy: "NEX", amount: "+320 NEX", reason: "产出结算误差补发", state: "待复核" },
        { ticket: "ADJ-2606-0139", uid: "U-90233", ccy: "USDT", amount: "+$520.00", reason: "兑付差额补偿 · 大额", state: "待复核" },
        { ticket: "ADJ-2606-0138", uid: "U-58642", ccy: "积分", amount: "+1,500", reason: "任务积分发放修正", state: "已通过" },
        { ticket: "ADJ-2606-0137", uid: "U-81905", ccy: "USDT", amount: "−$640.00", reason: "违规返利追回 · 大额", state: "待复核" },
        { ticket: "ADJ-2606-0136", uid: "U-72488", ccy: "NEX", amount: "−45 NEX", reason: "误发回收 · 已知会用户", state: "已拒绝" },
        { ticket: "ADJ-2606-0135", uid: "U-93077", ccy: "USDT", amount: "+$36.00", reason: "客诉核实补偿", state: "已通过" },
      ],
      detail: true,
      rowActions: [
        { label: "通过", tone: "primary" },
        { label: "驳回", tone: "danger" },
      ],
      note: "调账经财务发起、风控复核双签,发起人不可自审;≥ $500 大额需总管理员加签。每笔均生成 debit/credit 凭证并写入 A2,可逆操作须附冲正工单号。",
    },
  },
  {
    path: "/users/kyc",
    summary: "KYC 合规台账(C4):KYC 等级 / 状态 / $1 验证 / 复审。等级决定提现与兑换额度;升降级与人工复审写入 A2,敏感复核需双签。",
    content: {
      kind: "list",
      metrics: [
        { label: "已验证用户", value: "12,840", sub: "$1 验证通过", accent: "var(--v5-success)", hint: "完成 $1 小额验证、可正常出入金的用户数。" },
        { label: "待复审", value: "23", sub: "人工队列", accent: "var(--v5-warning)", hint: "材料进入人工复审、等待裁定的账户。" },
        { label: "高级 KYC", value: "1,206", sub: "高额度档", accent: "var(--admin-domain-c)", hint: "完成进阶认证、享更高提现额度的用户。" },
        { label: "驳回 / 高危", value: "8", sub: "近 7 日", accent: "var(--v5-danger)", hint: "证件存疑或命中名单、被驳回的申请。" },
      ],
      search: "搜索用户 ID / 证件尾号",
      filterKey: "level",
      filters: ["全部", "基础", "高级", "未验证"],
      columns: [
        { key: "uid", header: "用户", mono: true },
        { key: "level", header: "等级" },
        { key: "verify", header: "$1 验证" },
        { key: "region", header: "地区" },
        { key: "submitted", header: "提交", mono: true },
        { key: "state", header: "状态", status: true },
      ],
      rows: [
        { uid: "U-88421", level: "高级", verify: "已通过", region: "SEA", submitted: "06-01 10:22", state: "通过" },
        { uid: "U-90233", level: "基础", verify: "已通过", region: "LATAM", submitted: "06-02 09:14", state: "通过" },
        { uid: "U-77310", level: "基础", verify: "处理中", region: "SEA", submitted: "06-02 11:03", state: "待复核" },
        { uid: "U-65120", level: "高级", verify: "已通过", region: "EU", submitted: "05-30 16:48", state: "待复核" },
        { uid: "U-81905", level: "未验证", verify: "未发起", region: "—", submitted: "06-02 08:31", state: "高危" },
        { uid: "U-72488", level: "基础", verify: "已通过", region: "SEA", submitted: "05-29 14:20", state: "通过" },
        { uid: "U-58642", level: "高级", verify: "已通过", region: "MENA", submitted: "05-31 12:05", state: "通过" },
        { uid: "U-93077", level: "基础", verify: "已通过", region: "LATAM", submitted: "06-01 19:40", state: "待复核" },
      ],
      detail: true,
      rowActions: [
        { label: "KYC 通过", tone: "primary" },
        { label: "驳回", tone: "danger" },
        { label: "要求补件" },
      ],
      note: "KYC 等级决定 D 域提现 / G 域兑换额度上限;$1 验证为小额回流确权,不构成出入金。升降级与驳回写入 A2;命中制裁 / 高危名单的裁定需风控双签,发起人不可自审。",
    },
  },
  {
    path: "/users/security",
    summary: "安全 & 会话(C5):登录 / 设备 / 会话 / 异常。聚合近期登录与活跃会话,异常事件联动 C6 风控与 K 域标记;踢出会话 / 强制改密写入 A2。",
    content: {
      kind: "list",
      metrics: [
        { label: "活跃会话", value: "9,612", sub: "全端在线", accent: "var(--admin-domain-c)", hint: "当前持有有效令牌的会话数。" },
        { label: "异常登录", value: "31", sub: "近 24h", accent: "var(--v5-warning)", hint: "异地 / 新设备 / 风险 IP 命中的登录尝试。" },
        { label: "2FA 覆盖", value: "78%", sub: "已绑定用户", accent: "var(--v5-success)", hint: "已开启两步验证的用户占比。" },
        { label: "高危会话", value: "5", sub: "待处置", accent: "var(--v5-danger)", hint: "命中盗号特征、建议踢出的会话。" },
      ],
      search: "搜索用户 ID / 设备指纹",
      filterKey: "type",
      filters: ["全部", "登录", "新设备", "改密", "异常"],
      columns: [
        { key: "ts", header: "时间", mono: true },
        { key: "uid", header: "用户", mono: true },
        { key: "type", header: "事件" },
        { key: "device", header: "设备 / IP" },
        { key: "geo", header: "地理" },
        { key: "state", header: "判定", status: true },
      ],
      rows: [
        { ts: "14:11:03", uid: "U-88421", type: "登录", device: "iOS 17 · 203.0.x", geo: "新加坡", state: "正常" },
        { ts: "13:59:28", uid: "U-81905", type: "新设备", device: "Android · 198.51.x", geo: "尼日利亚", state: "异常" },
        { ts: "13:40:12", uid: "U-90233", type: "登录", device: "iOS 18 · 200.12.x", geo: "墨西哥", state: "正常" },
        { ts: "12:55:46", uid: "U-77310", type: "改密", device: "Web · 172.16.x", geo: "马来西亚", state: "正常" },
        { ts: "12:18:07", uid: "U-65120", type: "异常", device: "Web · 45.83.x · VPN", geo: "未知", state: "高危" },
        { ts: "11:42:33", uid: "U-72488", type: "登录", device: "Android · 202.5.x", geo: "印尼", state: "正常" },
        { ts: "11:05:50", uid: "U-58642", type: "新设备", device: "iOS 17 · 91.72.x", geo: "阿联酋", state: "待复核" },
        { ts: "10:22:19", uid: "U-93077", type: "异常", device: "Web · 103.21.x · 代理", geo: "可疑", state: "高危" },
      ],
      detail: true,
      rowActions: [
        { label: "强制下线", tone: "danger" },
        { label: "锁定账户", tone: "danger" },
      ],
      note: "异常判定由 C6 规则与 K 域标记联动产出;踢出会话 / 强制改密 / 解绑设备写入 A2 留痕。批量处置(同设备多账户)按高敏操作走双签,发起人不可自审。",
    },
  },
  {
    path: "/users/reg-risk",
    summary: "注册 / 登录风控看板(C6):注册风险分布 / 拦截率 / 多账户命中。规则与名单产出的命中信号下发至 C2 / C5 处置,口径为 server 端事件流派生。",
    content: {
      kind: "dashboard",
      metrics: [
        { label: "今日注册", value: "1,842", sub: "全渠道", accent: "var(--admin-domain-c)", hint: "今日完成注册的新账户数。" },
        { label: "拦截率", value: "6.4%", sub: "注册 + 登录", accent: "var(--v5-warning)", hint: "被风控规则拦截的请求占比。", delta: { dir: "down", text: "0.8pt", good: true } },
        { label: "多账户命中", value: "47", sub: "同设备 / 同 IP 段", accent: "var(--v5-danger)", hint: "命中关联规则、疑似一人多号的账户。" },
        { label: "高危拦截", value: "118", sub: "近 24h", accent: "var(--v5-danger)", hint: "命中黑名单 / 机器特征的高危拦截数。" },
      ],
      charts: [
        {
          type: "donut",
          title: "注册风险分布",
          sub: "今日 · 按风险评分分档",
          unit: "%",
          segments: [
            { label: "低危 · 放行", value: 71, color: "var(--v5-success)" },
            { label: "中危 · 加验证", value: 22, color: "var(--v5-warning)" },
            { label: "高危 · 拦截", value: 7, color: "var(--v5-danger)" },
          ],
        },
        {
          type: "area",
          title: "拦截率趋势",
          sub: "近 14 日 · 含 8% 预警线",
          color: "var(--admin-domain-c)",
          refLine: 8,
          data: [5.1, 4.8, 5.6, 6.2, 5.9, 7.1, 6.8, 5.4, 6.0, 6.6, 7.3, 6.1, 5.8, 6.4],
        },
        {
          type: "bars",
          title: "多账户命中来源",
          sub: "今日 · 按关联维度",
          color: "var(--v5-danger)",
          unit: "",
          labels: ["同设备", "同 IP 段", "同收款", "同推荐链", "行为相似"],
          data: [18, 12, 7, 6, 4],
        },
      ],
      controlLink: { label: "反多账户规则", href: "/risk/multi-account" },
      note: "风险评分与命中信号为 server 端事件流派生,前端仅展示;命中结果下发至 C2 处置与 C5 会话判定。规则阈值调整属 A 域配置,需双签生效。",
    },
  },
];
