/** 域 I 内容与合规 CMS — 注册表。accent=--admin-domain-i。
 * 转化文案 A/B、Nova 站内助手推送、通知 Campaign、信任中心 CMS、风险披露版本、i18n 双语文案、教程中心。
 * 信任中心 / 风险披露为真实合规内容管理:中性专业语言,发布 / 版本 / 审核均走 Maker-Checker + A2 留痕。
 */
import type { ModuleEntry } from "@/lib/admin/module-content";

export const DOMAIN_I: ModuleEntry[] = [
  {
    path: "/content/copy-ab",
    summary: "转化文案 A/B 实验台(I1)。各转化位多变体分流,以 B 域漏斗事件为权威指标;达显著性后由内容运营提报、增长复核切全量。",
    content: {
      kind: "list",
      metrics: [
        { label: "进行中实验", value: "6", sub: "全转化位", accent: "var(--admin-domain-i)", hint: "当前正在分流的文案实验数。" },
        { label: "本月已结", value: "11", sub: "胜出 7 / 持平 4", accent: "var(--v5-success)" },
        { label: "覆盖位", value: "9", sub: "首页 / 试用 / 充值 / 提现…", accent: "var(--admin-domain-i)", hint: "已接入实验框架的文案位数量。" },
        { label: "待显著性", value: "3", sub: "样本未达阈值", accent: "var(--v5-warning)", hint: "尚未达到统计显著、不可下结论的实验。" },
      ],
      search: "搜索实验 / 文案位",
      filterKey: "state",
      filters: ["全部", "进行中", "待显著性", "已结(胜出)", "草稿"],
      columns: [
        { key: "exp", header: "实验", mono: true },
        { key: "slot", header: "文案位" },
        { key: "variants", header: "变体", align: "center" },
        { key: "metric", header: "主指标" },
        { key: "lift", header: "相对增幅", align: "right", mono: true },
        { key: "sig", header: "显著性", align: "right", mono: true },
        { key: "state", header: "状态", status: true },
      ],
      rows: [
        { exp: "AB-I-2041", slot: "首页主 CTA 文案", variants: "A/B/C", metric: "首页→注册点击率", lift: "+8.4%", sig: "98%", state: "已结(胜出)" },
        { exp: "AB-I-2052", slot: "试用领取页标题", variants: "A/B", metric: "试用领取完成率", lift: "+5.1%", sig: "95%", state: "进行中" },
        { exp: "AB-I-2058", slot: "充值页档位说明", variants: "A/B", metric: "首充完成率", lift: "+2.0%", sig: "82%", state: "待显著性" },
        { exp: "AB-I-2063", slot: "提现确认弹窗副本", variants: "A/B", metric: "提现提交完成率", lift: "+1.3%", sig: "76%", state: "待显著性" },
        { exp: "AB-I-2069", slot: "复购引导横幅", variants: "A/B/C", metric: "复购点击率", lift: "+6.7%", sig: "96%", state: "进行中" },
        { exp: "AB-I-2074", slot: "推荐邀请文案", variants: "A/B", metric: "邀请链接生成率", lift: "+3.9%", sig: "91%", state: "进行中" },
        { exp: "AB-I-2080", slot: "空状态引导语", variants: "A/B", metric: "空页→功能页跳转率", lift: "—", sig: "—", state: "草稿" },
        { exp: "AB-I-2081", slot: "签到提醒推送文案", variants: "A/B", metric: "次日回访率", lift: "—", sig: "—", state: "草稿" },
      ],
      detail: true,
      rowActions: [
        { label: "设为胜出", tone: "primary", whenStatus: "进行中" },
        { label: "停止实验", tone: "danger", whenStatus: "进行中" },
      ],
      note: "主指标取 B 域 server 端漏斗事件,不以前端点击近似;未达显著性的实验不得对外宣称结论。切全量需内容运营提报 + 增长复核双签,变更写入 A2 审计。",
    },
  },
  {
    path: "/content/nova",
    summary: "Nova(站内 AI 助手)推送运营(I2)。按受众分群投放对话式提示;支持频控与一键停投,所有推送话术经合规白名单校验。",
    content: {
      kind: "list",
      metrics: [
        { label: "在投推送", value: "8", sub: "对话式提示", accent: "var(--admin-domain-i)", hint: "当前处于投放状态的 Nova 提示数。" },
        { label: "今日触达", value: "42,180", sub: "去重用户", accent: "var(--admin-domain-i)" },
        { label: "平均点击率", value: "11.3%", sub: "近 7 日", accent: "var(--v5-success)" },
        { label: "频控拦截", value: "2", sub: "超频自动暂停", accent: "var(--v5-warning)", hint: "因超过单用户频控阈值被自动暂停的推送。" },
      ],
      search: "搜索推送主题 / 受众",
      filterKey: "state",
      filters: ["全部", "投放中", "审核中", "已暂停", "草稿"],
      columns: [
        { key: "push", header: "推送", mono: true },
        { key: "topic", header: "主题" },
        { key: "audience", header: "受众分群" },
        { key: "reach", header: "触达", align: "right", mono: true },
        { key: "ctr", header: "点击率", align: "right", mono: true },
        { key: "state", header: "状态", status: true },
      ],
      rows: [
        { push: "NOVA-3012", topic: "试用到期提醒", audience: "试用期剩 ≤ 2 天", reach: "6,420", ctr: "18.6%", state: "投放中" },
        { push: "NOVA-3018", topic: "首充未完成引导", audience: "注册未充值", reach: "9,830", ctr: "9.2%", state: "投放中" },
        { push: "NOVA-3021", topic: "设备产出日报摘要", audience: "持有算力设备", reach: "12,540", ctr: "13.7%", state: "投放中" },
        { push: "NOVA-3026", topic: "提现进度查询入口", audience: "近 3 日有提现", reach: "3,110", ctr: "21.4%", state: "投放中" },
        { push: "NOVA-3030", topic: "新功能介绍", audience: "全量活跃", reach: "—", ctr: "—", state: "审核中" },
        { push: "NOVA-3033", topic: "签到连续奖励提示", audience: "签到中断 1 天", reach: "8,260", ctr: "7.8%", state: "已暂停" },
        { push: "NOVA-3037", topic: "推荐好友说明", audience: "已绑定推荐人", reach: "1,920", ctr: "6.1%", state: "投放中" },
        { push: "NOVA-3041", topic: "安全验证提醒", audience: "未开启 2FA", reach: "—", ctr: "—", state: "草稿" },
      ],
      detail: true,
      rowActions: [
        { label: "发布", tone: "primary", whenStatus: "草稿" },
        { label: "停投", tone: "danger", whenStatus: "投放中" },
      ],
      note: "Nova 话术须通过合规白名单校验(禁收益承诺 / 诱导性措辞);单用户频控由系统强制,超频自动暂停。投放与停投记录写入 A2 审计。",
    },
  },
  {
    path: "/content/notifications",
    summary: "通知 Campaign 编排(I3)。统一管理站内信 / 推送 / 邮件多渠道触达;受众取 B 域分群,营销类需用户订阅授权,交易类豁免。",
    content: {
      kind: "list",
      metrics: [
        { label: "活动总数", value: "14", sub: "本月", accent: "var(--admin-domain-i)", hint: "本月创建的通知 Campaign 数。" },
        { label: "进行中", value: "5", sub: "多渠道", accent: "var(--admin-domain-i)" },
        { label: "平均到达率", value: "96.8%", sub: "近 30 日", accent: "var(--v5-success)" },
        { label: "退订率", value: "0.4%", sub: "营销类", accent: "var(--v5-ink-3)", hint: "营销类通知触发的退订占比。" },
      ],
      search: "搜索活动 / 渠道",
      filterKey: "channel",
      filters: ["全部", "站内信", "推送", "邮件", "多渠道"],
      columns: [
        { key: "camp", header: "活动", mono: true },
        { key: "title", header: "活动名" },
        { key: "channel", header: "渠道" },
        { key: "audience", header: "受众" },
        { key: "delivered", header: "到达", align: "right", mono: true },
        { key: "state", header: "状态", status: true },
      ],
      rows: [
        { camp: "CMP-5101", title: "月度产出对账提醒", channel: "站内信", audience: "持有设备用户", delivered: "31,200", state: "已结" },
        { camp: "CMP-5108", title: "维护窗口预告", channel: "多渠道", audience: "全量", delivered: "88,640", state: "进行中" },
        { camp: "CMP-5112", title: "试用回归召回", channel: "推送", audience: "试用流失 7 日", delivered: "12,430", state: "进行中" },
        { camp: "CMP-5117", title: "提现到账通知", channel: "推送", audience: "提现完成", delivered: "4,860", state: "进行中" },
        { camp: "CMP-5120", title: "安全策略更新告知", channel: "邮件", audience: "全量", delivered: "—", state: "审核中" },
        { camp: "CMP-5124", title: "新设备上架公告", channel: "多渠道", audience: "活跃用户", delivered: "—", state: "草稿" },
        { camp: "CMP-5128", title: "签到活动周报", channel: "站内信", audience: "签到参与者", delivered: "22,910", state: "进行中" },
        { camp: "CMP-5131", title: "推荐计划说明", channel: "邮件", audience: "已订阅营销", delivered: "9,540", state: "已结" },
      ],
      detail: true,
      primaryAction: { label: "新建 Campaign", fields: ["名称", "渠道", "受众"] },
      rowActions: [
        { label: "发送", tone: "primary", whenStatus: "草稿" },
        { label: "停发", tone: "danger", whenStatus: "进行中" },
      ],
      note: "营销类 Campaign 仅向已授权订阅用户投放,交易类(到账 / 安全 / 维护)豁免;退订状态实时同步。受众分群与发送量以 server 端为准,发送动作写入 A2 审计。",
    },
  },
  {
    path: "/content/trust",
    summary: "信任中心 CMS(I4)。集中维护服务条款、隐私政策、资金安全、合规资质等公开披露条目;发布走草稿→审核→上线,版本可追溯。",
    content: {
      kind: "list",
      metrics: [
        { label: "已发布条目", value: "16", sub: "对外可见", accent: "var(--admin-domain-i)", hint: "当前线上可见的信任中心条目数。" },
        { label: "待审核", value: "2", sub: "法务复核中", accent: "var(--v5-warning)", hint: "提交后等待法务 / 合规复核的条目。" },
        { label: "双语完整度", value: "100%", sub: "en / zh 齐备", accent: "var(--v5-success)" },
        { label: "本月更新", value: "4", sub: "条款 / 资质", accent: "var(--v5-ink-3)" },
      ],
      search: "搜索条目 / 类型",
      filterKey: "type",
      filters: ["全部", "服务条款", "隐私政策", "资金与安全", "合规资质", "帮助"],
      columns: [
        { key: "doc", header: "条目", mono: true },
        { key: "title", header: "标题" },
        { key: "type", header: "类型" },
        { key: "ver", header: "版本", mono: true },
        { key: "updated", header: "更新时间", mono: true, align: "right" },
        { key: "state", header: "发布状态", status: true },
      ],
      rows: [
        { doc: "TRUST-001", title: "服务条款", type: "服务条款", ver: "v4.2", updated: "2026-05-28", state: "已上线" },
        { doc: "TRUST-002", title: "隐私政策", type: "隐私政策", ver: "v3.8", updated: "2026-05-20", state: "已上线" },
        { doc: "TRUST-003", title: "资金安全说明", type: "资金与安全", ver: "v2.5", updated: "2026-05-30", state: "已上线" },
        { doc: "TRUST-004", title: "账户安全与 2FA 指引", type: "资金与安全", ver: "v2.1", updated: "2026-05-12", state: "已上线" },
        { doc: "TRUST-005", title: "平台合规资质", type: "合规资质", ver: "v1.9", updated: "2026-06-01", state: "审核中" },
        { doc: "TRUST-006", title: "用户身份核验说明", type: "隐私政策", ver: "v1.4", updated: "2026-05-26", state: "已上线" },
        { doc: "TRUST-007", title: "争议与申诉流程", type: "帮助", ver: "v1.2", updated: "2026-04-30", state: "已上线" },
        { doc: "TRUST-008", title: "数据存储与跨境说明", type: "隐私政策", ver: "v1.1", updated: "2026-06-01", state: "审核中" },
      ],
      detail: true,
      primaryAction: { label: "新增条目", fields: ["标题", "类型"] },
      rowActions: [
        { label: "发布", tone: "primary", whenStatus: "审核中" },
        { label: "下架", tone: "danger", whenStatus: "已上线" },
      ],
      note: "信任中心条目为对外法律 / 合规文本,采用中性专业表述;发布走草稿→法务审核→上线三态,历史版本全部留存可追溯,上线动作需 Maker-Checker 双签并写入 A2 审计。",
    },
  },
  {
    path: "/content/disclosure",
    summary: "风险披露版本管理(I5)。维护投资与产品风险提示、合规公告的版本与生效区间;新版上线前需合规审核通过,旧版归档留痕。",
    content: {
      kind: "list",
      metrics: [
        { label: "当前生效版本", value: "v3.1", sub: "全量展示", accent: "var(--admin-domain-i)", hint: "线上正在向用户展示的风险披露版本。" },
        { label: "待生效", value: "1", sub: "已排期", accent: "var(--v5-warning)", hint: "审核通过、等待到达生效时间的版本。" },
        { label: "合规审核中", value: "1", sub: "法务复核", accent: "var(--v5-warning)" },
        { label: "历史归档", value: "9", sub: "可追溯", accent: "var(--v5-ink-3)", hint: "已被新版替换、留存备查的历史版本。" },
      ],
      search: "搜索版本 / 披露项",
      filterKey: "review",
      filters: ["全部", "已通过", "审核中", "已归档", "草稿"],
      columns: [
        { key: "ver", header: "版本号", mono: true },
        { key: "scope", header: "披露项" },
        { key: "effective", header: "生效日", mono: true },
        { key: "expires", header: "失效日", mono: true },
        { key: "lang", header: "语言" },
        { key: "review", header: "合规审核", status: true },
      ],
      rows: [
        { ver: "v3.1", scope: "投资风险提示 + 产品说明", effective: "2026-05-15", expires: "—", lang: "en / zh", review: "已通过" },
        { ver: "v3.2", scope: "新增设备衰减风险条款", effective: "2026-06-10", expires: "—", lang: "en / zh", review: "已通过" },
        { ver: "v3.3", scope: "跨境合规公告修订", effective: "待定", expires: "—", lang: "en / zh", review: "审核中" },
        { ver: "v3.0", scope: "投资风险提示 + 产品说明", effective: "2026-03-20", expires: "2026-05-15", lang: "en / zh", review: "已归档" },
        { ver: "v2.9", scope: "提现与资金风险提示", effective: "2026-01-12", expires: "2026-03-20", lang: "en / zh", review: "已归档" },
        { ver: "v2.8", scope: "投资风险提示", effective: "2025-11-05", expires: "2026-01-12", lang: "en / zh", review: "已归档" },
        { ver: "v3.4", scope: "兑换通道风险补充说明", effective: "草稿", expires: "—", lang: "zh", review: "草稿" },
        { ver: "v2.7", scope: "账户安全风险提示", effective: "2025-09-01", expires: "2025-11-05", lang: "en / zh", review: "已归档" },
      ],
      detail: true,
      rowActions: [
        { label: "发布新版", tone: "primary" },
        { label: "归档" },
      ],
      note: "风险披露为强制合规内容,语言中性、不含收益承诺;新版须合规审核通过后按生效日自动切换,旧版同步归档。版本发布需合规 + 总管理员双签并写入 A2 审计,任一版本不可删除。",
    },
  },
  {
    path: "/content/i18n",
    summary: "i18n 双语文案管理(I6)。集中维护 en / zh 文案键值,与前端 PRD 同源;缺失或未翻译的键会被标记,阻断对应模块发版。",
    content: {
      kind: "list",
      metrics: [
        { label: "文案键", value: "1,840", sub: "全模块", accent: "var(--admin-domain-i)", hint: "纳入 i18n 管理的键总数。" },
        { label: "翻译完整度", value: "99.6%", sub: "en / zh", accent: "var(--v5-success)" },
        { label: "缺失键", value: "7", sub: "待补译", accent: "var(--v5-warning)", hint: "存在一侧语言缺失、需补齐的键。" },
        { label: "本周新增", value: "32", sub: "随功能上线", accent: "var(--v5-ink-3)" },
      ],
      search: "搜索 key / 命名空间",
      filterKey: "ns",
      filters: ["全部", "home", "trial", "wallet", "device", "referral", "trust"],
      columns: [
        { key: "key", header: "Key", mono: true },
        { key: "ns", header: "命名空间" },
        { key: "en", header: "EN" },
        { key: "zh", header: "ZH" },
        { key: "state", header: "状态", status: true },
      ],
      rows: [
        { key: "home.hero.cta", ns: "home", en: "Start earning", zh: "立即开始", state: "已完成" },
        { key: "trial.claim.title", ns: "trial", en: "Claim your trial", zh: "领取试用", state: "已完成" },
        { key: "wallet.withdraw.confirm", ns: "wallet", en: "Confirm withdrawal", zh: "确认提现", state: "已完成" },
        { key: "device.yield.daily", ns: "device", en: "Daily output", zh: "每日产出", state: "已完成" },
        { key: "referral.invite.share", ns: "referral", en: "Share invite link", zh: "分享邀请链接", state: "已完成" },
        { key: "trust.disclosure.banner", ns: "trust", en: "Risk disclosure", zh: "风险披露", state: "已完成" },
        { key: "device.decay.notice", ns: "device", en: "Output decay notice", zh: "—", state: "缺失(待补译)" },
        { key: "wallet.exchange.fee", ns: "wallet", en: "—", zh: "兑换手续费", state: "缺失(待补译)" },
      ],
      detail: true,
      rowActions: [
        { label: "补全", whenStatus: "缺失(待补译)" },
        { label: "发布" },
      ],
      note: "文案键与前端代码同源(t.namespace.key),禁止 UI 硬编码;一侧语言缺失即标记缺失并阻断对应模块发版。键的增删改写入 A2 审计,版本随前端 PRD 对齐发布。",
    },
  },
  {
    path: "/content/learn",
    summary: "教程中心(I7)。维护新手引导、功能说明、安全指南等帮助内容;按分类组织,支持版本管理与双语,发布走草稿→审核→上线。",
    content: {
      kind: "list",
      metrics: [
        { label: "已发布教程", value: "38", sub: "对外可见", accent: "var(--admin-domain-i)", hint: "当前线上可见的教程数。" },
        { label: "草稿", value: "5", sub: "编辑中", accent: "var(--v5-warning)" },
        { label: "双语完整度", value: "100%", sub: "en / zh 齐备", accent: "var(--v5-success)" },
        { label: "本月阅读量", value: "126K", sub: "全部教程", accent: "var(--v5-ink-3)" },
      ],
      search: "搜索教程 / 分类",
      filterKey: "cat",
      filters: ["全部", "新手引导", "功能说明", "资金与提现", "安全", "常见问题"],
      columns: [
        { key: "art", header: "教程", mono: true },
        { key: "title", header: "标题" },
        { key: "cat", header: "分类" },
        { key: "ver", header: "版本", mono: true },
        { key: "views", header: "阅读量", align: "right", mono: true },
        { key: "state", header: "发布状态", status: true },
      ],
      rows: [
        { art: "EDU-7001", title: "Nexion 新手 5 步上手", cat: "新手引导", ver: "v2.3", views: "18,420", state: "已上线" },
        { art: "EDU-7006", title: "如何领取并使用试用", cat: "新手引导", ver: "v1.8", views: "12,940", state: "已上线" },
        { art: "EDU-7010", title: "算力设备产出机制说明", cat: "功能说明", ver: "v1.5", views: "9,360", state: "已上线" },
        { art: "EDU-7014", title: "充值与提现流程指引", cat: "资金与提现", ver: "v2.0", views: "15,280", state: "已上线" },
        { art: "EDU-7018", title: "开启两步验证保护账户", cat: "安全", ver: "v1.3", views: "6,710", state: "已上线" },
        { art: "EDU-7022", title: "推荐计划怎么算", cat: "功能说明", ver: "v1.1", views: "4,520", state: "已上线" },
        { art: "EDU-7026", title: "设备衰减与续期说明", cat: "功能说明", ver: "v0.9", views: "—", state: "审核中" },
        { art: "EDU-7030", title: "兑换通道使用指南", cat: "资金与提现", ver: "v0.6", views: "—", state: "草稿" },
      ],
      detail: true,
      primaryAction: { label: "新建教程", fields: ["标题", "分类"] },
      rowActions: [
        { label: "发布", tone: "primary", whenStatus: "草稿" },
        { label: "下架", tone: "danger", whenStatus: "已上线" },
      ],
      note: "教程内容采用中性说明语气,不含收益承诺或诱导措辞;发布走草稿→审核→上线三态,双语齐备方可上线。上线 / 下架写入 A2 审计,历史版本留存可追溯。",
    },
  },
];
