"use client";
import { useState } from 'react';
import type { Catalog, NativeRef, Policy, PolicyContent, PolicyPage } from '@/lib/admin/promotion-types';
import { promotionRead } from '@/lib/admin/promotion-client';
import { fetchA2Overview } from '@/lib/admin/a2-client';
import { Button, ConfirmCommand, DeviceRightsSummary, Dialog, Field, Loading, Notice, ReadError, Summary, Table, Tag, text, useRead } from './h4-promotion-ui';
const KINDS: Record<PolicyContent['kind'], string> = { FIRST_PURCHASE: '首购认定', DEVICE_AUDIENCE: '设备参与资格', DEVICE_RIGHTS: '赠品设备权益', ASSET: '资产成熟与可用', SETTLEMENT: '订单结算', STACKING: '优惠叠加', REFUND: '售后追回', QUOTE: '报价期限', AUTHORIZATION: '审核发布授权' };
const FIXED: Record<PolicyContent['kind'], Record<string, unknown>> = { FIRST_PURCHASE: { executorCode: 'PROMOTION_FIRST_PURCHASE_V1' }, DEVICE_AUDIENCE: { executorCode: 'PROMOTION_DEVICE_AUDIENCE_V1', excludeExpired: true, excludePhoneAndTrial: true }, DEVICE_RIGHTS: { executorCode: 'COMMERCE_GIFT_FROM_PRODUCT_V1' }, ASSET: { executorCode: 'EXISTING_EARNINGS_RELEASE_V1', riskBucketRouting: true }, SETTLEMENT: { executorCode: 'EXISTING_ORDER_MATURITY_V1', requiresPaid: true, requiresNoRefundHold: true, requiresNoFreeze: true }, STACKING: { executorCode: 'PROMOTION_STACKING_V1', samePurchaseUnit: 'EXCLUSIVE' }, REFUND: { executorCode: 'PROMOTION_WALLET_REFUND_V1', principalChannel: 'WALLET', scope: 'WHOLE_ORDER', insufficientRecovery: 'MANUAL_REVIEW', negativeBalance: false, crossAssetDeduction: false }, QUOTE: { executorCode: 'PROMOTION_QUOTE_V1', payByRule: 'MIN_ORDER_DEADLINE_ACTIVITY_END' }, AUTHORIZATION: { executorCode: 'PROMOTION_AUTHORIZATION_V1', approvalCapability: 'growth_promotion_approve', publishCapability: 'growth_promotion_publish', scope: 'PROMOTION_ONLY' } };
export default function PromotionPolicies({ catalog, can, onClose, onChanged }: {
    catalog: Catalog;
    can: (v: string) => boolean;
    onClose: () => void;
    onChanged: () => void;
}) {
    const [cursor, setCursor] = useState<string | null>(null), [selected, setSelected] = useState<Policy | null>(null), [creating, setCreating] = useState(false), [action, setAction] = useState<'approve' | 'revoke' | null>(null);
    const list = useRead(() => promotionRead<PolicyPage>('/promotion-policies', { limit: 20, cursor }), [cursor]);
    if (creating)
        return <PolicyCreate catalog={catalog} can={can} onClose={() => setCreating(false)} onDone={() => { setCreating(false); list.reload(); onChanged(); }}/>;
    if (action && selected)
        return <ConfirmCommand writeAllowed={can('growth_promotion_policy_approve') && !list.loading && !list.error} title={action === 'approve' ? '批准政策版本' : '撤销政策版本'} intent={{ operation: action === 'approve' ? 'approvePolicy' : 'revokePolicy', targetId: `${selected.policyId}:${selected.version}`, path: `/promotion-policies/${selected.policyId}/versions/${selected.version}/${action}`, method: 'POST' }} body={{ expectedRevision: selected.revision, evidenceRefs: [] }} onClose={() => setAction(null)} onSuccess={() => { setAction(null); setSelected(null); list.reload(); onChanged(); }}><Summary rows={[['政策类别', KINDS[selected.content.kind]], ['版本', `v${selected.version}`], ['影响', action === 'approve' ? '批准后可供活动引用；不自动发布活动。' : '原引用不可继续新发布，历史承诺按原合同处理。']]}/></ConfirmCommand>;
    if (selected)
        return <Dialog title={`${KINDS[selected.content.kind]} · v${selected.version}`} wide onClose={() => setSelected(null)} footer={<><Button onClick={() => setSelected(null)}>返回政策列表</Button>{selected.state === 'DRAFT' && <Button kind="primary" disabled={!can('growth_promotion_policy_approve')} onClick={() => setAction('approve')}>批准政策</Button>}{selected.state === 'APPROVED' && <Button kind="danger" disabled={!can('growth_promotion_policy_approve')} onClick={() => setAction('revoke')}>撤销政策</Button>}</>}><PromotionPolicyDetails policy={selected} catalog={catalog}/></Dialog>;
    return <Dialog title="政策与原合同" wide onClose={onClose} footer={<><Button onClick={onClose}>返回活动</Button><Button kind="primary" disabled={!can('growth_promotion_policy_write')} onClick={() => setCreating(true)}>新建政策草稿</Button></>}><Notice title="批准与发布分开">只可选择可用的原合同，版本和内容摘要由目录绑定，不需要人工填写。未批准政策不能执行活动。</Notice>{list.loading ? <Loading /> : list.error ? <ReadError target="政策与原合同" error={list.error} retry={list.reload}/> : <Table headers={['政策类别', '版本', '状态', '操作']} rows={(list.data?.items || []).map(p => [KINDS[p.content.kind], `v${p.version}`, <Tag value={p.state}/>, <Button kind="link" onClick={() => setSelected(p)}>查看</Button>])}/>}<div className="actions"><Button disabled={!cursor} onClick={() => setCursor(null)}>回到首页</Button><Button disabled={!list.data?.hasMore} onClick={() => setCursor(list.data!.nextCursor)}>下一页</Button></div></Dialog>;
}
const FIELD_LABELS: Record<string, string> = { mode: '首购计算单位', restoreAfterRefund: '退款后恢复资格', sources: '设备来源', states: '设备状态', productNo: '适用设备', productContract: '原商品合同', taskEligibility: '任务参与方式', rightsDescription: '权益说明', asset: '奖励资产', nativeContract: '原执行合同', availabilityDescription: '成熟与可用说明', voucher: '优惠券叠加', bundleDiscount: '组合折扣叠加', existingH8: '新人礼叠加', existingReferral: '现有邀请奖励叠加', deviceRecoveryPolicy: '设备追回原政策', lossOwner: '损失责任归属', terms: '售后说明', ttlSeconds: '报价有效期（秒）', separateMakerChecker: '审核与发布分人执行', requiresPaid: '必须付款', requiresNoRefundHold: '必须没有售后挂起', requiresNoFreeze: '必须没有冻结', riskBucketRouting: '使用原风险资金桶', samePurchaseUnit: '同一购买单位', principalChannel: '本金退款渠道', scope: '适用范围', insufficientRecovery: '追回不足处理', negativeBalance: '允许负余额', crossAssetDeduction: '允许跨币扣款', payByRule: '付款截止规则', excludeExpired: '排除过期设备', excludePhoneAndTrial: '排除手机与试用设备' };
const VALUE_LABELS: Record<string, string> = { FIRST_ELIGIBLE_ORDER: '第一笔合格订单', FIRST_ELIGIBLE_UNIT: '第一个合格购买单位', EXISTING_PRODUCT_RULES: '沿原商品规则', DISABLED: '不参与任务', ALLOW: '允许叠加', DENY: '不允许叠加', ORDER: '购买设备', PROMOTION_GIFT: '促销赠品设备', ACTIVE: '已激活', ONLINE: '在线', EXCLUSIVE: '互斥', WALLET: '钱包', WHOLE_ORDER: '整单', MANUAL_REVIEW: '人工审阅', MIN_ORDER_DEADLINE_ACTIVITY_END: '订单截止与活动结束取较早', PROMOTION_ONLY: '仅促销活动' };
function PolicyCreate({ catalog, can, onClose, onDone }: {
    catalog: Catalog;
    can: (v: string) => boolean;
    onClose: () => void;
    onDone: () => void;
}) {
    const [kind, setKind] = useState<PolicyContent['kind']>('DEVICE_RIGHTS'), [content, setContent] = useState<Record<string, unknown>>({ kind: 'DEVICE_RIGHTS', ...FIXED.DEVICE_RIGHTS }), [confirm, setConfirm] = useState(false);
    const audit = useRead(fetchA2Overview, []), patch = (key: string, value: unknown) => setContent({ ...content, [key]: value });
    const choice = (key: string, values: string[], boolean = false) => <Field key={key} label={`${FIELD_LABELS[key]} *`}><select value={content[key] === undefined ? '' : String(content[key])} onChange={e => patch(key, e.target.value ? boolean ? e.target.value === 'true' : e.target.value : undefined)}><option value="">请选择</option>{values.map(v => <option key={v} value={v}>{VALUE_LABELS[v] || (v === 'true' ? '是' : v === 'false' ? '否' : v)}</option>)}</select></Field>;
    const native = (key: string, system: string) => <Field key={key} label={`${FIELD_LABELS[key]} *`} hint="目录自动绑定当前版本与内容摘要。"><select value={(content[key] as {
        resourceId?: string;
    })?.resourceId || ''} onChange={e => { const n = catalog.nativeContracts.find(n => n.system === system && n.resourceId === e.target.value); patch(key, n?.reference); }}><option value="">请选择原合同</option>{catalog.nativeContracts.filter(n => n.system === system).map(n => <option key={n.resourceId} value={n.resourceId} disabled={!n.available || !n.reference}>{text(n.title)}{!n.available ? ' · 当前不可用' : ''}</option>)}</select></Field>;
    const localized = (key: string) => <fieldset className="form-section wide" key={key}><legend>{FIELD_LABELS[key]} *</legend><div className="grid2">{(['zh', 'en', 'vi'] as const).map((lang, i) => <Field label={['中文', 'English', 'Tiếng Việt'][i]} key={lang}><textarea value={(content[key] as Record<string, string>)?.[lang] || ''} onChange={e => patch(key, { ...(content[key] as Record<string, string> || {}), [lang]: e.target.value })}/></Field>)}</div></fieldset>;
    const sku = <Field label="适用设备 *"><select value={String(content.productNo || '')} onChange={e => patch('productNo', e.target.value)}><option value="">请选择</option>{catalog.skus.filter(s => s.giftEligible && s.available).map(s => <option value={s.productNo} key={s.productNo}>{text(s.name)}</option>)}</select></Field>;
    const evidence = [...(audit.data?.operationQueue || []).filter(t => t.status === 'approved').map(t => ({ value: t.id, label: `已批准操作 · ${t.action}` })), ...(audit.data?.recentLogs || []).map(t => ({ value: t.id, label: `审计记录 · ${t.action} · ${t.ts}` }))];
    if (confirm)
        return <ConfirmCommand writeAllowed={can('growth_promotion_policy_write') && !audit.loading && !audit.error} title="保存政策草稿" intent={{ operation: 'createPolicy', targetId: 'promotion-policies', path: '/promotion-policies', method: 'POST' }} body={{ content, evidenceRefs: [] }} evidenceOptions={evidence} requireEvidence evidenceMode="select" onClose={() => setConfirm(false)} onSuccess={onDone}><Notice title="保存后仍需批准">所选原合同与证据将在批准时由服务端重新核验。</Notice></ConfirmCommand>;
    return <Dialog title="新建政策草稿" wide onClose={onClose} footer={<><Button onClick={onClose}>取消</Button><Button kind="primary" disabled={!can('growth_promotion_policy_write') || audit.loading || !!audit.error || !evidence.length} onClick={() => setConfirm(true)}>保存前确认</Button></>}><Field label="政策类别"><select value={kind} onChange={e => { const next = e.target.value as PolicyContent['kind']; setKind(next); setContent({ kind: next, ...FIXED[next] }); }}>{Object.entries(KINDS).map(([v, label]) => <option key={v} value={v}>{label}</option>)}</select></Field><div className="grid2">{kind === 'FIRST_PURCHASE' && <>{choice('mode', ['FIRST_ELIGIBLE_ORDER', 'FIRST_ELIGIBLE_UNIT'])}{choice('restoreAfterRefund', ['true', 'false'], true)}</>}{kind === 'DEVICE_AUDIENCE' && <>{['sources', 'states'].map(key => <fieldset key={key} className="form-section"><legend>{FIELD_LABELS[key]}</legend>{(key === 'sources' ? ['ORDER', 'PROMOTION_GIFT'] : ['ACTIVE', 'ONLINE']).map(v => <label className="evidence-choice" key={v}><input type="checkbox" checked={(content[key] as string[] || []).includes(v)} onChange={e => patch(key, e.target.checked ? [...(content[key] as string[] || []), v] : (content[key] as string[] || []).filter(x => x !== v))}/>{VALUE_LABELS[v]}</label>)}</fieldset>)}</>}{kind === 'DEVICE_RIGHTS' && <>{sku}{native('productContract', 'E1_PRODUCT')}{choice('taskEligibility', ['EXISTING_PRODUCT_RULES', 'DISABLED'])}{localized('rightsDescription')}</>}{kind === 'ASSET' && <>{choice('asset', ['USDT', 'NEX'])}{native('nativeContract', 'EARNINGS_RELEASE')}{localized('availabilityDescription')}</>}{kind === 'SETTLEMENT' && native('nativeContract', 'ORDER_CONTRACT')}{kind === 'STACKING' && ['voucher', 'bundleDiscount', 'existingH8', 'existingReferral'].map(k => choice(k, ['ALLOW', 'DENY']))}{kind === 'REFUND' && <>{native('deviceRecoveryPolicy', 'A2_POLICY')}<Field label="损失责任归属 *"><input value={String(content.lossOwner || '')} onChange={e => patch('lossOwner', e.target.value)}/></Field>{localized('terms')}</>}{kind === 'QUOTE' && <Field label="报价有效期（秒） *"><input type="number" min={1} step={1} value={String(content.ttlSeconds || '')} onChange={e => patch('ttlSeconds', e.target.value ? Number(e.target.value) : undefined)}/></Field>}{kind === 'AUTHORIZATION' && <>{native('nativeContract', 'A2_POLICY')}{choice('separateMakerChecker', ['true', 'false'], true)}</>}</div><Notice title="固定执行边界">沿用已有资金桶、整单钱包退款和原合同；不允许负余额或跨币抵扣。具体内容在批准后才可用于活动。</Notice>{!!audit.error && <ReadError target="批准证据目录" error={audit.error} retry={audit.reload}/>} {!audit.loading && !evidence.length && <Notice title="没有可选择的批准证据" kind="warn">请先通过现有 A2 审批形成可访问依据，再返回配置政策。</Notice>}</Dialog>;
}

export function PromotionPolicyDetails({policy: selected, catalog}: {policy: Policy; catalog: Catalog}) {
    const contractTitle = (reference: NativeRef | null | undefined) => reference ? text(catalog.nativeContracts.find(n => n.reference?.system === reference.system && n.reference.resourceId === reference.resourceId && n.reference.revision === reference.revision && n.reference.contentHash === reference.contentHash)?.title) : '未知';
    return <><Summary rows={[['批准状态', <Tag value={selected.state}/>], ['批准人', selected.approvedBy || '尚未批准'], ['批准依据', selected.approvalRef || '尚未批准']]}/>{Object.entries(selected.content).filter(([k]) => !['executorCode', 'kind', 'approvalCapability', 'publishCapability'].includes(k)).map(([key, value]) => <div className="summary" key={key}><span>{FIELD_LABELS[key] || '合同约束'}</span><b>{typeof value === 'object' && value !== null ? 'zh' in value ? text(value as {
            zh: string;
        }) : 'resourceId' in value ? catalog.nativeContracts.find(n => n.reference?.resourceId === (value as {
            resourceId: string;
        }).resourceId)?.title.zh || '已绑定原合同' : Array.isArray(value) ? value.map(v => VALUE_LABELS[String(v)] || String(v)).join('、') : '已绑定' : typeof value === 'boolean' ? value ? '是' : '否' : VALUE_LABELS[String(value)] || String(value)}</b></div>)}{selected.content.kind === 'DEVICE_RIGHTS' && <><DeviceRightsSummary rights={selected.resolvedDeviceRights}/><Summary rows={[
            ['任务参与依据', contractTitle(selected.resolvedDeviceRights?.taskRule)],
            ['收益执行依据', contractTitle(selected.resolvedDeviceRights?.earningsRule)]
        ]}/></>}</>;
}
export function PromotionRightsDialog({policy, catalog, onClose}: {policy: Policy; catalog: Catalog; onClose: () => void}) { return <Dialog title="赠品权益详情" onClose={onClose}><PromotionPolicyDetails policy={policy} catalog={catalog}/></Dialog>; }
