"use client";
import { useState } from 'react';
import { promotionRead } from '@/lib/admin/promotion-client';
import type { Catalog, Promotion, RewardAdmin, RewardAdminPage, ResolveInput } from '@/lib/admin/promotion-types';
import { Button, Card, ConfirmCommand, DeviceRightsSummary, Dialog, Empty, Field, Loading, Notice, ReadError, Stats, Summary, Table, Tag, text, formatTime, labelState, rewardText, useRead } from './h4-promotion-ui';
const REWARD_STATES = ['PENDING', 'READY', 'PROCESSING', 'ISSUED', 'RETRYABLE_FAILED', 'OUTCOME_UNKNOWN', 'REVERSAL_PENDING', 'REVERSED', 'CANCELLED', 'MANUAL_REVIEW'];
export default function PromotionRewards({ activity, can, onBack }: {
    activity: Promotion;
    catalog: Catalog;
    can: (v: string) => boolean;
    onBack: () => void;
}) {
    const [filter, setFilter] = useState({ orderNo: '', type: '', state: '', beneficiaryId: '' }), [query, setQuery] = useState<Record<string, string | number>>({ activityId: activity.activityId, limit: 20 }), [previous, setPrevious] = useState<Array<Record<string, string | number>>>([]), [selected, setSelected] = useState<string | null>(null);
    const list = useRead(() => promotionRead<RewardAdminPage>('/promotion-rewards', query), [JSON.stringify(query)]), impact = activity.impact;
    return <><Stats items={[['活动已确认发放', impact.issued, '资金或设备真实回执'], ['活动待发 / 处理中', impact.pendingRewards, '等待原义务处理'], ['活动需恢复或核账', impact.failedRewards + impact.unknownRewards, '失败与结果未知'], ['活动冲正 / 人工审阅', impact.reversingRewards + impact.manualReviewRewards, '保留原承诺与证据']]}/><Card title="奖励明细" action={<Button onClick={onBack}>返回活动</Button>}><form className="filter" onSubmit={e => { e.preventDefault(); setPrevious([]); setQuery({ activityId: activity.activityId, limit: 20, ...filter }); }}><Field label="订单"><input value={filter.orderNo} onChange={e => setFilter({ ...filter, orderNo: e.target.value })}/></Field><Field label="资产类型"><select value={filter.type} onChange={e => setFilter({ ...filter, type: e.target.value })}><option value="">全部类型</option><option value="DEVICE">设备赠礼</option><option value="USDT">USDT</option><option value="NEX">NEX</option></select></Field><Field label="受益账户"><input type="number" min={1} value={filter.beneficiaryId} onChange={e => setFilter({ ...filter, beneficiaryId: e.target.value })}/></Field><Field label="发放状态"><select value={filter.state} onChange={e => setFilter({ ...filter, state: e.target.value })}><option value="">全部状态</option>{REWARD_STATES.map(v => <option key={v} value={v}>{labelState(v)}</option>)}</select></Field><Button kind="primary" type="submit">查询</Button></form>{list.loading ? <Loading /> : list.error ? <ReadError target="奖励台账" error={list.error} retry={list.reload}/> : !list.data?.items.length ? <Empty title="没有符合条件的奖励">保留当前筛选，可调整条件后重新查询。</Empty> : <Table headers={['订单 / 奖励项', '受益人', '原承诺', '状态', '回执 / 依据', '操作']} rows={list.data.items.map(r => [<>{r.orderNo}<small>购买行 {r.orderLineId} · 第 {r.unitSeq} 组</small></>, <>{labelState(r.beneficiaryRole)}<small>{r.beneficiaryId}</small></>, rewardText(r.reward, r.disclosure.deviceName), <Tag value={r.state}/>, r.assetReceipt ? <>{r.assetReceipt.earningsEntryNo || r.assetReceipt.instanceNos.join('、')}<small>{formatTime(r.assetReceipt.issuedAt)}</small></> : '暂无确认回执', <div className="actions"><Button kind="link" onClick={() => setSelected(r.obligationId)}>查看与处置</Button><Button kind="link" onClick={() => { setFilter({ ...filter, orderNo: r.orderNo }); setQuery({ orderNo: r.orderNo, limit: 20 }); setPrevious([]); }}>整单奖励</Button></div>])}/>}{list.data && !list.loading && <div className="pagination"><span>共 {list.data.total} 项 · 读取时刻 {formatTime(list.data.asOf)}</span><div className="actions"><Button disabled={!previous.length} onClick={() => { setQuery(previous.at(-1)!); setPrevious(previous.slice(0, -1)); }}>上一页</Button><Button disabled={!list.data.hasMore} onClick={() => { setPrevious([...previous, query]); setQuery({ ...query, cursor: list.data!.nextCursor! }); }}>下一页</Button></div></div>}</Card><Notice title="有依据的单项处置">结果未知先核账；只恢复原义务。取消、冲正需要关联且已确认的退款或批准依据，活动结束本身不构成依据。</Notice>{selected && <RewardDetail id={selected} can={can} onClose={() => setSelected(null)} onChanged={list.reload}/>}</>;
}
function RewardDetail({ id, can, onClose, onChanged }: {
    id: string;
    can: (v: string) => boolean;
    onClose: () => void;
    onChanged: () => void;
}) {
    const row = useRead(() => promotionRead<RewardAdmin>(`/promotion-rewards/${encodeURIComponent(id)}`), [id]), [action, setAction] = useState<string | null>(null), [decision, setDecision] = useState<ResolveInput['decision']>('KEEP_MANUAL_REVIEW'), [basisChoice, setBasisChoice] = useState('0');
    const r = row.data, labels: Record<string, string> = { retry: '重试原奖励项', reconcile: '核查原结果', cancel: '取消原奖励项', reverse: '发起冲正', resolve: '异常审阅' };
    const options = r?.dispositionOptions.filter(o => o.action === action?.toUpperCase()) || [];
    if (action && r)
        return <ConfirmCommand writeAllowed={can('growth_promotion_reward_'+action) && !row.loading && !row.error} title={labels[action]} intent={{ operation: `${action}Reward`, targetId: r.obligationId, path: `/promotion-rewards/${encodeURIComponent(r.obligationId)}/${action}`, method: 'POST' }} body={{ expectedRevision: r.revision, evidenceRefs: [], ...(action === 'resolve' ? { decision } : ['cancel', 'reverse'].includes(action) ? { basis: options[Number(basisChoice)]?.basis } : {}) }} requireEvidence={['cancel', 'reverse', 'resolve'].includes(action)} onClose={() => setAction(null)} onSuccess={async () => { await promotionRead<RewardAdmin>(`/promotion-rewards/${encodeURIComponent(r.obligationId)}`); setAction(null); row.reload(); onChanged(); }}><Summary rows={[['原订单', r.orderNo], ['受益人', `${labelState(r.beneficiaryRole)} · ${r.beneficiaryId}`], ['原奖励', rewardText(r.reward, r.disclosure.deviceName)], ['当前状态', labelState(r.state)]]}/><Notice title="只处理原奖励义务">不改变受益人、金额、币种或奖励身份；失败后保留原输入，未知结果先回查。</Notice>{['cancel', 'reverse'].includes(action) && <Field label="已确认的处置依据"><select value={basisChoice} onChange={e => setBasisChoice(e.target.value)}>{options.map((o, i) => <option key={i} value={i}>{o.label.zh}</option>)}</select></Field>}{action === 'resolve' && <Field label="依据证据选择后续处理"><select value={decision} onChange={e => setDecision(e.target.value as ResolveInput['decision'])}><option value="KEEP_MANUAL_REVIEW">证据不足，继续人工审阅</option><option value="CONFIRM_ISSUED">已有真实回执，核验已发放</option><option value="CONFIRM_NOT_ISSUED">证据确认未发，恢复原义务</option><option value="CONFIRM_REVERSED">已有真实追回凭证，核验冲正</option></select></Field>}</ConfirmCommand>;
    return <Dialog title="原奖励承诺与真实回执" wide onClose={onClose}>{row.loading ? <Loading /> : row.error ? <ReadError target="原奖励承诺与回执" error={row.error} retry={row.reload}/> : r && <><Summary rows={[['原订单', r.orderNo], ['原活动版本', `v${r.version}`], ['受益人', `${labelState(r.beneficiaryRole)} · ${r.beneficiaryId}`], ['原承诺', rewardText(r.reward, r.disclosure.deviceName)], ['当前状态', <Tag value={r.state}/>], ['资金凭证', r.assetReceipt?.ledgerBizNo || '暂无'], ['原收益条目', r.assetReceipt?.earningsEntryNo || '暂无'], ['真实设备', r.assetReceipt?.instanceNos.join('、') || '暂无'], ['已追回', r.recoveredAmount ?? '尚无追回凭证'], ['未结追回', r.recoveryOutstanding ?? '尚无追回结论']]}/><section className="form-section"><h3>原权益与售后说明</h3><Summary rows={[['公开标题', text(r.disclosure.title)], ['活动规则', text(r.disclosure.terms)], ['资产或设备权益', text(r.disclosure.benefitDescription)], ['售后处理', text(r.disclosure.refundTerms)]]}/>{r.disclosure.deviceRights && <DeviceRightsSummary rights={r.disclosure.deviceRights}/>}</section><div className="actions" style={{ marginTop: 16 }}><Button disabled={!can('growth_promotion_reward_retry') || r.state !== 'RETRYABLE_FAILED' || r.refundHold} onClick={() => setAction('retry')}>重试原奖励项</Button><Button disabled={!can('growth_promotion_reward_reconcile') || !['PENDING','READY','PROCESSING','RETRYABLE_FAILED','OUTCOME_UNKNOWN','ISSUED'].includes(r.state)} onClick={() => setAction('reconcile')}>核查原结果</Button><Button disabled={!can('growth_promotion_reward_cancel') || !r.dispositionOptions.some(o => o.action === 'CANCEL')} onClick={() => { setBasisChoice('0'); setAction('cancel'); }}>取消原奖励项</Button><Button disabled={!can('growth_promotion_reward_reverse') || !r.dispositionOptions.some(o => o.action === 'REVERSE')} onClick={() => { setBasisChoice('0'); setAction('reverse'); }}>发起冲正</Button><Button disabled={!can('growth_promotion_reward_resolve') || r.state !== 'MANUAL_REVIEW'} onClick={() => setAction('resolve')}>异常审阅</Button></div><p className="help">取消与冲正仅可选择关联的已确认退款或当前批准依据；没有候选依据时不可提交，系统会在执行时重新核验。</p>{r.refundHold && <Notice title="售后处理中" kind="warn">原奖励已挂起，不能再次发放。</Notice>}<Table headers={['原命令', '处理状态', '开始时间', '结束时间']} rows={r.attempts.map(a => [a.commandId, labelState(a.state), formatTime(a.startedAt), formatTime(a.finishedAt)])}/></>}</Dialog>;
}
