export type DomainCode = "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M";

export interface ReplayCommand {
  domain: string;
  op: string;
  params: Record<string, unknown>;
}
export interface LockTarget {
  domain: string;
  type: string;
  id: string;
}
export interface HighOpDef {
  op: string;
  domain: DomainCode;
  action: string;
  amplifies: boolean;
  type: "fund" | "param" | "acct" | "sos";
  gateLabel: string;
  targetType: string; // 锁目标 type
  buildCommand: (ctx: Record<string, unknown>) => ReplayCommand;
  buildTarget: (ctx: Record<string, unknown>) => LockTarget;
  buildTargets?: (ctx: Record<string, unknown>) => LockTarget[]; // 多锁(batch_kill/emergency_block 用)
}

/** 批 0:D2 提现放行/解冻。其余域 HIGH 动作分批补登记。 */
export const HIGH_OPS: HighOpDef[] = [
  {
    op: "d2_withdraw_approve",
    domain: "D",
    action: "放行提现",
    amplifies: true,
    type: "fund",
    gateLabel: "财务 / 超管",
    targetType: "withdrawal",
    buildCommand: (ctx) => ({
      domain: "D",
      op: "d2_withdraw_approve",
      params: { withdrawalNo: ctx.withdrawalNo, action: "APPROVE" },
    }),
    buildTarget: (ctx) => ({ domain: "D", type: "withdrawal", id: String(ctx.withdrawalNo) }),
  },
  {
    op: "d2_withdraw_unfreeze",
    domain: "D",
    action: "解冻提现",
    amplifies: true,
    type: "fund",
    gateLabel: "财务 / 超管",
    targetType: "withdrawal",
    buildCommand: (ctx) => ({
      domain: "D",
      op: "d2_withdraw_unfreeze",
      params: { withdrawalNo: ctx.withdrawalNo, action: "UNFREEZE" },
    }),
    buildTarget: (ctx) => ({ domain: "D", type: "withdrawal", id: String(ctx.withdrawalNo) }),
  },
  // —— A 域账号治理(批 1) ——
  {
    op: "a1_account_create",
    domain: "A",
    action: "新建运营账号",
    amplifies: false,
    type: "acct",
    gateLabel: "超管",
    targetType: "account",
    buildCommand: (ctx) => ({
      domain: "A",
      op: "a1_account_create",
      params: {
        username: ctx.username,
        displayName: ctx.displayName,
        email: ctx.email ?? null,
        role: ctx.role,
        initialPassword: ctx.initialPassword,
      },
    }),
    buildTarget: (ctx) => ({ domain: "A", type: "account", id: String(ctx.username) }),
  },
  {
    op: "a1_account_status_update",
    domain: "A",
    action: "启用/禁用账号",
    amplifies: false,
    type: "acct",
    gateLabel: "超管",
    targetType: "account",
    buildCommand: (ctx) => ({
      domain: "A",
      op: "a1_account_status_update",
      params: { accountId: String(ctx.accountId), status: ctx.status },
    }),
    buildTarget: (ctx) => ({ domain: "A", type: "account", id: String(ctx.accountId) }),
  },
  {
    op: "a1_account_change_role",
    domain: "A",
    action: "变更角色",
    amplifies: false,
    type: "acct",
    gateLabel: "超管",
    targetType: "account",
    buildCommand: (ctx) => ({
      domain: "A",
      op: "a1_account_change_role",
      params: { accountId: String(ctx.accountId), role: ctx.role },
    }),
    buildTarget: (ctx) => ({ domain: "A", type: "account", id: String(ctx.accountId) }),
  },
  {
    op: "a1_account_reset_2fa",
    domain: "A",
    action: "重置双因子",
    amplifies: false,
    type: "acct",
    gateLabel: "超管",
    targetType: "account",
    buildCommand: (ctx) => ({
      domain: "A",
      op: "a1_account_reset_2fa",
      params: { accountId: String(ctx.accountId) },
    }),
    buildTarget: (ctx) => ({ domain: "A", type: "account", id: String(ctx.accountId) }),
  },
  {
    op: "a1_account_delete",
    domain: "A",
    action: "删除账号",
    amplifies: false,
    type: "acct",
    gateLabel: "超管",
    targetType: "account",
    buildCommand: (ctx) => ({
      domain: "A",
      op: "a1_account_delete",
      params: { accountId: String(ctx.accountId) },
    }),
    buildTarget: (ctx) => ({ domain: "A", type: "account", id: String(ctx.accountId) }),
  },
  {
    op: "a1_account_update_profile",
    domain: "A",
    action: "编辑账号资料",
    amplifies: false,
    type: "acct",
    gateLabel: "超管",
    targetType: "account",
    buildCommand: (ctx) => ({
      domain: "A",
      op: "a1_account_update_profile",
      params: {
        accountId: String(ctx.accountId),
        username: ctx.username,
        displayName: ctx.displayName,
        email: ctx.email ?? null,
      },
    }),
    buildTarget: (ctx) => ({ domain: "A", type: "account", id: String(ctx.accountId) }),
  },
  {
    op: "a1_account_force_logout",
    domain: "A",
    action: "强制登出",
    amplifies: false,
    type: "acct",
    gateLabel: "超管",
    targetType: "account",
    buildCommand: (ctx) => ({
      domain: "A",
      op: "a1_account_force_logout",
      params: { accountId: String(ctx.accountId) },
    }),
    buildTarget: (ctx) => ({ domain: "A", type: "account", id: String(ctx.accountId) }),
  },
  {
    op: "a1_security_baseline_update",
    domain: "A",
    action: "调整安全基线",
    amplifies: false,
    type: "param",
    gateLabel: "超管",
    targetType: "baseline",
    buildCommand: (ctx) => ({
      domain: "A",
      op: "a1_security_baseline_update",
      params: { baselineKey: String(ctx.baselineKey), value: String(ctx.value) },
    }),
    buildTarget: (ctx) => ({ domain: "A", type: "baseline", id: String(ctx.baselineKey) }),
  },
  // —— C 域用户操作(批 2) ——
  {
    op: "c4_kyc_status_change",
    domain: "C",
    action: "KYC 状态变更",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "user",
    buildCommand: (ctx) => ({
      domain: "C",
      op: "c4_kyc_status_change",
      params: { userId: Number(ctx.userId), status: ctx.status },
    }),
    buildTarget: (ctx) => ({ domain: "C", type: "user", id: String(ctx.userId) }),
  },
  {
    op: "c5_2fa_disable",
    domain: "C",
    action: "关闭 2FA",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "user",
    buildCommand: (ctx) => ({
      domain: "C",
      op: "c5_2fa_disable",
      params: { userId: Number(ctx.userId) },
    }),
    buildTarget: (ctx) => ({ domain: "C", type: "user", id: String(ctx.userId) }),
  },
  {
    op: "c5_password_reset",
    domain: "C",
    action: "密码重置",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "user",
    buildCommand: (ctx) => ({
      domain: "C",
      op: "c5_password_reset",
      params: { userId: Number(ctx.userId) },
    }),
    buildTarget: (ctx) => ({ domain: "C", type: "user", id: String(ctx.userId) }),
  },
  {
    op: "c5_user_unlock",
    domain: "C",
    action: "解除锁定",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "user",
    buildCommand: (ctx) => ({
      domain: "C",
      op: "c5_user_unlock",
      params: { userId: Number(ctx.userId) },
    }),
    buildTarget: (ctx) => ({ domain: "C", type: "user", id: String(ctx.userId) }),
  },
  {
    op: "c2_account_freeze",
    domain: "C",
    action: "冻结账户",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "user",
    buildCommand: (ctx) => ({
      domain: "C",
      op: "c2_account_freeze",
      params: { userId: Number(ctx.userId), status: "FROZEN" },
    }),
    buildTarget: (ctx) => ({ domain: "C", type: "user", id: String(ctx.userId) }),
  },
  {
    op: "c2_account_unfreeze",
    domain: "C",
    action: "恢复账户",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "user",
    buildCommand: (ctx) => ({
      domain: "C",
      op: "c2_account_unfreeze",
      params: { userId: Number(ctx.userId), status: "ACTIVE" },
    }),
    buildTarget: (ctx) => ({ domain: "C", type: "user", id: String(ctx.userId) }),
  },
  {
    op: "c2_session_revoke_all",
    domain: "C",
    action: "全部踢线",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "user",
    buildCommand: (ctx) => ({
      domain: "C",
      op: "c2_session_revoke_all",
      params: { userId: Number(ctx.userId) },
    }),
    buildTarget: (ctx) => ({ domain: "C", type: "user", id: String(ctx.userId) }),
  },
  {
    op: "c5_session_revoke_one",
    domain: "C",
    action: "踢线(单会话)",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "session",
    buildCommand: (ctx) => ({
      domain: "C",
      op: "c5_session_revoke_one",
      params: { refreshTokenId: String(ctx.refreshTokenId) },
    }),
    buildTarget: (ctx) => ({ domain: "C", type: "session", id: String(ctx.refreshTokenId) }),
  },
  {
    op: "c2_impersonate_terminate",
    domain: "C",
    action: "终止模拟登录",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "impersonation",
    buildCommand: (ctx) => ({
      domain: "C",
      op: "c2_impersonate_terminate",
      params: { sessionNo: String(ctx.sessionNo) },
    }),
    buildTarget: (ctx) => ({ domain: "C", type: "impersonation", id: String(ctx.sessionNo) }),
  },
  {
    op: "c2_impersonate_start",
    domain: "C",
    action: "发起模拟登录",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "user",
    buildCommand: (ctx) => ({
      domain: "C",
      op: "c2_impersonate_start",
      params: { userId: Number(ctx.userId), ttlMinutes: Number(ctx.ttlMinutes ?? 30) },
    }),
    buildTarget: (ctx) => ({ domain: "C", type: "user", id: String(ctx.userId) }),
  },
  {
    op: "c3_adjust_approve",
    domain: "C",
    action: "通过资产调整",
    amplifies: false,
    type: "fund",
    gateLabel: "门槛者",
    targetType: "adjustment",
    buildCommand: (ctx) => ({
      domain: "C",
      op: "c3_adjust_approve",
      params: { adjustmentNo: String(ctx.adjustmentNo) },
    }),
    buildTarget: (ctx) => ({ domain: "C", type: "adjustment", id: String(ctx.adjustmentNo) }),
  },
  {
    op: "c3_adjust_reject",
    domain: "C",
    action: "驳回资产调整",
    amplifies: false,
    type: "fund",
    gateLabel: "门槛者",
    targetType: "adjustment",
    buildCommand: (ctx) => ({
      domain: "C",
      op: "c3_adjust_reject",
      params: { adjustmentNo: String(ctx.adjustmentNo) },
    }),
    buildTarget: (ctx) => ({ domain: "C", type: "adjustment", id: String(ctx.adjustmentNo) }),
  },
  {
    op: "c3_adjust_create",
    domain: "C",
    action: "创建资产调整",
    amplifies: false,
    type: "fund",
    gateLabel: "门槛者",
    targetType: "user",
    buildCommand: (ctx) => ({
      domain: "C",
      op: "c3_adjust_create",
      params: {
        userId: Number(ctx.userId),
        asset: ctx.asset,
        direction: ctx.direction,
        amount: String(ctx.amount),
        referenceType: ctx.referenceType ?? null,
        referenceId: ctx.referenceId ?? null,
      },
    }),
    buildTarget: (ctx) => ({ domain: "C", type: "user", id: String(ctx.userId) }),
  },
  {
    op: "c2_blocklist_upsert",
    domain: "C",
    action: "名单信任/禁入",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "accountlist",
    buildCommand: (ctx) => ({
      domain: "C",
      op: "c2_blocklist_upsert",
      params: { userId: Number(ctx.userId), kind: ctx.kind, expiresAt: ctx.expiresAt ?? null },
    }),
    buildTarget: (ctx) => ({ domain: "C", type: "accountlist", id: String(ctx.userId) }),
  },
  // —— K 域风控(批 3) ——
  {
    op: "k1_cluster_freeze",
    domain: "K",
    action: "批量冻结关联账户",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "cluster",
    buildCommand: (ctx) => ({
      domain: "K",
      op: "k1_cluster_freeze",
      params: { clusterId: String(ctx.clusterId) },
    }),
    buildTarget: (ctx) => ({ domain: "K", type: "cluster", id: String(ctx.clusterId) }),
  },
  {
    op: "k1_cluster_release",
    domain: "K",
    action: "解除误判",
    amplifies: true,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "cluster",
    buildCommand: (ctx) => ({
      domain: "K",
      op: "k1_cluster_release",
      params: { clusterId: String(ctx.clusterId) },
    }),
    buildTarget: (ctx) => ({ domain: "K", type: "cluster", id: String(ctx.clusterId) }),
  },
  {
    op: "k1_cluster_cleared",
    domain: "K",
    action: "判定为正常",
    amplifies: true,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "cluster",
    buildCommand: (ctx) => ({
      domain: "K",
      op: "k1_cluster_cleared",
      params: { clusterId: String(ctx.clusterId) },
    }),
    buildTarget: (ctx) => ({ domain: "K", type: "cluster", id: String(ctx.clusterId) }),
  },
  {
    op: "k1_cluster_flag",
    domain: "K",
    action: "标记可疑账户簇",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "cluster",
    buildCommand: (ctx) => ({
      domain: "K",
      op: "k1_cluster_flag",
      params: { clusterId: String(ctx.clusterId) },
    }),
    buildTarget: (ctx) => ({ domain: "K", type: "cluster", id: String(ctx.clusterId) }),
  },
  {
    op: "k2_row_flag",
    domain: "K",
    action: "标记套利账户",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "arbitrage_row",
    buildCommand: (ctx) => ({
      domain: "K",
      op: "k2_row_flag",
      params: { rowId: String(ctx.rowId) },
    }),
    buildTarget: (ctx) => ({ domain: "K", type: "arbitrage_row", id: String(ctx.rowId) }),
  },
  {
    op: "k2_row_blockgift",
    domain: "K",
    action: "拦截新人礼",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "arbitrage_row",
    buildCommand: (ctx) => ({
      domain: "K",
      op: "k2_row_blockgift",
      params: { rowId: String(ctx.rowId) },
    }),
    buildTarget: (ctx) => ({ domain: "K", type: "arbitrage_row", id: String(ctx.rowId) }),
  },
  {
    op: "k2_row_boardflag",
    domain: "K",
    action: "标记刷榜账户",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "arbitrage_row",
    buildCommand: (ctx) => ({
      domain: "K",
      op: "k2_row_boardflag",
      params: { rowId: String(ctx.rowId) },
    }),
    buildTarget: (ctx) => ({ domain: "K", type: "arbitrage_row", id: String(ctx.rowId) }),
  },
  {
    op: "k2_row_freeze",
    domain: "K",
    action: "联动 K1 批量冻结",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "arbitrage_row",
    buildCommand: (ctx) => ({
      domain: "K",
      op: "k2_row_freeze",
      params: { rowId: String(ctx.rowId) },
    }),
    buildTarget: (ctx) => ({ domain: "K", type: "arbitrage_row", id: String(ctx.rowId) }),
  },
  {
    op: "k3_rule_create",
    domain: "K",
    action: "新建提现风控规则",
    amplifies: false,
    type: "param",
    gateLabel: "门槛者",
    targetType: "rule",
    buildCommand: (ctx) => ({
      domain: "K",
      op: "k3_rule_create",
      params: {
        dimension: ctx.dimension,
        conditionText: ctx.conditionText,
        action: ctx.action,
      },
    }),
    // 语义键:与后端 createWithdrawRule 归一化后的 dimension+":"+condition 一致
    // (前端 businessForm 产出的 condition 已是归一化格式)
    buildTarget: (ctx) => ({
      domain: "K",
      type: "rule",
      id: String(ctx.dimension) + ":" + String(ctx.conditionText),
    }),
  },
  {
    op: "k3_rule_toggle",
    domain: "K",
    action: "启用/停用规则",
    amplifies: false,
    type: "param",
    gateLabel: "门槛者",
    targetType: "rule",
    buildCommand: (ctx) => ({
      domain: "K",
      op: "k3_rule_toggle",
      params: { ruleId: String(ctx.ruleId), state: String(ctx.state) },
    }),
    buildTarget: (ctx) => ({ domain: "K", type: "rule", id: String(ctx.ruleId) }),
  },
  {
    op: "k3_rule_archive",
    domain: "K",
    action: "归档规则",
    amplifies: false,
    type: "param",
    gateLabel: "门槛者",
    targetType: "rule",
    buildCommand: (ctx) => ({
      domain: "K",
      op: "k3_rule_archive",
      params: { ruleId: String(ctx.ruleId) },
    }),
    buildTarget: (ctx) => ({ domain: "K", type: "rule", id: String(ctx.ruleId) }),
  },
  {
    op: "k4_user_override",
    domain: "K",
    action: "人工覆盖评分",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "score_user",
    buildCommand: (ctx) => ({
      domain: "K",
      op: "k4_user_override",
      params: { userNo: String(ctx.userNo), score: Number(ctx.score) },
    }),
    buildTarget: (ctx) => ({ domain: "K", type: "score_user", id: String(ctx.userNo) }),
  },
  {
    op: "k4_user_recompute",
    domain: "K",
    action: "重算回模型分",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "score_user",
    buildCommand: (ctx) => ({
      domain: "K",
      op: "k4_user_recompute",
      params: { userNo: String(ctx.userNo) },
    }),
    buildTarget: (ctx) => ({ domain: "K", type: "score_user", id: String(ctx.userNo) }),
  },
  {
    op: "k5_ticket_pass",
    domain: "K",
    action: "通过 KYC 复审",
    amplifies: true,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "ticket",
    buildCommand: (ctx) => ({
      domain: "K",
      op: "k5_ticket_pass",
      params: { ticketId: String(ctx.ticketId) },
    }),
    buildTarget: (ctx) => ({ domain: "K", type: "ticket", id: String(ctx.ticketId) }),
  },
  {
    op: "k5_ticket_reject",
    domain: "K",
    action: "驳回 KYC 复审",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "ticket",
    buildCommand: (ctx) => ({
      domain: "K",
      op: "k5_ticket_reject",
      params: { ticketId: String(ctx.ticketId) },
    }),
    buildTarget: (ctx) => ({ domain: "K", type: "ticket", id: String(ctx.ticketId) }),
  },
  {
    op: "k5_ticket_manual",
    domain: "K",
    action: "手动补触发复审",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "user",
    buildCommand: (ctx) => ({
      domain: "K",
      op: "k5_ticket_manual",
      params: { userNo: String(ctx.userNo) },
    }),
    buildTarget: (ctx) => ({ domain: "K", type: "user", id: String(ctx.userNo) }),
  },
  // —— J 域紧急与合规控制(批 4) ——
  {
    op: "j1_gate_kill",
    domain: "J",
    action: "熔断功能闸",
    amplifies: false,
    type: "sos",
    gateLabel: "门槛者",
    targetType: "gate",
    buildCommand: (ctx) => ({
      domain: "J",
      op: "j1_gate_kill",
      params: { gateKey: String(ctx.gateKey) },
    }),
    buildTarget: (ctx) => ({ domain: "J", type: "gate", id: String(ctx.gateKey) }),
  },
  {
    op: "j1_gate_resume",
    domain: "J",
    action: "恢复功能闸",
    amplifies: true,
    type: "sos",
    gateLabel: "门槛者",
    targetType: "gate",
    buildCommand: (ctx) => ({
      domain: "J",
      op: "j1_gate_resume",
      params: { gateKey: String(ctx.gateKey) },
    }),
    buildTarget: (ctx) => ({ domain: "J", type: "gate", id: String(ctx.gateKey) }),
  },
  {
    op: "j1_batch_kill",
    domain: "J",
    action: "应急批量熔断",
    amplifies: false,
    type: "sos",
    gateLabel: "门槛者",
    targetType: "gate",
    buildCommand: (ctx) => ({
      domain: "J",
      op: "j1_batch_kill",
      params: { keys: (ctx.keys as string[]) ?? [] },
    }),
    // 多锁:per-gate 一锁(对齐 spec §4.7 业务对象单位)
    buildTargets: (ctx) =>
      ((ctx.keys as string[]) ?? []).map((k) => ({ domain: "J", type: "gate", id: String(k) })),
    // 单锁兜底(若 usePropose 未支持 targets,用首个 gate;正常路径走 buildTargets)
    buildTarget: (ctx) => ({ domain: "J", type: "gate", id: String(((ctx.keys as string[]) ?? [""])[0]) }),
  },
  {
    op: "j2_country_manage",
    domain: "J",
    action: "国家管控",
    amplifies: false, // 默认封锁不放大;前端调用时按 status=allowed 覆盖为 true(解除方向)
    type: "param",
    gateLabel: "门槛者",
    targetType: "country",
    buildCommand: (ctx) => ({
      domain: "J",
      op: "j2_country_manage",
      params: { countryCode: String(ctx.countryCode), status: String(ctx.status) },
    }),
    buildTarget: (ctx) => ({ domain: "J", type: "country", id: String(ctx.countryCode) }),
  },
  {
    op: "j2_emergency_block",
    domain: "J",
    action: "应急批量封锁",
    amplifies: false,
    type: "sos",
    gateLabel: "门槛者",
    targetType: "country",
    buildCommand: (ctx) => ({
      domain: "J",
      op: "j2_emergency_block",
      params: { countries: (ctx.countries as string[]) ?? [] },
    }),
    buildTargets: (ctx) =>
      ((ctx.countries as string[]) ?? []).map((c) => ({ domain: "J", type: "country", id: String(c) })),
    buildTarget: (ctx) => ({ domain: "J", type: "country", id: String(((ctx.countries as string[]) ?? [""])[0]) }),
  },
  {
    op: "j3_alert_config",
    domain: "J",
    action: "篡改告警阈值配置",
    amplifies: false,
    type: "param",
    gateLabel: "门槛者",
    targetType: "alert_config",
    buildCommand: (ctx) => ({
      domain: "J",
      op: "j3_alert_config",
      params: { threshold: Number(ctx.threshold), feedK4: Boolean(ctx.feedK4) },
    }),
    buildTarget: () => ({ domain: "J", type: "alert_config", id: "default" }),
  },
  {
    op: "j4_playbook_execute",
    domain: "J",
    action: "执行应急剧本",
    amplifies: false,
    type: "sos",
    gateLabel: "门槛者",
    targetType: "playbook",
    buildCommand: (ctx) => ({
      domain: "J",
      op: "j4_playbook_execute",
      params: { code: String(ctx.code), emergency: Boolean(ctx.emergency ?? false) },
    }),
    buildTarget: (ctx) => ({ domain: "J", type: "playbook", id: String(ctx.code) }),
  },
  {
    op: "j4_playbook_rollback",
    domain: "J",
    action: "回滚剧本执行",
    amplifies: false,
    type: "sos",
    gateLabel: "门槛者",
    targetType: "playbook_execution",
    buildCommand: (ctx) => ({
      domain: "J",
      op: "j4_playbook_rollback",
      params: { code: String(ctx.code), executionId: String(ctx.executionId), emergency: false },
    }),
    buildTarget: (ctx) => ({ domain: "J", type: "playbook_execution", id: String(ctx.executionId) }),
  },
  // —— G 域 NEX 市场(批 5) ——
  {
    op: "g1_staking_pool_param",
    domain: "G",
    action: "质押池参数调整",
    amplifies: true, // 默认 apy↑/penalty↓ 放大;前端 adjMin 中性可覆盖
    type: "param",
    gateLabel: "门槛者",
    targetType: "staking_pool",
    buildCommand: (ctx) => ({ domain: "G", op: "g1_staking_pool_param",
      params: { tierKey: String(ctx.tierKey), paramKey: String(ctx.paramKey), value: String(ctx.value) } }),
    buildTarget: (ctx) => ({ domain: "G", type: "staking_pool", id: String(ctx.tierKey) }),
  },
  {
    op: "g1_staking_pool_sale_status",
    domain: "G",
    action: "质押池开/停售",
    amplifies: false, // 默认停售不放大;前端按 enabled=true(开售)覆盖为 true(放大方向)
    type: "fund",
    gateLabel: "门槛者",
    targetType: "staking_pool",
    buildCommand: (ctx) => ({ domain: "G", op: "g1_staking_pool_sale_status",
      params: { tierKey: String(ctx.tierKey), enabled: Boolean(ctx.enabled) } }),
    buildTarget: (ctx) => ({ domain: "G", type: "staking_pool", id: String(ctx.tierKey) }),
  },
  {
    op: "g1_staking_pool_kill_status",
    domain: "G",
    action: "质押池熔断/解除",
    amplifies: false, // 默认熔断不放大;前端按 killed=false(解除)覆盖为 true(放大方向)
    type: "sos",
    gateLabel: "门槛者",
    targetType: "staking_pool",
    buildCommand: (ctx) => ({ domain: "G", op: "g1_staking_pool_kill_status",
      params: { tierKey: String(ctx.tierKey), killed: Boolean(ctx.killed) } }),
    buildTarget: (ctx) => ({ domain: "G", type: "staking_pool", id: String(ctx.tierKey) }),
  },
  {
    op: "g2_exchange_param",
    domain: "G",
    action: "兑换参数调整",
    amplifies: true, // 默认 cap↑/fee↓ 放大
    type: "fund",
    gateLabel: "门槛者",
    targetType: "exchange_param",
    buildCommand: (ctx) => ({ domain: "G", op: "g2_exchange_param",
      params: { paramKey: String(ctx.paramKey), value: String(ctx.value) } }),
    buildTarget: (ctx) => ({ domain: "G", type: "exchange_param", id: String(ctx.paramKey) }),
  },
  {
    op: "g2_exchange_swap_status",
    domain: "G",
    action: "兑换交易熔断/恢复",
    amplifies: false, // 默认熔断不放大;前端按 enabled=true(恢复)覆盖为 true(放大方向)
    type: "sos",
    gateLabel: "门槛者",
    targetType: "exchange_swap",
    buildCommand: (ctx) => ({ domain: "G", op: "g2_exchange_swap_status",
      params: { enabled: Boolean(ctx.enabled) } }),
    buildTarget: () => ({ domain: "G", type: "exchange_swap", id: "exchange" }),
  },
  {
    op: "g2_exchange_cancel_queue",
    domain: "G",
    action: "取消排队兑换单",
    amplifies: false, // 取消=退款收缩
    type: "fund",
    gateLabel: "门槛者",
    targetType: "exchange_order",
    buildCommand: (ctx) => ({ domain: "G", op: "g2_exchange_cancel_queue",
      params: { exchangeNo: String(ctx.exchangeNo) } }),
    buildTarget: (ctx) => ({ domain: "G", type: "exchange_order", id: String(ctx.exchangeNo) }),
  },
  {
    op: "g2_exchange_trigger_kyc_review",
    domain: "G",
    action: "触发兑换合规复审",
    amplifies: false, // 开合规拦截
    type: "fund",
    gateLabel: "门槛者",
    targetType: "exchange_order",
    buildCommand: (ctx) => ({ domain: "G", op: "g2_exchange_trigger_kyc_review",
      params: { exchangeNo: String(ctx.exchangeNo) } }),
    buildTarget: (ctx) => ({ domain: "G", type: "exchange_order", id: String(ctx.exchangeNo) }),
  },
  {
    op: "g3_curve_update",
    domain: "G",
    action: "更新周曲线",
    amplifies: true, // 默认 peak↑ 放大负债
    type: "fund",
    gateLabel: "门槛者",
    targetType: "nex_market_curve",
    buildCommand: (ctx) => ({ domain: "G", op: "g3_curve_update",
      params: { frames: (ctx.frames as Array<Record<string, unknown>>) ?? [] } }),
    buildTarget: () => ({ domain: "G", type: "nex_market_curve", id: "weekly" }),
  },
  {
    op: "g3_curve_advance",
    domain: "G",
    action: "推进曲线帧",
    amplifies: true, // 推更高价帧
    type: "param",
    gateLabel: "门槛者",
    targetType: "nex_market_curve",
    buildCommand: () => ({ domain: "G", op: "g3_curve_advance", params: {} }),
    buildTarget: () => ({ domain: "G", type: "nex_market_curve", id: "weekly" }),
  },
  {
    op: "g3_curve_control",
    domain: "G",
    action: "调整曲线引擎控制",
    amplifies: false, // 引擎编排非直接资金
    type: "param",
    gateLabel: "门槛者",
    targetType: "nex_market_control",
    buildCommand: (ctx) => ({ domain: "G", op: "g3_curve_control",
      params: { controlKey: String(ctx.controlKey), value: String(ctx.value) } }),
    buildTarget: (ctx) => ({ domain: "G", type: "nex_market_control", id: String(ctx.controlKey) }),
  },
  {
    op: "g3_override",
    domain: "G",
    action: "覆盖市场即时状态",
    amplifies: true, // 默认 currentPrice↑/resume 放大;前端 paused→pause 覆盖为 false(收缩方向)
    type: "fund",
    gateLabel: "门槛者",
    targetType: "nex_market_override",
    buildCommand: (ctx) => ({ domain: "G", op: "g3_override",
      params: { overrideKey: String(ctx.overrideKey), value: String(ctx.value) } }),
    buildTarget: (ctx) => ({ domain: "G", type: "nex_market_override", id: String(ctx.overrideKey) }),
  },
  {
    op: "g4_genesis_param",
    domain: "G",
    action: "创世参数调整",
    amplifies: true, // 默认 supply↑/price↑/dividend↑ 放大
    type: "fund",
    gateLabel: "门槛者",
    targetType: "genesis_param",
    buildCommand: (ctx) => ({ domain: "G", op: "g4_genesis_param",
      params: { paramKey: String(ctx.paramKey), value: String(ctx.value) } }),
    buildTarget: (ctx) => ({ domain: "G", type: "genesis_param", id: String(ctx.paramKey) }),
  },
  {
    op: "g4_genesis_market_status",
    domain: "G",
    action: "创世市场开/关",
    amplifies: false, // 默认关市不放大;前端按 enabled=true(开市)覆盖为 true(放大方向)
    type: "sos",
    gateLabel: "门槛者",
    targetType: "genesis_market",
    buildCommand: (ctx) => ({ domain: "G", op: "g4_genesis_market_status",
      params: { enabled: Boolean(ctx.enabled) } }),
    buildTarget: () => ({ domain: "G", type: "genesis_market", id: "genesis" }),
  },
  {
    op: "g4_genesis_rerun_dividend",
    domain: "G",
    action: "重跑创世排放批次",
    amplifies: true, // 硬=true,直接资金 postLedgerEntry
    type: "fund",
    gateLabel: "门槛者",
    targetType: "genesis_dividend_batch",
    buildCommand: (ctx) => ({ domain: "G", op: "g4_genesis_rerun_dividend",
      params: { batchNo: String(ctx.batchNo) } }),
    buildTarget: (ctx) => ({ domain: "G", type: "genesis_dividend_batch", id: String(ctx.batchNo) }),
  },
  {
    op: "g7_repurchase_param",
    domain: "G",
    action: "回购参数调整",
    amplifies: true, // 默认 apy↑/nurture↑ 放大
    type: "fund",
    gateLabel: "门槛者",
    targetType: "repurchase_param",
    buildCommand: (ctx) => ({ domain: "G", op: "g7_repurchase_param",
      params: { paramKey: String(ctx.paramKey), value: String(ctx.value) } }),
    buildTarget: (ctx) => ({ domain: "G", type: "repurchase_param", id: String(ctx.paramKey) }),
  },
  // —— E 域设备(批 6) ——
  // E1 目录(e1 sku/review/phase/gate)
  {
    op: "e1_sku_create",
    domain: "E",
    action: "新建设备 SKU",
    amplifies: false,
    type: "param",
    gateLabel: "门槛者",
    targetType: "device_sku",
    // 全 DeviceSkuUpsertRequest 透传:后端 buildSkuUpsertRequest 按 key 从 params 读取(37 字段)
    buildCommand: (ctx) => ({ domain: "E", op: "e1_sku_create", params: { ...ctx } }),
    buildTarget: (ctx) => ({ domain: "E", type: "device_sku", id: String(ctx.skuId) }),
  },
  {
    op: "e1_sku_update",
    domain: "E",
    action: "更新设备 SKU",
    amplifies: false,
    type: "param",
    gateLabel: "门槛者",
    targetType: "device_sku",
    // 全 DeviceSkuUpsertRequest 透传:后端 buildSkuUpsertRequest 按 key 从 params 读取(37 字段)
    buildCommand: (ctx) => ({ domain: "E", op: "e1_sku_update", params: { ...ctx } }),
    buildTarget: (ctx) => ({ domain: "E", type: "device_sku", id: String(ctx.skuId) }),
  },
  {
    op: "e1_sku_status",
    domain: "E",
    action: "调整 SKU 上下架",
    amplifies: false,
    type: "param",
    gateLabel: "门槛者",
    targetType: "device_sku",
    buildCommand: (ctx) => ({ domain: "E", op: "e1_sku_status",
      params: { skuId: String(ctx.skuId), status: String(ctx.status) } }),
    buildTarget: (ctx) => ({ domain: "E", type: "device_sku", id: String(ctx.skuId) }),
  },
  {
    op: "e1_sku_delete",
    domain: "E",
    action: "删除设备 SKU",
    amplifies: false,
    type: "sos",
    gateLabel: "门槛者",
    targetType: "device_sku",
    buildCommand: (ctx) => ({ domain: "E", op: "e1_sku_delete",
      params: { skuId: String(ctx.skuId) } }),
    buildTarget: (ctx) => ({ domain: "E", type: "device_sku", id: String(ctx.skuId) }),
  },
  {
    op: "e1_review_create",
    domain: "E",
    action: "新建设备评测",
    amplifies: false,
    type: "param",
    gateLabel: "门槛者",
    targetType: "device_review",
    buildCommand: (ctx) => ({ domain: "E", op: "e1_review_create",
      params: { skuId: String(ctx.skuId), author: String(ctx.author), rating: ctx.rating,
        content: String(ctx.content), dateText: String(ctx.dateText), status: String(ctx.status) } }),
    buildTarget: (ctx) => ({ domain: "E", type: "device_review", id: String(ctx.reviewId) }),
  },
  {
    op: "e1_review_update",
    domain: "E",
    action: "更新设备评测",
    amplifies: false,
    type: "param",
    gateLabel: "门槛者",
    targetType: "device_review",
    buildCommand: (ctx) => ({ domain: "E", op: "e1_review_update",
      params: { reviewId: String(ctx.reviewId), skuId: String(ctx.skuId), author: String(ctx.author),
        rating: ctx.rating, content: String(ctx.content), dateText: String(ctx.dateText), status: String(ctx.status) } }),
    buildTarget: (ctx) => ({ domain: "E", type: "device_review", id: String(ctx.reviewId) }),
  },
  {
    op: "e1_review_status",
    domain: "E",
    action: "调整评测状态",
    amplifies: false,
    type: "param",
    gateLabel: "门槛者",
    targetType: "device_review",
    buildCommand: (ctx) => ({ domain: "E", op: "e1_review_status",
      params: { reviewId: String(ctx.reviewId), status: String(ctx.status) } }),
    buildTarget: (ctx) => ({ domain: "E", type: "device_review", id: String(ctx.reviewId) }),
  },
  {
    op: "e1_review_delete",
    domain: "E",
    action: "删除设备评测",
    amplifies: false,
    type: "sos",
    gateLabel: "门槛者",
    targetType: "device_review",
    buildCommand: (ctx) => ({ domain: "E", op: "e1_review_delete",
      params: { reviewId: String(ctx.reviewId) } }),
    buildTarget: (ctx) => ({ domain: "E", type: "device_review", id: String(ctx.reviewId) }),
  },
  {
    op: "e1_phase_create",
    domain: "E",
    action: "新建生命周期阶段",
    amplifies: false,
    type: "param",
    gateLabel: "门槛者",
    targetType: "device_phase",
    buildCommand: (ctx) => ({ domain: "E", op: "e1_phase_create",
      params: { phaseId: String(ctx.phaseId), label: String(ctx.label), meta: String(ctx.meta),
        skus: String(ctx.skus), sortOrder: ctx.sortOrder, status: String(ctx.status) } }),
    buildTarget: (ctx) => ({ domain: "E", type: "device_phase", id: String(ctx.label) }),
  },
  {
    op: "e1_phase_patch",
    domain: "E",
    action: "更新生命周期阶段",
    amplifies: false,
    type: "param",
    gateLabel: "门槛者",
    targetType: "device_phase",
    buildCommand: (ctx) => ({ domain: "E", op: "e1_phase_patch",
      params: { phaseId: String(ctx.phaseId), label: String(ctx.label), meta: String(ctx.meta),
        skus: String(ctx.skus), sortOrder: ctx.sortOrder, status: String(ctx.status) } }),
    buildTarget: (ctx) => ({ domain: "E", type: "device_phase", id: String(ctx.phaseId) }),
  },
  {
    op: "e1_phase_archive",
    domain: "E",
    action: "归档生命周期阶段",
    amplifies: false,
    type: "sos",
    gateLabel: "门槛者",
    targetType: "device_phase",
    buildCommand: (ctx) => ({ domain: "E", op: "e1_phase_archive",
      params: { phaseId: String(ctx.phaseId) } }),
    buildTarget: (ctx) => ({ domain: "E", type: "device_phase", id: String(ctx.phaseId) }),
  },
  {
    op: "e1_phase_current",
    domain: "E",
    action: "设置当前生命周期阶段",
    amplifies: false,
    type: "param",
    gateLabel: "门槛者",
    targetType: "device_phase",
    buildCommand: (ctx) => ({ domain: "E", op: "e1_phase_current",
      params: { phaseId: String(ctx.phaseId) } }),
    buildTarget: (ctx) => ({ domain: "E", type: "device_phase", id: String(ctx.phaseId) }),
  },
  {
    op: "e1_gate_create",
    domain: "E",
    action: "新建换代门槛",
    amplifies: false,
    type: "param",
    gateLabel: "门槛者",
    targetType: "device_generation_gate",
    buildCommand: (ctx) => ({ domain: "E", op: "e1_gate_create",
      params: { skuId: String(ctx.skuId), name: String(ctx.name), releaseMonth: ctx.releaseMonth,
        phase: String(ctx.phase), discount: ctx.discount, eligibility: Boolean(ctx.eligibility),
        phaseOffset: ctx.phaseOffset, forceUnlock: Boolean(ctx.forceUnlock), status: String(ctx.status) } }),
    buildTarget: (ctx) => ({ domain: "E", type: "device_generation_gate", id: String(ctx.skuId) }),
  },
  {
    op: "e1_gate_patch",
    domain: "E",
    action: "更新换代门槛",
    amplifies: false,
    type: "param",
    gateLabel: "门槛者",
    targetType: "device_generation_gate",
    buildCommand: (ctx) => ({ domain: "E", op: "e1_gate_patch",
      params: { skuId: String(ctx.skuId), name: String(ctx.name), releaseMonth: ctx.releaseMonth,
        phase: String(ctx.phase), discount: ctx.discount, eligibility: Boolean(ctx.eligibility),
        phaseOffset: ctx.phaseOffset, forceUnlock: Boolean(ctx.forceUnlock), status: String(ctx.status) } }),
    buildTarget: (ctx) => ({ domain: "E", type: "device_generation_gate", id: String(ctx.skuId) }),
  },
  {
    op: "e1_gate_archive",
    domain: "E",
    action: "归档换代门槛",
    amplifies: false,
    type: "sos",
    gateLabel: "门槛者",
    targetType: "device_generation_gate",
    buildCommand: (ctx) => ({ domain: "E", op: "e1_gate_archive",
      params: { skuId: String(ctx.skuId) } }),
    buildTarget: (ctx) => ({ domain: "E", type: "device_generation_gate", id: String(ctx.skuId) }),
  },
  {
    op: "e1_gate_field",
    domain: "E",
    action: "调整换代门槛字段",
    amplifies: false,
    type: "param",
    gateLabel: "门槛者",
    targetType: "device_generation_gate",
    // 锁 id 取复合 key:后端 updateE1GenerationGate 经 normalizeE1GateKey 解析为 key[0](generationId)再查锁
    buildCommand: (ctx) => ({ domain: "E", op: "e1_gate_field",
      params: { key: String(ctx.key), value: String(ctx.value) } }),
    buildTarget: (ctx) => ({ domain: "E", type: "device_generation_gate", id: String(ctx.key) }),
  },
  // E2 收益(e2 phone_tier/task)
  {
    op: "e2_phone_tier",
    domain: "E",
    action: "调整手机 tier 日产奖励",
    amplifies: true, // 日产发放率↑放大负债
    type: "fund",
    gateLabel: "门槛者",
    targetType: "phone_tier",
    buildCommand: (ctx) => ({ domain: "E", op: "e2_phone_tier",
      params: { tier: ctx.tier, dailyUsdt: ctx.dailyUsdt, dailyNex: ctx.dailyNex } }),
    buildTarget: (ctx) => ({ domain: "E", type: "phone_tier", id: String(ctx.tier) }),
  },
  {
    op: "e2_task_create",
    domain: "E",
    action: "新建设备任务",
    amplifies: false,
    type: "param",
    gateLabel: "门槛者",
    targetType: "device_task",
    buildCommand: (ctx) => ({ domain: "E", op: "e2_task_create",
      params: { name: String(ctx.name), price: ctx.price, unit: String(ctx.unit),
        requirement: String(ctx.requirement), saturation: ctx.saturation, status: String(ctx.status),
        taskClass: String(ctx.taskClass), model: String(ctx.model), minReward: ctx.minReward,
        maxReward: ctx.maxReward, minVram: String(ctx.minVram), killInit: String(ctx.killInit) } }),
    buildTarget: (ctx) => ({ domain: "E", type: "device_task", id: String(ctx.taskId) }),
  },
  {
    op: "e2_task_update",
    domain: "E",
    action: "更新设备任务",
    amplifies: false,
    type: "param",
    gateLabel: "门槛者",
    targetType: "device_task",
    buildCommand: (ctx) => ({ domain: "E", op: "e2_task_update",
      params: { taskId: String(ctx.taskId), name: String(ctx.name), price: ctx.price, unit: String(ctx.unit),
        requirement: String(ctx.requirement), saturation: ctx.saturation, status: String(ctx.status),
        taskClass: String(ctx.taskClass), model: String(ctx.model), minReward: ctx.minReward,
        maxReward: ctx.maxReward, minVram: String(ctx.minVram), killInit: String(ctx.killInit) } }),
    buildTarget: (ctx) => ({ domain: "E", type: "device_task", id: String(ctx.taskId) }),
  },
  {
    op: "e2_task_price",
    domain: "E",
    action: "调整任务单价",
    amplifies: true, // 单价↑放大(前端可覆盖)
    type: "fund",
    gateLabel: "门槛者",
    targetType: "device_task",
    buildCommand: (ctx) => ({ domain: "E", op: "e2_task_price",
      params: { taskId: String(ctx.taskId), price: ctx.price } }),
    buildTarget: (ctx) => ({ domain: "E", type: "device_task", id: String(ctx.taskId) }),
  },
  {
    op: "e2_task_status",
    domain: "E",
    action: "调整任务状态",
    amplifies: false,
    type: "param",
    gateLabel: "门槛者",
    targetType: "device_task",
    buildCommand: (ctx) => ({ domain: "E", op: "e2_task_status",
      params: { taskId: String(ctx.taskId), status: String(ctx.status) } }),
    buildTarget: (ctx) => ({ domain: "E", type: "device_task", id: String(ctx.taskId) }),
  },
  {
    op: "e2_task_delete",
    domain: "E",
    action: "删除设备任务",
    amplifies: false,
    type: "sos",
    gateLabel: "门槛者",
    targetType: "device_task",
    buildCommand: (ctx) => ({ domain: "E", op: "e2_task_delete",
      params: { taskId: String(ctx.taskId) } }),
    buildTarget: (ctx) => ({ domain: "E", type: "device_task", id: String(ctx.taskId) }),
  },
  // E3 生命周期(e3 config/tradein/restore)
  {
    op: "e3_config",
    domain: "E",
    action: "更新 E3 生命周期配置",
    amplifies: false,
    type: "param",
    gateLabel: "门槛者",
    targetType: "device_e3_config",
    buildCommand: (ctx) => ({ domain: "E", op: "e3_config",
      params: { key: String(ctx.key), value: String(ctx.value) } }),
    buildTarget: (ctx) => ({ domain: "E", type: "device_e3_config", id: String(ctx.key) }),
  },
  {
    op: "e3_config_batch",
    domain: "E",
    action: "批量更新 E3 生命周期配置",
    amplifies: false,
    type: "param",
    gateLabel: "门槛者",
    targetType: "device_e3_config",
    buildCommand: (ctx) => ({ domain: "E", op: "e3_config_batch", params: { values: ctx.values } }),
    buildTargets: (ctx) =>
      Object.keys((ctx.values as Record<string, unknown>) ?? {})
        .sort()
        .map((key) => ({ domain: "E", type: "device_e3_config", id: key })),
    buildTarget: (ctx) => ({
      domain: "E",
      type: "device_e3_config",
      id: Object.keys((ctx.values as Record<string, unknown>) ?? {}).sort()[0] ?? "__E3_BATCH__",
    }),
  },
  {
    op: "e3_tradein",
    domain: "E",
    action: "以旧换新/处置设备",
    amplifies: true, // 默认 recycle/replace 补偿放大;前端按 operation=deactivate 覆盖为 false(收缩方向)
    type: "fund",
    gateLabel: "门槛者",
    targetType: "device",
    buildCommand: (ctx) => ({ domain: "E", op: "e3_tradein",
      params: { operation: String(ctx.operation), deviceId: ctx.deviceId } }),
    buildTarget: (ctx) => ({ domain: "E", type: "device", id: String(ctx.deviceId) }),
  },
  {
    op: "e3_restore",
    domain: "E",
    action: "恢复设备计息",
    amplifies: true, // 恢复计息放大负债
    type: "fund",
    gateLabel: "门槛者",
    targetType: "device",
    buildCommand: (ctx) => ({ domain: "E", op: "e3_restore",
      params: { deviceId: ctx.deviceId } }),
    buildTarget: (ctx) => ({ domain: "E", type: "device", id: String(ctx.deviceId) }),
  },
  // E4 订单(e4 refund/cancel/terminal/state)
  {
    op: "e4_order_refund",
    domain: "E",
    action: "退款设备订单",
    amplifies: true, // 硬=true,直接资金 postLedgerEntry REFUND IN
    type: "fund",
    gateLabel: "门槛者",
    targetType: "device_order",
    buildCommand: (ctx) => ({ domain: "E", op: "e4_order_refund",
      params: { orderNo: String(ctx.orderNo) } }),
    buildTarget: (ctx) => ({ domain: "E", type: "device_order", id: String(ctx.orderNo) }),
  },
  {
    op: "e4_order_cancel",
    domain: "E",
    action: "取消设备订单",
    amplifies: false, // 取消=退款收缩
    type: "fund",
    gateLabel: "门槛者",
    targetType: "device_order",
    buildCommand: (ctx) => ({ domain: "E", op: "e4_order_cancel",
      params: { orderNo: String(ctx.orderNo) } }),
    buildTarget: (ctx) => ({ domain: "E", type: "device_order", id: String(ctx.orderNo) }),
  },
  {
    op: "e4_order_terminal",
    domain: "E",
    action: "终止设备订单",
    amplifies: false,
    type: "param",
    gateLabel: "门槛者",
    targetType: "device_order",
    buildCommand: (ctx) => ({ domain: "E", op: "e4_order_terminal",
      params: { orderNo: String(ctx.orderNo), terminalState: String(ctx.terminalState) } }),
    buildTarget: (ctx) => ({ domain: "E", type: "device_order", id: String(ctx.orderNo) }),
  },
  {
    op: "e4_order_state",
    domain: "E",
    action: "更新订单状态",
    amplifies: false,
    type: "param",
    gateLabel: "门槛者",
    targetType: "device_order",
    buildCommand: (ctx) => ({ domain: "E", op: "e4_order_state",
      params: { orderNo: String(ctx.orderNo), state: String(ctx.state) } }),
    buildTarget: (ctx) => ({ domain: "E", type: "device_order", id: String(ctx.orderNo) }),
  },
  // E5 运维(e5 datacenter create/update/delete/pause/resume)
  {
    op: "e5_datacenter_create",
    domain: "E",
    action: "新建数据中心",
    amplifies: false,
    type: "param",
    gateLabel: "门槛者",
    targetType: "device_datacenter",
    buildCommand: (ctx) => ({ domain: "E", op: "e5_datacenter_create",
      params: { dcLocation: String(ctx.dcLocation), regionLabel: String(ctx.regionLabel),
        status: String(ctx.status), sortOrder: ctx.sortOrder } }),
    buildTarget: (ctx) => ({ domain: "E", type: "device_datacenter", id: String(ctx.dcLocation) }),
  },
  {
    op: "e5_datacenter_update",
    domain: "E",
    action: "更新数据中心",
    amplifies: false,
    type: "param",
    gateLabel: "门槛者",
    targetType: "device_datacenter",
    buildCommand: (ctx) => ({ domain: "E", op: "e5_datacenter_update",
      params: { dcLocation: String(ctx.dcLocation), regionLabel: String(ctx.regionLabel),
        status: String(ctx.status), sortOrder: ctx.sortOrder } }),
    buildTarget: (ctx) => ({ domain: "E", type: "device_datacenter", id: String(ctx.dcLocation) }),
  },
  {
    op: "e5_datacenter_delete",
    domain: "E",
    action: "删除数据中心",
    amplifies: false,
    type: "sos",
    gateLabel: "门槛者",
    targetType: "device_datacenter",
    buildCommand: (ctx) => ({ domain: "E", op: "e5_datacenter_delete",
      params: { dcLocation: String(ctx.dcLocation) } }),
    buildTarget: (ctx) => ({ domain: "E", type: "device_datacenter", id: String(ctx.dcLocation) }),
  },
  {
    op: "e5_datacenter_pause",
    domain: "E",
    action: "暂停数据中心派单",
    amplifies: false, // 暂停=收缩(resume 见 e5_datacenter_resume)
    type: "sos",
    gateLabel: "门槛者",
    targetType: "device_datacenter",
    buildCommand: (ctx) => ({ domain: "E", op: "e5_datacenter_pause",
      params: { dcLocation: String(ctx.dcLocation) } }),
    buildTarget: (ctx) => ({ domain: "E", type: "device_datacenter", id: String(ctx.dcLocation) }),
  },
  {
    op: "e5_datacenter_resume",
    domain: "E",
    action: "恢复数据中心派单",
    amplifies: true, // 恢复派单放大
    type: "fund",
    gateLabel: "门槛者",
    targetType: "device_datacenter",
    buildCommand: (ctx) => ({ domain: "E", op: "e5_datacenter_resume",
      params: { dcLocation: String(ctx.dcLocation) } }),
    buildTarget: (ctx) => ({ domain: "E", type: "device_datacenter", id: String(ctx.dcLocation) }),
  },
  // E6 算力(e6 compute_config)
  {
    op: "e6_compute_config",
    domain: "E",
    action: "更新算力配置参数",
    amplifies: false,
    type: "param",
    gateLabel: "门槛者",
    targetType: "e6_compute_config",
    buildCommand: (ctx) => ({ domain: "E", op: "e6_compute_config",
      params: { paramKey: String(ctx.paramKey), value: String(ctx.value) } }),
    buildTarget: (ctx) => ({ domain: "E", type: "e6_compute_config", id: String(ctx.paramKey) }),
  },
  // —— H 域增长(批 7) ——
  // H1 phase 控制(control/override)
  {
    op: "h1_phase_control",
    domain: "H",
    action: "Phase 切换控制",
    amplifies: false, // 配置/状态变更,不动资金
    type: "param",
    gateLabel: "门槛者",
    targetType: "growth_phase_control",
    buildCommand: (ctx) => ({ domain: "H", op: "h1_phase_control",
      params: { controlKey: String(ctx.controlKey), value: String(ctx.value) } }),
    buildTarget: (ctx) => ({ domain: "H", type: "growth_phase_control", id: String(ctx.controlKey) }),
  },
  {
    op: "h1_phase_override",
    domain: "H",
    action: "撤销 Phase override",
    amplifies: false, // 配置标记,不动资金
    type: "param",
    gateLabel: "门槛者",
    targetType: "growth_phase_override",
    buildCommand: (ctx) => ({ domain: "H", op: "h1_phase_override",
      params: { overrideId: String(ctx.overrideId), disabled: Boolean(ctx.disabled) } }),
    buildTarget: (ctx) => ({ domain: "H", type: "growth_phase_override", id: String(ctx.overrideId) }),
  },
  // H2 trial 会话(cancel/charge 共享 trial_session:{sid} 互斥锁)
  {
    op: "h2_trial_cancel",
    domain: "H",
    action: "强制取消试用会话",
    amplifies: false, // 状态变更,不动资金
    type: "sos",
    gateLabel: "门槛者",
    targetType: "trial_session",
    buildCommand: (ctx) => ({ domain: "H", op: "h2_trial_cancel",
      params: { sid: String(ctx.sid) } }),
    buildTarget: (ctx) => ({ domain: "H", type: "trial_session", id: String(ctx.sid) }),
  },
  {
    op: "h2_trial_charge",
    domain: "H",
    action: "强制触发试用扣款",
    amplifies: true, // 硬=true,直接动 USDT 台账(postLedgerEntry OUT,金额由 trialChargeAmount() 实时算)
    type: "fund",
    gateLabel: "门槛者",
    targetType: "trial_session",
    buildCommand: (ctx) => ({ domain: "H", op: "h2_trial_charge",
      params: { sid: String(ctx.sid) } }),
    buildTarget: (ctx) => ({ domain: "H", type: "trial_session", id: String(ctx.sid) }),
  },
  // H5 checkin 规则(ruleKey 短形式:baseline/bonus7/p15/p2/broken;后端 raw=canonical,normalizeCheckInRuleKey 有别名但 op 表用短形式)
  {
    op: "h5_checkin_rule",
    domain: "H",
    action: "签到规则调整",
    amplifies: false, // 配置变更,不动资金
    type: "param",
    gateLabel: "门槛者",
    targetType: "checkin_rule",
    buildCommand: (ctx) => ({ domain: "H", op: "h5_checkin_rule",
      params: { ruleKey: String(ctx.ruleKey), value: String(ctx.value) } }),
    buildTarget: (ctx) => ({ domain: "H", type: "checkin_rule", id: String(ctx.ruleKey) }),
  },
  // —— I 域内容(批 8) ——
  // buildCommand params 严格对齐后端 OpsTrustDisclosureService.replay(委托架构:I3/I7 委托另 2 service)。
  // I3 通知优先级 CAP(updateCapRule · tier 锁 · amplifies false)
  {
    op: "i3_cap_adjust",
    domain: "I",
    action: "调整通知优先级 CAP",
    amplifies: false, // 容量配置,不动资金
    type: "param",
    gateLabel: "门槛者",
    targetType: "notification_cap",
    buildCommand: (ctx) => ({ domain: "I", op: "i3_cap_adjust",
      params: { tier: String(ctx.tier), cap: String(ctx.cap) } }),
    buildTarget: (ctx) => ({ domain: "I", type: "notification_cap", id: String(ctx.tier) }),
  },
  // I4 信任版块 publish/rollback/archive 共享 trust_section:{sectionKey} 锁(1 op + action 分发,replay switch action)
  {
    op: "i4_trust_section_manage",
    domain: "I",
    action: "信任版块发布/回滚/下架",
    amplifies: false, // 对外内容,不动账本
    type: "param",
    gateLabel: "门槛者",
    targetType: "trust_section",
    buildCommand: (ctx) => ({ domain: "I", op: "i4_trust_section_manage",
      params: {
        sectionKey: String(ctx.sectionKey),
        action: String(ctx.action),
        version: ctx.version != null ? String(ctx.version) : null, // publish 用
        targetVersion: ctx.targetVersion != null ? String(ctx.targetVersion) : null, // rollback 用
      } }),
    buildTarget: (ctx) => ({ domain: "I", type: "trust_section", id: String(ctx.sectionKey) }),
  },
  // I5 披露发布(publishDisclosure · 法域 jurisdiction 锁 · amplifies false)
  {
    op: "i4_disclosure_publish",
    domain: "I",
    action: "发布披露新版",
    amplifies: false, // 条款重签非熔断,不动账本
    type: "param",
    gateLabel: "门槛者",
    targetType: "disclosure_jurisdiction",
    buildCommand: (ctx) => ({ domain: "I", op: "i4_disclosure_publish",
      params: {
        jurisdiction: String(ctx.jurisdiction),
        version: String(ctx.version),
        languageScope: String(ctx.languageScope ?? "en+zh"),
        effectiveDate: String(ctx.effectiveDate ?? ""),
        requiresReack: ctx.requiresReack ?? true,
        zh: String(ctx.zh ?? ""),
        en: String(ctx.en ?? ""),
      } }),
    buildTarget: (ctx) => ({ domain: "I", type: "disclosure_jurisdiction", id: String(ctx.jurisdiction) }),
  },
  // I5 受限动作范围调整(updateGateScope · 全仓单例锁 restricted-actions · amplifies 放松资金类合规拦截)
  {
    op: "i4_gate_adjust",
    domain: "I",
    action: "调整披露受限动作范围",
    amplifies: true, // 移出范围 = 放松合规拦截;前端按纳入方向可覆盖为 false
    type: "param",
    gateLabel: "门槛者",
    targetType: "disclosure_gate",
    buildCommand: (ctx) => ({ domain: "I", op: "i4_gate_adjust",
      params: { scope: String(ctx.scope) } }),
    buildTarget: () => ({ domain: "I", type: "disclosure_gate", id: "restricted-actions" }),
  },
  // I7 课程奖励调整(updateCourseReward · courseId 锁 · amplifies 放大未来 NEX 流出,B1 红线前置)
  {
    op: "i7_course_reward_adjust",
    domain: "I",
    action: "课程奖励调整",
    amplifies: true, // rewardNex↑ 放大 NEX 流出
    type: "fund",
    gateLabel: "门槛者",
    targetType: "learning_course",
    buildCommand: (ctx) => ({ domain: "I", op: "i7_course_reward_adjust",
      params: { courseId: String(ctx.courseId), rewardNex: ctx.rewardNex } }),
    buildTarget: (ctx) => ({ domain: "I", type: "learning_course", id: String(ctx.courseId) }),
  },
  // —— F 域网络(批 9) ——
  // 4 polymorphic op:后端 OpsTeamService 单端点 /commissions/config/{key} 按 key 分发,
  // replay switch 4 op 全部 params {key, value}(commit afe51f2)。锁 target id 从 key 派生(对齐后端查锁 countActiveByTarget)。
  // f_config: ACTIVE_KEYS 数值政策(directRoyaltyPct/binary-rate/pool-ratio 等)。amplifies true(资金类政策放大佣金流出)。
  {
    op: "f_config",
    domain: "F",
    action: "网络佣金政策参数调整",
    amplifies: true, // 资金类政策放大(royalty/match/pool)
    type: "fund",
    gateLabel: "门槛者",
    targetType: "team_config",
    buildCommand: (ctx) => ({ domain: "F", op: "f_config",
      params: { key: String(ctx.key), value: String(ctx.value) } }),
    // 后端查锁 countActiveByTarget("F","team_config",key) → id = key
    buildTarget: (ctx) => ({ domain: "F", type: "team_config", id: String(ctx.key) }),
  },
  // f_ui_config: UI keys toggle/文案(F.vrank.permanent/F.binary.paused/F.leaderboard.paused 等)。amplifies false。
  {
    op: "f_ui_config",
    domain: "F",
    action: "网络 UI 开关/文案配置",
    amplifies: false, // toggle/文案,不动资金
    type: "param",
    gateLabel: "门槛者",
    targetType: "ui_config",
    buildCommand: (ctx) => ({ domain: "F", op: "f_ui_config",
      params: { key: String(ctx.key), value: String(ctx.value) } }),
    // 后端查锁 countActiveByTarget("F","ui_config",key) → id = key
    buildTarget: (ctx) => ({ domain: "F", type: "ui_config", id: String(ctx.key) }),
  },
  // f_unilevel_rule: F.unilevel.L{n}(usdtRate) / F.unilevel.nex.L{n}(nexPerUsd)。amplifies true(费率放大佣金流出)。
  {
    op: "f_unilevel_rule",
    domain: "F",
    action: "层级费率调整",
    amplifies: true, // 费率放大佣金流出
    type: "fund",
    gateLabel: "门槛者",
    targetType: "unilevel_rule",
    buildCommand: (ctx) => ({ domain: "F", op: "f_unilevel_rule",
      params: { key: String(ctx.key), value: String(ctx.value) } }),
    // 后端查锁 countActiveByTarget("F","unilevel_rule","L"+layerNo) → id 从 key 解析 L+layerNo
    // F.unilevel.L3 → "L3", F.unilevel.nex.L3 → "L3"(对齐后端 unilevelLayerNo(key)+"L")
    buildTarget: (ctx) => {
      const m = String(ctx.key).match(/F\.unilevel\.(?:nex\.)?L(\d+)/);
      return { domain: "F", type: "unilevel_rule", id: m ? "L" + m[1] : String(ctx.key) };
    },
  },
  // f_commission_status: F.commission.{eventId}.status(state)。amplifies true ⚠ 动资金 postLedgerEntry(解锁放大可提余额)。
  {
    op: "f_commission_status",
    domain: "F",
    action: "佣金事件处置",
    amplifies: true, // 硬=true,动资金 postLedgerEntry(解锁方向 IN/PENDING 放大可提余额)
    type: "fund",
    gateLabel: "门槛者",
    targetType: "commission_event",
    buildCommand: (ctx) => ({ domain: "F", op: "f_commission_status",
      params: { key: String(ctx.key), value: String(ctx.value) } }),
    // 后端查锁 countActiveByTarget("F","commission_event",eventId) → id 从 key 解析 eventId
    // F.commission.{eventId}.status → eventId(对齐后端 commissionStatusEventId(key))
    buildTarget: (ctx) => {
      const key = String(ctx.key);
      const prefix = "F.commission.";
      const suffix = ".status";
      let id = key;
      if (key.startsWith(prefix) && key.endsWith(suffix)) {
        id = key.substring(prefix.length, key.length - suffix.length);
      }
      return { domain: "F", type: "commission_event", id };
    },
  },
  // —— L 域 BI(批 9) ——
  // l5_task_approve: OpsBiService.reportAction(reportId,"APPROVE")。锁 report/reportId。amplifies false(状态推进非资金)。
  {
    op: "l5_task_approve",
    domain: "L",
    action: "审批放行导出/监管报告",
    amplifies: false, // 状态推进非资金
    type: "param",
    gateLabel: "门槛者",
    targetType: "report",
    buildCommand: (ctx) => ({ domain: "L", op: "l5_task_approve",
      params: { reportId: String(ctx.reportId) } }),
    buildTarget: (ctx) => ({ domain: "L", type: "report", id: String(ctx.reportId) }),
  },
];

export function findHighOp(op: string): HighOpDef | undefined {
  return HIGH_OPS.find((o) => o.op === op);
}
