export type DomainCode = "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M";

export interface ReplayCommand {
  domain: string;
  op: string;
  params: Record<string, unknown>;
}
export interface LockTarget {
  domain: string;
  type: string;
  id: string;
}
export interface HighOpDef {
  op: string;
  domain: DomainCode;
  action: string;
  amplifies: boolean;
  type: "fund" | "param" | "acct" | "sos";
  gateLabel: string;
  targetType: string; // 锁目标 type
  buildCommand: (ctx: Record<string, unknown>) => ReplayCommand;
  buildTarget: (ctx: Record<string, unknown>) => LockTarget;
  buildTargets?: (ctx: Record<string, unknown>) => LockTarget[]; // 多锁(batch_kill/emergency_block 用)
}

/** 批 0:D2 提现放行/解冻。其余域 HIGH 动作分批补登记。 */
export const HIGH_OPS: HighOpDef[] = [
  {
    op: "d2_withdraw_approve",
    domain: "D",
    action: "放行提现",
    amplifies: true,
    type: "fund",
    gateLabel: "财务 / 超管",
    targetType: "withdrawal",
    buildCommand: (ctx) => ({
      domain: "D",
      op: "d2_withdraw_approve",
      params: { withdrawalNo: ctx.withdrawalNo, action: "APPROVE" },
    }),
    buildTarget: (ctx) => ({ domain: "D", type: "withdrawal", id: String(ctx.withdrawalNo) }),
  },
  {
    op: "d2_withdraw_unfreeze",
    domain: "D",
    action: "解冻提现",
    amplifies: true,
    type: "fund",
    gateLabel: "财务 / 超管",
    targetType: "withdrawal",
    buildCommand: (ctx) => ({
      domain: "D",
      op: "d2_withdraw_unfreeze",
      params: { withdrawalNo: ctx.withdrawalNo, action: "UNFREEZE" },
    }),
    buildTarget: (ctx) => ({ domain: "D", type: "withdrawal", id: String(ctx.withdrawalNo) }),
  },
  // —— A 域账号治理(批 1) ——
  {
    op: "a1_account_create",
    domain: "A",
    action: "新建运营账号",
    amplifies: false,
    type: "acct",
    gateLabel: "超管",
    targetType: "account",
    buildCommand: (ctx) => ({
      domain: "A",
      op: "a1_account_create",
      params: {
        username: ctx.username,
        displayName: ctx.displayName,
        email: ctx.email ?? null,
        role: ctx.role,
        initialPassword: ctx.initialPassword,
      },
    }),
    buildTarget: (ctx) => ({ domain: "A", type: "account", id: String(ctx.username) }),
  },
  {
    op: "a1_account_status_update",
    domain: "A",
    action: "启用/禁用账号",
    amplifies: false,
    type: "acct",
    gateLabel: "超管",
    targetType: "account",
    buildCommand: (ctx) => ({
      domain: "A",
      op: "a1_account_status_update",
      params: { accountId: String(ctx.accountId), status: ctx.status },
    }),
    buildTarget: (ctx) => ({ domain: "A", type: "account", id: String(ctx.accountId) }),
  },
  {
    op: "a1_account_change_role",
    domain: "A",
    action: "变更角色",
    amplifies: false,
    type: "acct",
    gateLabel: "超管",
    targetType: "account",
    buildCommand: (ctx) => ({
      domain: "A",
      op: "a1_account_change_role",
      params: { accountId: String(ctx.accountId), role: ctx.role },
    }),
    buildTarget: (ctx) => ({ domain: "A", type: "account", id: String(ctx.accountId) }),
  },
  {
    op: "a1_account_reset_2fa",
    domain: "A",
    action: "重置双因子",
    amplifies: false,
    type: "acct",
    gateLabel: "超管",
    targetType: "account",
    buildCommand: (ctx) => ({
      domain: "A",
      op: "a1_account_reset_2fa",
      params: { accountId: String(ctx.accountId) },
    }),
    buildTarget: (ctx) => ({ domain: "A", type: "account", id: String(ctx.accountId) }),
  },
  {
    op: "a1_account_delete",
    domain: "A",
    action: "删除账号",
    amplifies: false,
    type: "acct",
    gateLabel: "超管",
    targetType: "account",
    buildCommand: (ctx) => ({
      domain: "A",
      op: "a1_account_delete",
      params: { accountId: String(ctx.accountId) },
    }),
    buildTarget: (ctx) => ({ domain: "A", type: "account", id: String(ctx.accountId) }),
  },
  {
    op: "a1_account_update_profile",
    domain: "A",
    action: "编辑账号资料",
    amplifies: false,
    type: "acct",
    gateLabel: "超管",
    targetType: "account",
    buildCommand: (ctx) => ({
      domain: "A",
      op: "a1_account_update_profile",
      params: {
        accountId: String(ctx.accountId),
        username: ctx.username,
        displayName: ctx.displayName,
        email: ctx.email ?? null,
      },
    }),
    buildTarget: (ctx) => ({ domain: "A", type: "account", id: String(ctx.accountId) }),
  },
  {
    op: "a1_account_force_logout",
    domain: "A",
    action: "强制登出",
    amplifies: false,
    type: "acct",
    gateLabel: "超管",
    targetType: "account",
    buildCommand: (ctx) => ({
      domain: "A",
      op: "a1_account_force_logout",
      params: { accountId: String(ctx.accountId) },
    }),
    buildTarget: (ctx) => ({ domain: "A", type: "account", id: String(ctx.accountId) }),
  },
  {
    op: "a1_security_baseline_update",
    domain: "A",
    action: "调整安全基线",
    amplifies: false,
    type: "param",
    gateLabel: "超管",
    targetType: "baseline",
    buildCommand: (ctx) => ({
      domain: "A",
      op: "a1_security_baseline_update",
      params: { baselineKey: String(ctx.baselineKey), value: String(ctx.value) },
    }),
    buildTarget: (ctx) => ({ domain: "A", type: "baseline", id: String(ctx.baselineKey) }),
  },
  // —— C 域用户操作(批 2) ——
  {
    op: "c4_kyc_status_change",
    domain: "C",
    action: "KYC 状态变更",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "user",
    buildCommand: (ctx) => ({
      domain: "C",
      op: "c4_kyc_status_change",
      params: { userId: Number(ctx.userId), status: ctx.status },
    }),
    buildTarget: (ctx) => ({ domain: "C", type: "user", id: String(ctx.userId) }),
  },
  {
    op: "c5_2fa_disable",
    domain: "C",
    action: "关闭 2FA",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "user",
    buildCommand: (ctx) => ({
      domain: "C",
      op: "c5_2fa_disable",
      params: { userId: Number(ctx.userId) },
    }),
    buildTarget: (ctx) => ({ domain: "C", type: "user", id: String(ctx.userId) }),
  },
  {
    op: "c5_password_reset",
    domain: "C",
    action: "密码重置",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "user",
    buildCommand: (ctx) => ({
      domain: "C",
      op: "c5_password_reset",
      params: { userId: Number(ctx.userId) },
    }),
    buildTarget: (ctx) => ({ domain: "C", type: "user", id: String(ctx.userId) }),
  },
  {
    op: "c5_user_unlock",
    domain: "C",
    action: "解除锁定",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "user",
    buildCommand: (ctx) => ({
      domain: "C",
      op: "c5_user_unlock",
      params: { userId: Number(ctx.userId) },
    }),
    buildTarget: (ctx) => ({ domain: "C", type: "user", id: String(ctx.userId) }),
  },
  {
    op: "c2_account_freeze",
    domain: "C",
    action: "冻结账户",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "user",
    buildCommand: (ctx) => ({
      domain: "C",
      op: "c2_account_freeze",
      params: { userId: Number(ctx.userId), status: "FROZEN" },
    }),
    buildTarget: (ctx) => ({ domain: "C", type: "user", id: String(ctx.userId) }),
  },
  {
    op: "c2_account_unfreeze",
    domain: "C",
    action: "恢复账户",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "user",
    buildCommand: (ctx) => ({
      domain: "C",
      op: "c2_account_unfreeze",
      params: { userId: Number(ctx.userId), status: "ACTIVE" },
    }),
    buildTarget: (ctx) => ({ domain: "C", type: "user", id: String(ctx.userId) }),
  },
  {
    op: "c2_session_revoke_all",
    domain: "C",
    action: "全部踢线",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "user",
    buildCommand: (ctx) => ({
      domain: "C",
      op: "c2_session_revoke_all",
      params: { userId: Number(ctx.userId) },
    }),
    buildTarget: (ctx) => ({ domain: "C", type: "user", id: String(ctx.userId) }),
  },
  {
    op: "c5_session_revoke_one",
    domain: "C",
    action: "踢线(单会话)",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "session",
    buildCommand: (ctx) => ({
      domain: "C",
      op: "c5_session_revoke_one",
      params: { refreshTokenId: String(ctx.refreshTokenId) },
    }),
    buildTarget: (ctx) => ({ domain: "C", type: "session", id: String(ctx.refreshTokenId) }),
  },
  {
    op: "c2_impersonate_terminate",
    domain: "C",
    action: "终止模拟登录",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "impersonation",
    buildCommand: (ctx) => ({
      domain: "C",
      op: "c2_impersonate_terminate",
      params: { sessionNo: String(ctx.sessionNo) },
    }),
    buildTarget: (ctx) => ({ domain: "C", type: "impersonation", id: String(ctx.sessionNo) }),
  },
  {
    op: "c2_impersonate_start",
    domain: "C",
    action: "发起模拟登录",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "user",
    buildCommand: (ctx) => ({
      domain: "C",
      op: "c2_impersonate_start",
      params: { userId: Number(ctx.userId), ttlMinutes: Number(ctx.ttlMinutes ?? 30) },
    }),
    buildTarget: (ctx) => ({ domain: "C", type: "user", id: String(ctx.userId) }),
  },
  {
    op: "c3_adjust_approve",
    domain: "C",
    action: "通过资产调整",
    amplifies: false,
    type: "fund",
    gateLabel: "门槛者",
    targetType: "adjustment",
    buildCommand: (ctx) => ({
      domain: "C",
      op: "c3_adjust_approve",
      params: { adjustmentNo: String(ctx.adjustmentNo) },
    }),
    buildTarget: (ctx) => ({ domain: "C", type: "adjustment", id: String(ctx.adjustmentNo) }),
  },
  {
    op: "c3_adjust_reject",
    domain: "C",
    action: "驳回资产调整",
    amplifies: false,
    type: "fund",
    gateLabel: "门槛者",
    targetType: "adjustment",
    buildCommand: (ctx) => ({
      domain: "C",
      op: "c3_adjust_reject",
      params: { adjustmentNo: String(ctx.adjustmentNo) },
    }),
    buildTarget: (ctx) => ({ domain: "C", type: "adjustment", id: String(ctx.adjustmentNo) }),
  },
  {
    op: "c3_adjust_create",
    domain: "C",
    action: "创建资产调整",
    amplifies: false,
    type: "fund",
    gateLabel: "门槛者",
    targetType: "user",
    buildCommand: (ctx) => ({
      domain: "C",
      op: "c3_adjust_create",
      params: {
        userId: Number(ctx.userId),
        asset: ctx.asset,
        direction: ctx.direction,
        amount: String(ctx.amount),
        referenceType: ctx.referenceType ?? null,
        referenceId: ctx.referenceId ?? null,
      },
    }),
    buildTarget: (ctx) => ({ domain: "C", type: "user", id: String(ctx.userId) }),
  },
  {
    op: "c2_blocklist_upsert",
    domain: "C",
    action: "名单信任/禁入",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "accountlist",
    buildCommand: (ctx) => ({
      domain: "C",
      op: "c2_blocklist_upsert",
      params: { userId: Number(ctx.userId), kind: ctx.kind, expiresAt: ctx.expiresAt ?? null },
    }),
    buildTarget: (ctx) => ({ domain: "C", type: "accountlist", id: String(ctx.userId) }),
  },
  // —— K 域风控(批 3) ——
  {
    op: "k1_cluster_freeze",
    domain: "K",
    action: "批量冻结关联账户",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "cluster",
    buildCommand: (ctx) => ({
      domain: "K",
      op: "k1_cluster_freeze",
      params: { clusterId: String(ctx.clusterId) },
    }),
    buildTarget: (ctx) => ({ domain: "K", type: "cluster", id: String(ctx.clusterId) }),
  },
  {
    op: "k1_cluster_release",
    domain: "K",
    action: "解除误判",
    amplifies: true,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "cluster",
    buildCommand: (ctx) => ({
      domain: "K",
      op: "k1_cluster_release",
      params: { clusterId: String(ctx.clusterId) },
    }),
    buildTarget: (ctx) => ({ domain: "K", type: "cluster", id: String(ctx.clusterId) }),
  },
  {
    op: "k1_cluster_cleared",
    domain: "K",
    action: "判定为正常",
    amplifies: true,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "cluster",
    buildCommand: (ctx) => ({
      domain: "K",
      op: "k1_cluster_cleared",
      params: { clusterId: String(ctx.clusterId) },
    }),
    buildTarget: (ctx) => ({ domain: "K", type: "cluster", id: String(ctx.clusterId) }),
  },
  {
    op: "k1_cluster_flag",
    domain: "K",
    action: "标记可疑账户簇",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "cluster",
    buildCommand: (ctx) => ({
      domain: "K",
      op: "k1_cluster_flag",
      params: { clusterId: String(ctx.clusterId) },
    }),
    buildTarget: (ctx) => ({ domain: "K", type: "cluster", id: String(ctx.clusterId) }),
  },
  {
    op: "k2_row_flag",
    domain: "K",
    action: "标记套利账户",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "arbitrage_row",
    buildCommand: (ctx) => ({
      domain: "K",
      op: "k2_row_flag",
      params: { rowId: String(ctx.rowId) },
    }),
    buildTarget: (ctx) => ({ domain: "K", type: "arbitrage_row", id: String(ctx.rowId) }),
  },
  {
    op: "k2_row_blockgift",
    domain: "K",
    action: "拦截新人礼",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "arbitrage_row",
    buildCommand: (ctx) => ({
      domain: "K",
      op: "k2_row_blockgift",
      params: { rowId: String(ctx.rowId) },
    }),
    buildTarget: (ctx) => ({ domain: "K", type: "arbitrage_row", id: String(ctx.rowId) }),
  },
  {
    op: "k2_row_boardflag",
    domain: "K",
    action: "标记刷榜账户",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "arbitrage_row",
    buildCommand: (ctx) => ({
      domain: "K",
      op: "k2_row_boardflag",
      params: { rowId: String(ctx.rowId) },
    }),
    buildTarget: (ctx) => ({ domain: "K", type: "arbitrage_row", id: String(ctx.rowId) }),
  },
  {
    op: "k2_row_freeze",
    domain: "K",
    action: "联动 K1 批量冻结",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "arbitrage_row",
    buildCommand: (ctx) => ({
      domain: "K",
      op: "k2_row_freeze",
      params: { rowId: String(ctx.rowId) },
    }),
    buildTarget: (ctx) => ({ domain: "K", type: "arbitrage_row", id: String(ctx.rowId) }),
  },
  {
    op: "k3_rule_create",
    domain: "K",
    action: "新建提现风控规则",
    amplifies: false,
    type: "param",
    gateLabel: "门槛者",
    targetType: "rule",
    buildCommand: (ctx) => ({
      domain: "K",
      op: "k3_rule_create",
      params: {
        dimension: ctx.dimension,
        conditionText: ctx.conditionText,
        action: ctx.action,
      },
    }),
    // 语义键:与后端 createWithdrawRule 归一化后的 dimension+":"+condition 一致
    // (前端 businessForm 产出的 condition 已是归一化格式)
    buildTarget: (ctx) => ({
      domain: "K",
      type: "rule",
      id: String(ctx.dimension) + ":" + String(ctx.conditionText),
    }),
  },
  {
    op: "k3_rule_toggle",
    domain: "K",
    action: "启用/停用规则",
    amplifies: false,
    type: "param",
    gateLabel: "门槛者",
    targetType: "rule",
    buildCommand: (ctx) => ({
      domain: "K",
      op: "k3_rule_toggle",
      params: { ruleId: String(ctx.ruleId), state: String(ctx.state) },
    }),
    buildTarget: (ctx) => ({ domain: "K", type: "rule", id: String(ctx.ruleId) }),
  },
  {
    op: "k3_rule_archive",
    domain: "K",
    action: "归档规则",
    amplifies: false,
    type: "param",
    gateLabel: "门槛者",
    targetType: "rule",
    buildCommand: (ctx) => ({
      domain: "K",
      op: "k3_rule_archive",
      params: { ruleId: String(ctx.ruleId) },
    }),
    buildTarget: (ctx) => ({ domain: "K", type: "rule", id: String(ctx.ruleId) }),
  },
  {
    op: "k4_user_override",
    domain: "K",
    action: "人工覆盖评分",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "score_user",
    buildCommand: (ctx) => ({
      domain: "K",
      op: "k4_user_override",
      params: { userNo: String(ctx.userNo), score: Number(ctx.score) },
    }),
    buildTarget: (ctx) => ({ domain: "K", type: "score_user", id: String(ctx.userNo) }),
  },
  {
    op: "k4_user_recompute",
    domain: "K",
    action: "重算回模型分",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "score_user",
    buildCommand: (ctx) => ({
      domain: "K",
      op: "k4_user_recompute",
      params: { userNo: String(ctx.userNo) },
    }),
    buildTarget: (ctx) => ({ domain: "K", type: "score_user", id: String(ctx.userNo) }),
  },
  {
    op: "k5_ticket_pass",
    domain: "K",
    action: "通过 KYC 复审",
    amplifies: true,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "ticket",
    buildCommand: (ctx) => ({
      domain: "K",
      op: "k5_ticket_pass",
      params: { ticketId: String(ctx.ticketId) },
    }),
    buildTarget: (ctx) => ({ domain: "K", type: "ticket", id: String(ctx.ticketId) }),
  },
  {
    op: "k5_ticket_reject",
    domain: "K",
    action: "驳回 KYC 复审",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "ticket",
    buildCommand: (ctx) => ({
      domain: "K",
      op: "k5_ticket_reject",
      params: { ticketId: String(ctx.ticketId) },
    }),
    buildTarget: (ctx) => ({ domain: "K", type: "ticket", id: String(ctx.ticketId) }),
  },
  {
    op: "k5_ticket_manual",
    domain: "K",
    action: "手动补触发复审",
    amplifies: false,
    type: "acct",
    gateLabel: "门槛者",
    targetType: "user",
    buildCommand: (ctx) => ({
      domain: "K",
      op: "k5_ticket_manual",
      params: { userNo: String(ctx.userNo) },
    }),
    buildTarget: (ctx) => ({ domain: "K", type: "user", id: String(ctx.userNo) }),
  },
  // —— J 域紧急与合规控制(批 4) ——
  {
    op: "j1_gate_kill",
    domain: "J",
    action: "熔断功能闸",
    amplifies: false,
    type: "sos",
    gateLabel: "门槛者",
    targetType: "gate",
    buildCommand: (ctx) => ({
      domain: "J",
      op: "j1_gate_kill",
      params: { gateKey: String(ctx.gateKey) },
    }),
    buildTarget: (ctx) => ({ domain: "J", type: "gate", id: String(ctx.gateKey) }),
  },
  {
    op: "j1_gate_resume",
    domain: "J",
    action: "恢复功能闸",
    amplifies: true,
    type: "sos",
    gateLabel: "门槛者",
    targetType: "gate",
    buildCommand: (ctx) => ({
      domain: "J",
      op: "j1_gate_resume",
      params: { gateKey: String(ctx.gateKey) },
    }),
    buildTarget: (ctx) => ({ domain: "J", type: "gate", id: String(ctx.gateKey) }),
  },
  {
    op: "j1_batch_kill",
    domain: "J",
    action: "应急批量熔断",
    amplifies: false,
    type: "sos",
    gateLabel: "门槛者",
    targetType: "gate",
    buildCommand: (ctx) => ({
      domain: "J",
      op: "j1_batch_kill",
      params: { keys: (ctx.keys as string[]) ?? [] },
    }),
    // 多锁:per-gate 一锁(对齐 spec §4.7 业务对象单位)
    buildTargets: (ctx) =>
      ((ctx.keys as string[]) ?? []).map((k) => ({ domain: "J", type: "gate", id: String(k) })),
    // 单锁兜底(若 usePropose 未支持 targets,用首个 gate;正常路径走 buildTargets)
    buildTarget: (ctx) => ({ domain: "J", type: "gate", id: String(((ctx.keys as string[]) ?? [""])[0]) }),
  },
  {
    op: "j2_country_manage",
    domain: "J",
    action: "国家管控",
    amplifies: false, // 默认封锁不放大;前端调用时按 status=allowed 覆盖为 true(解除方向)
    type: "param",
    gateLabel: "门槛者",
    targetType: "country",
    buildCommand: (ctx) => ({
      domain: "J",
      op: "j2_country_manage",
      params: { countryCode: String(ctx.countryCode), status: String(ctx.status) },
    }),
    buildTarget: (ctx) => ({ domain: "J", type: "country", id: String(ctx.countryCode) }),
  },
  {
    op: "j2_emergency_block",
    domain: "J",
    action: "应急批量封锁",
    amplifies: false,
    type: "sos",
    gateLabel: "门槛者",
    targetType: "country",
    buildCommand: (ctx) => ({
      domain: "J",
      op: "j2_emergency_block",
      params: { countries: (ctx.countries as string[]) ?? [] },
    }),
    buildTargets: (ctx) =>
      ((ctx.countries as string[]) ?? []).map((c) => ({ domain: "J", type: "country", id: String(c) })),
    buildTarget: (ctx) => ({ domain: "J", type: "country", id: String(((ctx.countries as string[]) ?? [""])[0]) }),
  },
  {
    op: "j3_alert_config",
    domain: "J",
    action: "篡改告警阈值配置",
    amplifies: false,
    type: "param",
    gateLabel: "门槛者",
    targetType: "alert_config",
    buildCommand: (ctx) => ({
      domain: "J",
      op: "j3_alert_config",
      params: { threshold: Number(ctx.threshold), feedK4: Boolean(ctx.feedK4) },
    }),
    buildTarget: () => ({ domain: "J", type: "alert_config", id: "default" }),
  },
  {
    op: "j4_playbook_execute",
    domain: "J",
    action: "执行应急剧本",
    amplifies: false,
    type: "sos",
    gateLabel: "门槛者",
    targetType: "playbook",
    buildCommand: (ctx) => ({
      domain: "J",
      op: "j4_playbook_execute",
      params: { code: String(ctx.code), emergency: Boolean(ctx.emergency ?? false) },
    }),
    buildTarget: (ctx) => ({ domain: "J", type: "playbook", id: String(ctx.code) }),
  },
  {
    op: "j4_playbook_rollback",
    domain: "J",
    action: "回滚剧本执行",
    amplifies: false,
    type: "sos",
    gateLabel: "门槛者",
    targetType: "playbook_execution",
    buildCommand: (ctx) => ({
      domain: "J",
      op: "j4_playbook_rollback",
      params: { code: String(ctx.code), executionId: String(ctx.executionId), emergency: false },
    }),
    buildTarget: (ctx) => ({ domain: "J", type: "playbook_execution", id: String(ctx.executionId) }),
  },
];

export function findHighOp(op: string): HighOpDef | undefined {
  return HIGH_OPS.find((o) => o.op === op);
}
