import { supportRequest, supportJson, supportObject, parseSupportId, parseSupportCount, parseSupportPage, supportWireId } from "./m-support-client.ts";
import { createPendingMutationStore, PENDING_MUTATION_TTL_MS, type PendingMutationRecord } from "./pending-mutation-store.ts";

const BASE = "/support-agents/groups";
const GROUP_STATES = ["ENABLED", "DISABLED", "ARCHIVED"] as const;
const QUAL_STATES = ["ENABLED", "DISABLED", "REMOVED"] as const;
export type QualificationKind = "SERVICE" | "SUPERVISOR";
export type GroupStatus = typeof GROUP_STATES[number];
export type QualificationStatus = typeof QUAL_STATES[number];
function bad(field: string): never { throw new Error(`SUPPORT_CONTRACT_MALFORMED:group.${field}`); }
function object(value: unknown, fields: string) { const r = supportObject(value, "group.object"); if (Object.keys(r).some(key => !fields.split(" ").includes(key))) bad("unexpectedField"); return r; }
function text(value: unknown): string { if (typeof value !== "string") bad("text"); return value; }
function nonempty(value: unknown): string { const result = text(value); if (!result.trim()) bad("empty"); return result; }
function bool(value: unknown): boolean { if (typeof value !== "boolean") bad("boolean"); return value; }
function enumeration<const T extends readonly string[]>(value: unknown, choices: T): T[number] { if (typeof value !== "string" || !choices.includes(value)) bad("enum"); return value as T[number]; }
function count(value: unknown): number { return parseSupportCount(value, "group.count"); }
function positive(value: unknown): number { const n = count(value); if (!n) bad("positive"); return n; }
function id(value: unknown): string { const result = parseSupportId(value, "group.id"); if (!/^[1-9]\d*$/.test(result)) bad("id"); return result; }
function nullableId(value: unknown): string | null { return value === null ? null : id(value); }
function array<T>(value: unknown, parse: (value: unknown) => T): T[] { if (!Array.isArray(value)) bad("array"); return value.map(parse); }
function unique<T>(rows: T[], key: (row: T) => string): T[] { if (new Set(rows.map(key)).size !== rows.length) bad("duplicate"); return rows; }
function reason(value: unknown): string { const result = text(value).trim(); if (Array.from(result).length < 8 || result.length > 200 || /[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/.test(result)) bad("reason"); return result; }
function name(value: unknown): string { const result = nonempty(value).trim(); if (result.length > 120) bad("name"); return result; }
export function accountVersion(value: unknown): number { const s = text(value); if (!/^(0|[1-9]\d*)$/.test(s) || BigInt(s) > BigInt(Number.MAX_SAFE_INTEGER)) bad("accountVersion"); return Number(s); }
export function parseSupportGroup(value: unknown) { const r = object(value, "id name supervisorAdminId status version"); return { id: id(r.id), name: name(r.name), supervisorAdminId: id(r.supervisorAdminId), status: enumeration(r.status, GROUP_STATES), version: positive(r.version) }; }
export type SupportGroup = ReturnType<typeof parseSupportGroup>;
export function parseGroupDetail(value: unknown) {
  const r = object(value, "group members memberCount routedCustomers pendingOperations blockers"), group = parseSupportGroup(r.group);
  const members = unique(array(r.members, value => { const m = object(value, "adminId version groupId accountStatus handoverRequired boundCustomers"); const groupId = id(m.groupId); if (groupId !== group.id) bad("memberGroup"); const handover = m.handoverRequired; if (handover !== 0 && handover !== 1 && typeof handover !== "boolean") bad("handover"); return { adminId: id(m.adminId), version: positive(m.version), groupId, accountStatus: count(m.accountStatus), handoverRequired: handover === true || handover === 1, boundCustomers: count(m.boundCustomers) }; }), m => m.adminId);
  const b = object(r.blockers, "members routedCustomers pendingOperations canExit nextSteps");
  const result = { group, members, memberCount: count(r.memberCount), routedCustomers: count(r.routedCustomers), pendingOperations: count(r.pendingOperations), blockers: { members: count(b.members), routedCustomers: count(b.routedCustomers), pendingOperations: count(b.pendingOperations), canExit: bool(b.canExit), nextSteps: array(b.nextSteps, text) } };
  if (result.memberCount !== members.length || result.blockers.members !== result.memberCount || result.blockers.routedCustomers !== result.routedCustomers || result.blockers.pendingOperations !== result.pendingOperations || result.blockers.canExit !== (result.memberCount === 0 && result.routedCustomers === 0 && result.pendingOperations === 0)) bad("blockers"); return result;
}
export type SupportGroupDetail = ReturnType<typeof parseGroupDetail>;
export function parseGroupMember(value: unknown) {
  const r = object(value, "adminId name accountStatus currentMember boundCustomers"), m = object(r.currentMember, "state id groupId version");
  const state = enumeration(m.state, ["AVAILABLE", "ABSENT", "UNKNOWN"] as const), memberId = nullableId(m.id), groupId = nullableId(m.groupId), version = m.version === null ? null : positive(m.version);
  if (state === "AVAILABLE" ? memberId === null || version === null : memberId !== null || groupId !== null || version !== null) bad("memberObservation");
  return { adminId: id(r.adminId), name: nonempty(r.name), accountStatus: count(r.accountStatus), currentMember: { state, id: memberId, groupId, version }, boundCustomers: count(r.boundCustomers) };
}
export type SupportGroupMember = ReturnType<typeof parseGroupMember>;
export function parseQualifications(value: unknown) {
  const r = object(value, "adminId name accountStatus accountVersion qualifications"); accountVersion(r.accountVersion);
  const qualifications = unique(array(r.qualifications, value => { const q = object(value, "kind state observationState id version"), kind = enumeration(q.kind, ["SERVICE", "SUPERVISOR"] as const), observationState = enumeration(q.observationState, ["AVAILABLE", "ABSENT", "UNKNOWN"] as const), state = q.state === null ? null : enumeration(q.state, QUAL_STATES), qualificationId = nullableId(q.id), version = q.version === null ? null : positive(q.version);
    if (observationState === "AVAILABLE" ? state === null || qualificationId === null || version === null : state !== null || qualificationId !== null || version !== null) bad("qualificationObservation"); return { kind, state, observationState, id: qualificationId, version }; }), q => q.kind);
  if (qualifications.length !== 2) bad("qualificationKinds"); return { adminId: id(r.adminId), name: nonempty(r.name), accountStatus: count(r.accountStatus), accountVersion: text(r.accountVersion), qualifications };
}
export type SupportQualifications = ReturnType<typeof parseQualifications>;
export function observedVersion(fact: { state?: string | null; observationState?: string; version: number | null }): number { const observed = fact.observationState ?? fact.state; if (observed === "ABSENT") return 0; if (observed !== "AVAILABLE" || fact.version === null) bad("unverifiedVersion"); return positive(fact.version); }
export type CreateGroupInput = { name: string; supervisorAdminId: string; reason: string };
export type RenameGroupInput = { name: string; expectedVersion: number; reason: string };
export type StatusGroupInput = { status: GroupStatus; expectedVersion: number; reason: string };
export type OwnerGroupInput = { supervisorAdminId: string; expectedVersion: number; reason: string };
export type MoveGroupInput = { targetGroupId: string | null; expectedMemberVersion: number; sourceGroupVersion: number | null; targetGroupVersion: number | null; reason: string };
export type QualificationInput = { qualificationKind: QualificationKind; state: QualificationStatus; expectedQualificationVersion: number; expectedAccountVersion: number; reason: string };
type GroupIntent = { kind: "CREATE"; payload: CreateGroupInput } | { kind: "RENAME"; targetId: string; payload: RenameGroupInput } | { kind: "STATUS"; targetId: string; payload: StatusGroupInput } | { kind: "OWNER"; targetId: string; payload: OwnerGroupInput } | { kind: "MEMBER"; targetId: string; payload: MoveGroupInput } | { kind: "QUALIFICATION"; targetId: string; payload: QualificationInput };
export type GroupPendingRecord = PendingMutationRecord & { actorId: number; intent: GroupIntent; label: string };
// Unresolved evidence outlives the server's 24h replay window; session storage ends with the tab.
export const groupPendingCommands = createPendingMutationStore<GroupPendingRecord>({ storageKey: "nexion-admin-support-group-commands-v1", ttlMs: Math.floor(Number.MAX_SAFE_INTEGER / 2), isValidRecord: r => Number.isSafeInteger(r.actorId) && r.actorId > 0 && !!r.intent && ["CREATE", "RENAME", "STATUS", "OWNER", "MEMBER", "QUALIFICATION"].includes(r.intent.kind) && !!r.intent.payload && typeof r.intent.payload.reason === "string" && typeof r.label === "string" });
export function canReplayGroupCommand(record: GroupPendingRecord, now = Date.now()): boolean { return now >= record.createdAt && now < record.createdAt + PENDING_MUTATION_TTL_MS; }
function key(value: string): string { if (!value || value.length > 96 || /[\x00-\x20\x7f]/.test(value)) bad("key"); return value; }
function groupNameInput(input: RenameGroupInput) { object(input, "name expectedVersion reason"); return { name: name(input.name), expectedVersion: positive(input.expectedVersion), reason: reason(input.reason) }; }
function changedGroup(value: unknown, target: string, expectedVersion: number, matches: (group: SupportGroup) => boolean) { const result = parseSupportGroup(value); if (result.id !== target || result.version <= expectedVersion || !matches(result)) bad("writeAcknowledgement"); return result; }
function parseQualificationWrites(value: unknown, target: string) { return unique(array(value, value => { const q = object(value, "id adminId qualificationKind state version startsAt"); if (id(q.adminId) !== target) bad("qualificationIdentity"); return { id: id(q.id), adminId: target, kind: enumeration(q.qualificationKind, ["SERVICE", "SUPERVISOR"] as const), state: enumeration(q.state, QUAL_STATES), version: positive(q.version), startsAt: text(q.startsAt) }; }), q => q.kind); }
export const supportGroupClient = {
  groups(signal?: AbortSignal): Promise<SupportGroup[]> { return supportRequest(BASE, value => unique(array(value, parseSupportGroup), g => g.id), { signal }); },
  detail(groupId: string, signal?: AbortSignal): Promise<SupportGroupDetail> { const target = id(groupId); return supportRequest(`${BASE}/${target}`, value => { const result = parseGroupDetail(value); if (result.group.id !== target) bad("detailIdentity"); return result; }, { signal }); },
  member(adminId: string, signal?: AbortSignal): Promise<SupportGroupMember> { const target = id(adminId); return supportRequest(`${BASE}/members/${target}`, value => { const result = parseGroupMember(value); if (result.adminId !== target) bad("memberIdentity"); return result; }, { signal }); },
  qualifications(adminId: string, signal?: AbortSignal): Promise<SupportQualifications> { const target = id(adminId); return supportRequest(`/support-agents/${target}/qualifications`, value => { const result = parseQualifications(value); if (result.adminId !== target) bad("qualificationIdentity"); return result; }, { signal }); },
  supervisors(signal?: AbortSignal) { return supportRequest(`${BASE}/supervisors`, value => { const r = object(value, "items supervisorCount memberCount peopleCount"); const items = unique(array(r.items, value => { const s = object(value, "adminId name state version accountStatus groupCount"); return { adminId: id(s.adminId), name: nonempty(s.name), state: enumeration(s.state, QUAL_STATES), version: positive(s.version), accountStatus: count(s.accountStatus), groupCount: count(s.groupCount) }; }), s => s.adminId); const result = { items, supervisorCount: count(r.supervisorCount), memberCount: count(r.memberCount), peopleCount: count(r.peopleCount) }; if (result.supervisorCount !== items.length || result.peopleCount < result.supervisorCount || result.peopleCount < result.memberCount || result.peopleCount > result.supervisorCount + result.memberCount) bad("supervisorCounts"); return result; }, { signal }); },
  candidates(options: { groupId?: string; pageNum: number; pageSize: number }, signal?: AbortSignal) { object(options, "groupId pageNum pageSize"); const params = new URLSearchParams({ pageNum: String(positive(options.pageNum)), pageSize: String(positive(options.pageSize)) }); if (options.pageSize > 100) bad("pageSize"); if (options.groupId !== undefined) params.set("groupId", id(options.groupId)); return supportRequest(`/support-agents/page?${params}`, value => { const result = parseSupportPage(value, entry => { const r = supportObject(entry, "group.candidate"); return { adminId: id(r.adminId), name: nonempty(r.name) }; }); if (result.pageNum !== options.pageNum || result.pageSize !== options.pageSize) bad("pageIdentity"); return result; }, { signal }); },
  command(commandKey: string, signal?: AbortSignal) { return supportRequest(`/support-workbench/commands/${encodeURIComponent(key(commandKey))}`, value => { const r = object(value, "status"); return { status: nonempty(r.status) }; }, { signal }); },
  createSupportGroup(input: CreateGroupInput, commandKey: string, signal?: AbortSignal) { object(input, "name supervisorAdminId reason"); const ownerId = id(input.supervisorAdminId), body = { name: name(input.name), supervisorAdminId: supportWireId(ownerId, "group.owner"), reason: reason(input.reason) }; return supportRequest(BASE, value => { const result = parseSupportGroup(value); if (result.name !== body.name || result.supervisorAdminId !== ownerId || result.status !== "ENABLED") bad("createAcknowledgement"); return result; }, supportJson("POST", body, key(commandKey), signal)); },
  renameSupportGroup(groupId: string, input: RenameGroupInput, commandKey: string, signal?: AbortSignal) { const target = id(groupId), body = groupNameInput(input); return supportRequest(`${BASE}/${target}/name`, value => changedGroup(value, target, body.expectedVersion, g => g.name === body.name), supportJson("PATCH", body, key(commandKey), signal)); },
  setSupportGroupStatus(groupId: string, input: StatusGroupInput, commandKey: string, signal?: AbortSignal) { const target = id(groupId); object(input, "status expectedVersion reason"); const body = { status: enumeration(input.status, GROUP_STATES), expectedVersion: positive(input.expectedVersion), reason: reason(input.reason) }; return supportRequest(`${BASE}/${target}/status`, value => changedGroup(value, target, body.expectedVersion, g => g.status === body.status), supportJson("PATCH", body, key(commandKey), signal)); },
  transferSupportGroupOwner(groupId: string, input: OwnerGroupInput, commandKey: string, signal?: AbortSignal) { const target = id(groupId), ownerId = id(input.supervisorAdminId); object(input, "supervisorAdminId expectedVersion reason"); const body = { supervisorAdminId: supportWireId(ownerId, "group.owner"), expectedVersion: positive(input.expectedVersion), reason: reason(input.reason) }; return supportRequest(`${BASE}/${target}/owner`, value => changedGroup(value, target, body.expectedVersion, g => g.supervisorAdminId === ownerId), supportJson("PATCH", body, key(commandKey), signal)); },
  moveSupportGroupMember(adminId: string, input: MoveGroupInput, commandKey: string, signal?: AbortSignal) { const target = id(adminId); object(input, "targetGroupId expectedMemberVersion sourceGroupVersion targetGroupVersion reason"); const targetGroupId = input.targetGroupId === null ? null : id(input.targetGroupId), body = { targetGroupId: targetGroupId === null ? null : supportWireId(targetGroupId, "group.target"), expectedMemberVersion: count(input.expectedMemberVersion), sourceGroupVersion: input.sourceGroupVersion === null ? null : positive(input.sourceGroupVersion), targetGroupVersion: input.targetGroupVersion === null ? null : positive(input.targetGroupVersion), reason: reason(input.reason) }; if (body.targetGroupId !== null && body.targetGroupVersion === null || body.targetGroupId === null && body.targetGroupVersion !== null) bad("targetVersion"); return supportRequest(`${BASE}/members/${target}`, value => { const r = object(value, "member boundCustomers"), m = object(r.member, "id agentAdminId groupId version startsAt"); if (id(m.agentAdminId) !== target || nullableId(m.groupId) !== targetGroupId || positive(m.version) <= body.expectedMemberVersion) bad("moveIdentity"); return { member: { id: id(m.id), adminId: target, groupId: nullableId(m.groupId), version: positive(m.version), startsAt: text(m.startsAt) }, boundCustomers: count(r.boundCustomers) }; }, supportJson("PATCH", body, key(commandKey), signal)); },
  setSupportQualification(adminId: string, input: QualificationInput, commandKey: string, signal?: AbortSignal) { const target = id(adminId); object(input, "qualificationKind state expectedQualificationVersion expectedAccountVersion reason"); const body = { qualificationKind: enumeration(input.qualificationKind, ["SERVICE", "SUPERVISOR"] as const), state: enumeration(input.state, QUAL_STATES), expectedQualificationVersion: count(input.expectedQualificationVersion), expectedAccountVersion: count(input.expectedAccountVersion), reason: reason(input.reason) }; return supportRequest(`/support-agents/${target}/qualification`, value => { const rows = parseQualificationWrites(value, target), changed = rows.find(q => q.kind === body.qualificationKind); if (!changed || changed.state !== body.state || changed.version <= body.expectedQualificationVersion) bad("qualificationAcknowledgement"); return rows; }, supportJson("PATCH", body, key(commandKey), signal)); },
};
