/**
 * 脚手架页「8 段规格」域定制提示。
 * 8 段固定标签取自 PRD 子模块模板;每域 8 条一句话提示取自 Ch3 §3.3 域职能,
 * 让未建页也能传达该模块「将控制什么」,而非空洞占位(反模板)。
 */
export const SECTION_LABELS: string[] = [
  "① 目的 & 对齐",
  "② 后台界面",
  "③ 可控参数",
  "④ 操作动作",
  "⑤ 接口",
  "⑥ 权限 & 审计",
  "⑦ 风控 & 联动",
  "⑧ 埋点",
];

/** domain code → 8 段提示(顺序对应 SECTION_LABELS)。 */
export const DOMAIN_HINTS: Record<string, string[]> = {
  A: [
    "RBAC / 审计 / 配置 / 埋点 — 全后台横切地基",
    "角色矩阵 · 审计流水 · feature flag 表",
    "角色权限位 · 幂等键 TTL · server time 源",
    "建角色 / 改权限 / 发 flag · 操作确认",
    "/admin/rbac · /admin/audit · /admin/config",
    "仅 superadmin · 全部写操作留痕",
    "服务端权威 · 改 flag 联动全域生效",
    "admin.role_changed · admin.config_updated",
  ],
  B: [
    "双账本 / 水位 / 漏斗 / 节奏 / 雷达 — 态势总览",
    "覆盖率 hero · 堆叠水位 · 漏斗图 · 雷达灯",
    "红线阈值 · 告警水位 · 雷达灵敏度",
    "调阈值(操作确认)· 钻取 · 导出快照",
    "/admin/dashboard/* 只读聚合端点",
    "全角色可读 · 阈值改动留痕",
    "兑付覆盖率红线前置 · 引用 D3 / K4",
    "只读看板 · 事件源自 A4 埋点流",
  ],
  C: [
    "检索 / 处置 / 资产 / KYC / 安全 / 注册风控",
    "用户表 · 画像卡 · 处置面板 · 会话列表",
    "OTP TTL · 锁定阈值 · 冻结原因码",
    "冻结/解冻 · 强制登出 · impersonate · 调资产",
    "/admin/users/* · /admin/users/:id/actions",
    "客服 + 风控 · impersonate 强审计",
    "资产调整操作确认 · 联动 K4 / C2 / D2",
    "admin.user_frozen · admin.balance_adjusted",
  ],
  D: [
    "充值对账 / 提现队列 / 资金池 / 账本 / 参数",
    "对账中心 · 提现队列 · 水位盘 · 账本审计",
    "日限 / 80% 上限 / fee / cooldown(随 Phase)",
    "批准/延迟/冻结提现 · 操作确认 · 补单",
    "/admin/withdrawals · /admin/recon · /admin/pool",
    "财务 + 风控 · 大额放行操作确认",
    "B1 覆盖率红线前置 · 联动 K3 / C4",
    "admin.withdrawal_reviewed · payout.*",
  ],
  E: [
    "商品 / 代际门 / 任务 / 生命周期 / Trade-in / 订单 / 运维",
    "SKU 表 · 定价详情 · 代际时间线 · 订单态机",
    "price / baseRate / stock · unlocksAtPhase · 衰减",
    "上架/调价/发代际 · 操作确认 · 退款",
    "/admin/products · /admin/orders · /admin/devices",
    "增长 + 客服 · 调价操作确认",
    "调价覆盖率核验 · 联动 H1 代际门",
    "admin.price_changed · order.state_changed",
  ],
  F: [
    "V-Rank / 版税 / 双轨 / 领导池 / 佣金 / 配额 / 大使 / 榜",
    "等级表 · 费率矩阵 · 双轨监控 · 佣金流水",
    "L1-L7 费率 · binaryDailyCap · 池比例",
    "调费率/封顶 · 审区域大使 · 操作确认",
    "/admin/ranks · /admin/commissions · /admin/binary",
    "增长运营 · 费率改动操作确认",
    "费率覆盖率核验 · 联动 H1 cap",
    "commission.* · admin.rate_changed",
  ],
  G: [
    "Staking / 兑换 / 行情 / Genesis / Premium / NEXv2 / 复投",
    "池配置 · 兑换风控 · 行情曲线 · Genesis 盘",
    "APY / penalty / caps · 分红率 · gate Phase",
    "调 APY/分红 · kill 开关 · 操作确认",
    "/admin/staking · /admin/exchange · /admin/genesis",
    "财务 + 增长 · APY / kill 操作确认",
    "放大流出红线前置 · 联动 B1 / J1",
    "stake.* · genesis.* · admin.apy_changed",
  ],
  H: [
    "Phase 调度 / 试用 / Quest / 活动 / 签到 / 里程碑",
    "Phase 仪表 · 10-dial 表 · 活动 CMS · Quest 表",
    "10 dial(月粒度)· cohort override · 倍率",
    "调 dial / 发活动 · 操作确认 · 排程",
    "/admin/phase · /admin/trial · /admin/events",
    "增长运营 · dial 改动操作确认",
    "Phase 权威源 · 派发 D5 / F3 / G5 联动",
    "trial.* · quest.* · admin.dial_changed",
  ],
  I: [
    "文案 / Nova / 通知 / 信任中心 / 披露 / i18n / 教程 / 客服支持",
    "文案池 · 推送 cadence · 模板库 · 披露版本 · 工单台",
    "A/B 权重 · cadence / cooldown · 披露版本号 · ticket SLA",
    "发文案/推送 · per-channel kill · 回复/关闭工单 · 操作确认",
    "/admin/copy · /admin/nova · /admin/disclosure · /admin/support",
    "内容/客服运营 · 披露版本与工单写动作留审计",
    "虚假宣传应急下架 · 支持升级回 C/D/E/G 业务域",
    "nova.* · disclosure.acked · admin.copy_published · support.ticket_replied",
  ],
  J: [
    "Kill 矩阵 / Geo-block / 篡改防御 / 应急 SOP",
    "7 闸开关网格 · geo 地图 · 篡改看板 · SOP",
    "kill 开关位 · geo 国家表 · 篡改阈值",
    "切 kill/geo · 强操作确认 · SOP 编排",
    "/admin/kill-switch · /admin/geo · /admin/tamper",
    "superadmin + 风控 · kill 强操作确认",
    "解 kill 前覆盖率核验 · 全域联动",
    "admin.killswitch_toggled · risk.tamper_detected",
  ],
  K: [
    "反多账户 / 套利刷量 / 提现风控 / 评分 / KYC 复审",
    "关联图 · 规则引擎 · 评分分布 · 复审队列",
    "去重阈值 · 规则权重 · 评分模型参数",
    "标记/拉黑/触发复审 · 操作确认",
    "/admin/risk/* · /admin/scoring",
    "风控 · 拉黑操作确认",
    "评分权威源 · 供 C1 / D2 复用",
    "risk.flagged · risk.score_updated",
  ],
  L: [
    "KPI / 漏斗 cohort / 财务 / 运营 / 导出",
    "8 KPI 卡 · 漏斗分析 · 报表 · 导出中心",
    "KPI 口径 · cohort 维度 · 导出范围",
    "跑查询/导出/订阅报表 · 审计导出",
    "/admin/bi/* · /admin/export",
    "全角色可读 · 导出留痕",
    "依赖 A4 事件流 · 只读分析",
    "admin.report_exported · admin.bi_query_run",
  ],
};

/** 域 ghost 表的合理化列名(脚手架占位表用,按域贴近真实)。 */
export const DOMAIN_GHOST_COLUMNS: Record<string, string[]> = {
  A: ["账号", "角色", "最近操作", "时间"],
  B: ["指标", "当前值", "环比", "状态"],
  C: ["用户ID", "注册时间", "KYC", "风险分"],
  D: ["单号", "金额", "状态", "处理人"],
  E: ["商品", "价格", "库存", "状态"],
  F: ["层级", "费率", "结算", "状态"],
  G: ["产品", "APY", "TVL", "状态"],
  H: ["参数", "当前值", "生效月", "状态"],
  I: ["模板", "渠道", "版本", "状态"],
  J: ["开关", "状态", "最近切换", "操作人"],
  K: ["命中规则", "用户", "评分", "处置"],
  L: ["报表", "周期", "口径", "导出"],
};
